### ISSUE TITLE
Google Analytics - Q4

### ISSUE THREAD

**Issue by agoode26** [Ebazhanov/linkedin-skill-assessments-quizzes#1000]
Q4. A user downloads a white paper with event tracking once in a single session. Another user downloads the same white paper three times in a single session. How many unique events are counted?
one <<<<<< Correct
three
two >>>> **_**I believe the answer is Two, not one. The unique event is any new user downloading the white paper. Two users downloaded the WP four times. We only care about unique events, so the answer is two, right?_**
four

I believe the answer is Two, not one. The unique event is any new user downloading the white paper. Two users downloaded the WP four times. We only care about unique events, so the answer is two, right?

**Comment by rradfar** [comment]
Thanks @agoode26. You are correct. The solution will be fixed in the next update.

**Comment by Ebazhanov** [comment]
@rradfar thank you for updates, FYI @agoode26 thank you for raising this issue the last changes is here https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/pull/1140/files
