### ISSUE TITLE
2 new questions for the git test

### ISSUE THREAD

**Issue by christiansgesp** [Ebazhanov/linkedin-skill-assessments-quizzes#1009]
Q 1. How would you configure Git to abort a commit if a smoke test script fails?
- Create a post-commit shell script that triggers the action.
- Create a post-commit hook to trigger the script.
- Create a pre-commit hook to trigger the script.
- Create a pree-commit shell script that triggers the action.

Q 2. Which use case is NOT a good candidate for a Git hook?
- state dependent environment changes
- continuous integration
- increasing code average
- enforcing commit rules

**I don't have the correct answers.**

**Comment by Ebazhanov** [comment]
@all-contributors please add @christiansgesp for code
