### ISSUE TITLE
New java questions

### ISSUE THREAD

**Issue by k-tipp** [Ebazhanov/linkedin-skill-assessments-quizzes#1024]
![grafik](https://user-images.githubusercontent.com/3494491/105501853-078e2180-5cc5-11eb-9b53-a49ffbad5e55.png)

![grafik](https://user-images.githubusercontent.com/3494491/105501927-21c7ff80-5cc5-11eb-8d65-4bc3509ed5ba.png)

Which functional interfaces does Java provide to serve as data types for lambda expressions?
[] Observer, Observable
[] Collector, Builder
[] Filter, Map, Reduce
[] Consumer, Predicate, Supplier

**Comment by Ebazhanov** [comment]
Hello, @k-tipp! Thank you for the issue and the new questions :+1: FYI they were implemented in this PR by @rradfar 
https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/pull/1168
so the questions is available now here
https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/master/java/java-quiz.md
:rose:
