### ISSUE TITLE
New Question- MongoDb

### ISSUE THREAD

**Issue by pavananand1996** [Ebazhanov/linkedin-skill-assessments-quizzes#1034]
![Screenshot (13)](https://user-images.githubusercontent.com/35186350/105762207-1d783c80-5f7a-11eb-8b81-9db6f74fd234.png)

**Comment by jrshort89** [comment]
Working on this.

**Comment by rradfar** [comment]
Looks like @jrshort89 already added this question to [our codebase](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/pull/1076) on Feb 4th, so this issue can be closed. Thanks 👍

**Comment by Ebazhanov** [comment]
Agree with @rradfar, thanks @pavananand1996 anyway, if you have anything you are always welcome! :pray:
