### ISSUE TITLE
45 QUESTIONS WITH PHOTOSHOP TEST ANSWERS

### ISSUE THREAD

**Issue by babeshark** [Ebazhanov/linkedin-skill-assessments-quizzes#1035]
I share my list with 45 photoshop questions and correct answers. I need answers for Lightroom, in case anyone can share. thankful

[TEST - PHOTOSHOP.docx](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/files/5870373/TEST.-.PHOTOSHOP.docx)

**Comment by rradfar** [comment]
@babeshark This is a great list, thanks for sharing! Do you by any chance have the accompanying assets (images) too? There are about 14 images.

**Comment by rradfar** [comment]
I went through this great list and added as many questions as I could to our codebase. Here is a summary:
- Duplicate questions **not** added: 1, 2, 3, 4, 5, 6, 7, 9, 10, 11, 12, 13, 14, 15, 18, 25, 27, 28, 29, 30, 32, 34, 35, 36, 37, 39, 40, 41, 42, 43
- New questions [added ](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/pull/1142): 8, 19, 20, 21, 22, 23, 24, 26, 31, 33, 45
- Questions **not** added due to missing images: 16, 17, 38, 44

**Comment by babeshark** [comment]
Sorry for the delay. Yes, I have the images, but I don't remember which image refers to which issue

![IMG_1540](https://user-images.githubusercontent.com/78000734/107857168-7f0a2900-6e0b-11eb-93d3-fcab403415c2.PNG)
![IMG_1541](https://user-images.githubusercontent.com/78000734/107857173-829db000-6e0b-11eb-9940-782f1b51836f.PNG)
![IMG_1542](https://user-images.githubusercontent.com/78000734/107857174-8a5d5480-6e0b-11eb-8c2d-3017b5c9dd27.PNG)
![IMG_1543](https://user-images.githubusercontent.com/78000734/107857177-8c271800-6e0b-11eb-9b75-1452001b3958.PNG)
![IMG_1544](https://user-images.githubusercontent.com/78000734/107857178-8df0db80-6e0b-11eb-9881-f8b36d4f1705.PNG)
![IMG_1545](https://user-images.githubusercontent.com/78000734/107857179-8f220880-6e0b-11eb-940b-e690fb969f27.PNG)
![IMG_1546](https://user-images.githubusercontent.com/78000734/107857180-90533580-6e0b-11eb-8230-65732a1f31df.PNG)
![IMG_1547](https://user-images.githubusercontent.com/78000734/107857182-91846280-6e0b-11eb-9ba9-857520a22dbc.PNG)
![IMG_1548](https://user-images.githubusercontent.com/78000734/107857185-921cf900-6e0b-11eb-880d-2cfad3999ee4.PNG)
![IMG_1549](https://user-images.githubusercontent.com/78000734/107857186-93e6bc80-6e0b-11eb-890f-a10634e456b8.PNG)
![IMG_1550](https://user-images.githubusercontent.com/78000734/107857187-95b08000-6e0b-11eb-80c3-ff490817579d.PNG)
![IMG_1551](https://user-images.githubusercontent.com/78000734/107857189-977a4380-6e0b-11eb-9d49-17c8d81fa8eb.PNG)
![IMG_1552](https://user-images.githubusercontent.com/78000734/107857191-99440700-6e0b-11eb-91e8-d1c7d52976fd.PNG)
![IMG_1553](https://user-images.githubusercontent.com/78000734/107857193-9b0dca80-6e0b-11eb-8f92-591c3bb6c615.PNG)
![IMG_1554](https://user-images.githubusercontent.com/78000734/107857196-9c3ef780-6e0b-11eb-9648-9bae2d0d92ee.PNG)
![IMG_1555](https://user-images.githubusercontent.com/78000734/107857197-9e08bb00-6e0b-11eb-8aaf-f0486fd7fdb8.PNG)

**Comment by rradfar** [comment]
@babeshark Very cool, thanks! 😀 I will go through them and see if any of them are the ones we're missing.

**Comment by Ebazhanov** [comment]
Thank you guys so, it is so good to see team spirit and collaboration! :metal:
@all-contributors please add @babeshark for code, design
