### ISSUE TITLE
20 QUESTIONS AND ANSWERS FOR THE ILLUSTRATOR 

### ISSUE THREAD

**Issue by babeshark** [Ebazhanov/linkedin-skill-assessments-quizzes#1036]
I share my list with 20 questions and correct answers from the IILUSTRATOR test. I need answers for Lightroom, in case anyone can share. thankful
[TEST - ILLUSTRATOR.docx](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/files/5870396/TEST.-.ILLUSTRATOR.docx)

**Comment by rradfar** [comment]
@babeshark Awesome list! Thanks for your contribution! Do you also happen to have the two image assets that your file refers to?

**Comment by rradfar** [comment]
Thanks a lot @babeshark! 😀 There were some duplicates we already had, but I added all the new questions (13 of them) to our codebase!

**Comment by Ebazhanov** [comment]
Thank you, @babeshark! Was successfully added by @rradfar
check it out here 
https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/master/adobe-illustrator/adobe-illustrator-quiz.md
