### ISSUE TITLE
add new question for PHP assesment

### ISSUE THREAD

**Issue by hl8-coder** [Ebazhanov/linkedin-skill-assessments-quizzes#1048]
#### Q34. Which code snippet demonstrates encapsulation?

- [ ] class Cow extends Animal {
    private $milk;
    }

- [ ] class Cow {
        public $milk;
        }
        
        $daisy = new Cow();
        $daisy->milk = "creamy";

- [ ] class Cow {
        public $milk;
        
            function getMilk() {
                return $this->milk;
            }
        }
            
- [x] class Cow {
        private $milk;
        
            public function getMilk() {
                return $this->milk;
            }
        }

**Comment by jrshort89** [comment]
My first contribution :)

**Comment by rradfar** [comment]
@jrshort89 Nice, thanks Jacob! Looks like your contribution has been [merged into the codebase](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/pull/1076), so I think this issue can now be closed 🙂
