### ISSUE TITLE
New XML and Azure question 

### ISSUE THREAD

**Issue by lostNfound2434** [Ebazhanov/linkedin-skill-assessments-quizzes#1049]
### **XML**

![image](https://user-images.githubusercontent.com/49598554/106043043-d8542780-60ab-11eb-8571-fddeae106805.png)`

**Q21 is missing the selection part:**
![image](https://user-images.githubusercontent.com/49598554/106042878-a17e1180-60ab-11eb-805b-01f2d6d35b85.png)

### Azure
![image](https://user-images.githubusercontent.com/49598554/106043201-0c2f4d00-60ac-11eb-91dd-14c27c617251.png)

**Comment by Ebazhanov** [comment]
@lostNfound2434 thanks for raising this issue, FYI `Azure` questions were implemented in this PR https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/pull/1213 by @rradfar :fire:
=========
but we want to keep it open because XML questions still not in the codebase

**Comment by Ebazhanov** [comment]
OK, thanks @rradfar based on https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/pull/1215
will close, great job guys!
