### ISSUE TITLE
there is a syntax error in #47 solution

### ISSUE THREAD

**Issue by speckworks** [Ebazhanov/linkedin-skill-assessments-quizzes#1081]
" <button onClick={this.handleClick.bind(handleClick}>Click this</button>"

should be:

 <button onClick={this.handleClick.bind(handleClick)}>Click this</button>

i believe. If not, please advise.

**Comment by speckworks** [comment]
` <button onClick={this.handleClick.bind(handleClick}>Click this</button>`

should be 

` <button onClick={this.handleClick.bind(handleClick)}>Click this</button>`

**Comment by rradfar** [comment]
@speckworks  Thanks John! Should be fixed in the next update.

**Comment by Ebazhanov** [comment]
fix is here https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/pull/1084
