### ISSUE TITLE
React - Duplicate questions, different answers

### ISSUE THREAD

**Issue by nathanhannig** [Ebazhanov/linkedin-skill-assessments-quizzes#1085]
Q20 and Q50

`What is the difference between the click behaviors of these two buttons(assuming that this.handleClick is bound correctly)`

They have different answers and are the same question

**Comment by rradfar** [comment]
@nathanhannig Thanks Nathan! Do you think the correct answer is that there are no differences between the two click handlers?

**Comment by nathanhannig** [comment]
@rradfar  Yes, I feel Q50 is the correct answer.

**Comment by rradfar** [comment]
@nathanhannig Sweet, thanks! Will fix in the next update!

**Comment by nathanhannig** [comment]
@rradfar 
I also just noticed the Q50 has typo
`A. <button onClick=fthis.handleClickl>Click Me</button>`

It has an `f` and an `l` surronding this.handleClick

Fix is below:
`A. <button onClick={this.handleClick}>Click Me</button>`

**Comment by rradfar** [comment]
@nathanhannig Thanks. I removed Q50 so that took care of that problem too 😉

**Comment by Ebazhanov** [comment]
Thank you guys!
