### ISSUE TITLE
Add visual representation (image) to the Microsoft Excel Q28

### ISSUE THREAD

**Issue by monkrus** [Ebazhanov/linkedin-skill-assessments-quizzes#1104]
Please add an **image** or **link to the image** for this question. It is hard to answer without seeing it.
```
In the worksheet below, you want to copy the formatting of cell A1 into cells B1:D1. Which approach (see arrows) accomplishes this the most efficiently?
 B
 C
 **A**
 D
```

**Comment by Ebazhanov** [comment]
@monkrus FYI the image now in master
https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/master/microsoft-excel/microsoft-excel-quiz.md
