### ISSUE TITLE
Answer  Microsoft Excel Q35 question :  Which format setting does not change the background appearance of a cell?

### ISSUE THREAD

**Issue by monkrus** [Ebazhanov/linkedin-skill-assessments-quizzes#1105]
Answer `Which format setting does not change the background appearance of a cell?` question

Q35. Which format setting does not change the background appearance of a cell?
 Cell style
 Fill color
 Pattern style
 Font color

**Comment by Ebazhanov** [comment]
FYI @monkrus you can also use `Discussions` for your question
https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/discussions
![image](https://user-images.githubusercontent.com/13170022/107162353-c2474080-69a2-11eb-9698-72d61b76afaa.png)

**Comment by Ebazhanov** [comment]
@monkrus please find the answer in this PR https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/pull/1139
![image](https://user-images.githubusercontent.com/13170022/107854972-e4681500-6e1f-11eb-9bc5-b677cce2a933.png)
