### ISSUE TITLE
Microsoft Outlook - 14 slides

### ISSUE THREAD

**Issue by Ebazhanov** [Ebazhanov/linkedin-skill-assessments-quizzes#1174]
![outlook 14](https://user-images.githubusercontent.com/13170022/108572242-2c9ca100-7312-11eb-8764-85bb632b8e42.png)
![outlook 5](https://user-images.githubusercontent.com/13170022/108572244-2dcdce00-7312-11eb-8ef8-fce04af42615.png)
![outlook 3](https://user-images.githubusercontent.com/13170022/108572245-2e666480-7312-11eb-842d-0f963e9c80cc.png)
![outlook 1](https://user-images.githubusercontent.com/13170022/108572246-2efefb00-7312-11eb-9cba-3d79e24cd114.png)
![outlook 12](https://user-images.githubusercontent.com/13170022/108572249-2efefb00-7312-11eb-81a3-120dd17f0040.png)
![outlook 8](https://user-images.githubusercontent.com/13170022/108572250-2f979180-7312-11eb-85df-da1e07e1c538.png)
![outlook 6](https://user-images.githubusercontent.com/13170022/108572251-30302800-7312-11eb-91a3-f372aa271814.png)
![outlook 4](https://user-images.githubusercontent.com/13170022/108572254-30302800-7312-11eb-8432-b2b61a624bb1.png)
![outlook 2](https://user-images.githubusercontent.com/13170022/108572255-30c8be80-7312-11eb-8a5a-4d52026d2317.png)
![outlook 10](https://user-images.githubusercontent.com/13170022/108572256-30c8be80-7312-11eb-9ffe-89d37089f095.png)
![outlook 13](https://user-images.githubusercontent.com/13170022/108572257-30c8be80-7312-11eb-82be-eb7515c46eaf.png)
![outlook 9](https://user-images.githubusercontent.com/13170022/108572259-31615500-7312-11eb-97da-16924a772b53.png)
![outlook 7](https://user-images.githubusercontent.com/13170022/108572260-31615500-7312-11eb-925a-6b43a4874e0b.png)
![outlook 11](https://user-images.githubusercontent.com/13170022/108572262-31f9eb80-7312-11eb-940c-135929fe19e8.png)

**Comment by lnugraha** [comment]
Hi there, 

I have included all of these questions in my latest pull request (PR #1198). In addition, I have also bumped the number of problem from 12 to 42.

**Comment by Ebazhanov** [comment]
Nice, good job! Thank you, @lnugraha! I really appreciate it! :pray:
