### ISSUE TITLE
MongoDB - 2 slides

### ISSUE THREAD

**Issue by rradfar** [Ebazhanov/linkedin-skill-assessments-quizzes#1205]
![mongo1](https://user-images.githubusercontent.com/31255934/109210180-582fe900-7761-11eb-9588-8132a2b12872.png)
![mongo2](https://user-images.githubusercontent.com/31255934/109210182-582fe900-7761-11eb-9715-489c425f96d8.png)

**Comment by jjeshwani** [comment]
can take this issue

**Comment by Ebazhanov** [comment]
Well done @jjeshwani! Thanks that you take care about this issue! :muscle:
