### ISSUE TITLE
Python - 1 slide

### ISSUE THREAD

**Issue by rradfar** [Ebazhanov/linkedin-skill-assessments-quizzes#1217]
<img width="1147" alt="109248254-77576680-77b3-11eb-96ef-1f5a36110121" src="https://user-images.githubusercontent.com/31255934/109400855-f063d480-78ff-11eb-9c87-e9dcb2ce68d5.png">

**Comment by suryanmon** [comment]
Second one.

**Comment by tik9** [comment]
Would be nice to add it [here](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/master/python/python-quiz.md). Then we close it.

**Comment by Ebazhanov** [comment]
Thanks, @rradfar, as you already know it was added in this PR https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/pull/1248   :point_left:
