### ISSUE TITLE
MS Excel update

### ISSUE THREAD

**Issue by fmalk** [Ebazhanov/linkedin-skill-assessments-quizzes#1234]
![image](https://user-images.githubusercontent.com/208820/110005073-da3a8780-7cf6-11eb-83a1-6992789d497a.png)

![image](https://user-images.githubusercontent.com/208820/110005157-f0e0de80-7cf6-11eb-8eeb-297b9c0e2b8e.png)

**Comment by simoconfa** [comment]
I would add also:
 
 
![immagine](https://user-images.githubusercontent.com/8224154/111881326-35839f80-89b0-11eb-8c85-ec014530fb68.png)

**Comment by praveenpno** [comment]
The formula contains SUM(C2:C8) instead of SUM(C3:C8)

Answer--> The AutoSum formulas include the year at the top of each column in the calculation.

**Comment by Ebazhanov** [comment]
Thank you Guys @fmalk @simoconfa @praveenpno have double check and those questions are in codebase now 👍 
FYI https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/master/microsoft-excel/microsoft-excel-quiz.md
Great job :muscle:
