### ISSUE TITLE
Java update

### ISSUE THREAD

**Issue by Yurii17K** [Ebazhanov/linkedin-skill-assessments-quizzes#1270]
![{7E7C97B2-157D-4848-9D85-A8D424481672}](https://user-images.githubusercontent.com/56108535/110773065-014c0880-8265-11eb-918d-d04a46b6f7a7.png)
![{5A6025C2-5891-4C79-88F4-40E1C167BE71}](https://user-images.githubusercontent.com/56108535/110773067-01e49f00-8265-11eb-9767-810ee285cd62.png)

**Comment by Yurii17K** [comment]
First screenshot: this.getClass().getSimpleName();   this.getClass().getSimpleName().getDeclaredMethods()
![image](https://user-images.githubusercontent.com/56108535/111863140-6341f780-8962-11eb-99c9-e8456adc3544.png)

Second: deciding if two instances of a class are equal.
Java can not differentiate two instances of the same class if equals() and hashcode() are not implemented. Otherwise, you will receive the same hashcode for different instances.

**Comment by Ebazhanov** [comment]
@Yurii17K thanks a lot for your screenshot and answers 👍 (will add it today), let me know if you would like to be added as contributor in Readme.
