### ISSUE TITLE
MS Word update - 2 slides

### ISSUE THREAD

**Issue by simoconfa** [Ebazhanov/linkedin-skill-assessments-quizzes#1304]
Here are some new questions that are not [here](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/master/microsoft-word/microsoft-word-quiz.md) :
![immagine](https://user-images.githubusercontent.com/8224154/111868266-3b11c300-8979-11eb-8476-0f2b8c073cc7.png)
![immagine](https://user-images.githubusercontent.com/8224154/111868285-567cce00-8979-11eb-8e08-2891e786d23e.png)

**Comment by monkrus** [comment]
"When you crop.." question already exists as  Q26

**Comment by Ebazhanov** [comment]
Thank @simoconfa for your screenshots! 👍  I will add your questions today!
