### ISSUE TITLE
Linux - 3 slides

### ISSUE THREAD

**Issue by Ebazhanov** [Ebazhanov/linkedin-skill-assessments-quizzes#1306]
![linux_2](https://user-images.githubusercontent.com/13170022/111904174-c3f63080-8a45-11eb-8e20-dde08b35a673.png)
![linux_3](https://user-images.githubusercontent.com/13170022/111904175-c5275d80-8a45-11eb-82c0-bed92c4716c7.png)
![linux_1](https://user-images.githubusercontent.com/13170022/111904176-c5275d80-8a45-11eb-8834-a8d1d50f4af1.png)

**Comment by M-Razavi** [comment]
1) ?
2) change global user account setting
3) it is a command line tool that manager network connections.

**Comment by Ebazhanov** [comment]
@M-Razavi thanks for your suggestion, I found that it is already in codebase
