### ISSUE TITLE
MS Word, New Questions.

### ISSUE THREAD

**Issue by Cyborg002** [Ebazhanov/linkedin-skill-assessments-quizzes#1324]
**Q**.    You're finalizing a document that contains some high-resolution images. You want to reduce the picture size while ensuring image quality is adequate for online viewing. What is a best-practice approach?

A.    Review the images and crop as needed. Compress the images. Save the document and then compress the entire document.
B.    Replace the images with lower-resolution images. Save the document and then compress it.
C.    Review the images and crop as needed. Then compress the images and delete cropped areas.
D.    Review the images and crop as needed. Save document and then compress it.

**My Answer**:   option (C)     [Reference](https://support.microsoft.com/en-us/topic/reduce-the-file-size-of-a-picture-in-microsoft-office-8db7211c-d958-457c-babd-194109eb9535)

---------------------------------------------------------------------------------------
**Q**.    When working with Track Changes, what is the difference between Simple Markup and All Markup?  

A.   Simple Markup shows the revisions of one selected author in the Review pane; All Markup shows the revisions of all authors with inline markups.
B.    Simple Markup shows the markup version by one selected author; All Markup shows the combined markup version of all authors.
C.    Simple Markup shows the final version with inline markups; All Markups shows the final version without inline markups.
D.    Simple Markup shows the final version without inline markups; All  Markup shows the final version with inline markups.

---------------------------------------------------------------------------------------
**Q**.    Before you send a document to an external client, you must remove personal information--including document author names, comments, and hidden text--from the doc. What tool can help you locate and clean up these details?

A.   Accessibility Checker 
B.   Check Compatibility
C.   Manage Document
D.   Document Inspector

**My Answer**:   option (D)     [Reference](https://support.microsoft.com/en-us/topic/remove-hidden-data-and-personal-information-by-inspecting-documents-presentations-or-workbooks-356b7b5d-77af-44fe-a07f-9aa4d085966f#:~:text=Click%20File%20%3E%20Info%20%3E%20Remove%20Personal,from%20the%20document%20check%20box.)

**Comment by Ebazhanov** [comment]
Thanks a lot @Cyborg002! Your questions with reference links will be added today! Good job with typing! 👍
