### ISSUE TITLE
Java: Q12 Explanation not correct

### ISSUE THREAD

**Issue by Romanicus** [Ebazhanov/linkedin-skill-assessments-quizzes#1329]
Hi, the explanation of the Question 12 is incorrect. It's true that `Non-static method message() cannot be referenced from a static context`, but than the error would be in line 8, where the method is tried to execute.
The correct explanation is, that the `'message()' cannot override 'message()' in 'MainClass'; overridden method is final`

**Comment by Ebazhanov** [comment]
@Romanicus thanks for your input, I am pretty sure that you are right, but there is no such variant of the answer. So I hope to keep in touch with you 👍
