### ISSUE TITLE
NoSql - new questions

### ISSUE THREAD

**Issue by M-Razavi** [Ebazhanov/linkedin-skill-assessments-quizzes#1342]
![nosql4](https://user-images.githubusercontent.com/6397404/112730664-47cf8180-8f4c-11eb-9120-802a9e57ceaa.png)
![nosql2](https://user-images.githubusercontent.com/6397404/112730666-4900ae80-8f4c-11eb-9d94-c99d2cb61d49.png)
![nosql](https://user-images.githubusercontent.com/6397404/112730667-4900ae80-8f4c-11eb-9315-7ceba26472ba.png)

**Comment by Badekale** [comment]
They are some repeated question with different and in NoSQL question eg.Q7-Q20, Q8-Q22,Q4-Q19,Q11-Q24, Q10-Q29,Q1-Q37

**Comment by teohangxanh** [comment]
Can anyone have a look at Q.7 and Q.20 from [here](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/master/nosql/nosql-quiz.md)?

**Comment by M-Razavi** [comment]
> Can anyone have a look at Q.7 and Q.20 from [here](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/master/nosql/nosql-quiz.md)?

what do you mean?

**Comment by Ebazhanov** [comment]
FYI @M-Razavi your questions with answer were successfully added to our codebase, thank you 👍 !
