### ISSUE TITLE
TSQL - New Questions

### ISSUE THREAD

**Issue by M-Razavi** [Ebazhanov/linkedin-skill-assessments-quizzes#1343]
![tsql5](https://user-images.githubusercontent.com/6397404/112730690-646bb980-8f4c-11eb-9a89-171c3af566a8.png)
![sql4](https://user-images.githubusercontent.com/6397404/112730691-659ce680-8f4c-11eb-816b-83fdc0c54542.png)
![tsql3](https://user-images.githubusercontent.com/6397404/112730692-659ce680-8f4c-11eb-9865-8b0d939118c4.png)
![tsql2](https://user-images.githubusercontent.com/6397404/112730695-66357d00-8f4c-11eb-89d8-d79b2d3c049e.png)
![tsql1](https://user-images.githubusercontent.com/6397404/112730696-66ce1380-8f4c-11eb-81c3-5ec2e6dcad6a.png)

**Comment by Ebazhanov** [comment]
@M-Razavi thanks for screenshots, all questions were added
https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/master/t-sql/t-sql-quiz.md
