### ISSUE TITLE
JavaScript - New Questions

### ISSUE THREAD

**Issue by M-Razavi** [Ebazhanov/linkedin-skill-assessments-quizzes#1344]
![javascript3](https://user-images.githubusercontent.com/6397404/112730715-86653c00-8f4c-11eb-8fa2-95652a3b397b.png)
![javascript2](https://user-images.githubusercontent.com/6397404/112730716-86fdd280-8f4c-11eb-8ba7-a82d84781af8.png)
![javascript1](https://user-images.githubusercontent.com/6397404/112730717-87966900-8f4c-11eb-88ae-24b2c5fd9374.png)

**Comment by lnugraha** [comment]
All questions in Issue #1344 have been included in javascript-quiz.md; this issue can now be closed

**Comment by Ebazhanov** [comment]
Thank you @M-Razavi for raising this issue! 👍

**Comment by Ebazhanov** [comment]
@all-contributors please add @M-Razavi for design, code
