### ISSUE TITLE
HTML - New Question

### ISSUE THREAD

**Issue by M-Razavi** [Ebazhanov/linkedin-skill-assessments-quizzes#1345]
![html1](https://user-images.githubusercontent.com/6397404/112730734-a09f1a00-8f4c-11eb-9f7f-ee6335603702.png)

**Comment by Ebazhanov** [comment]
@M-Razavi  FYI https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/master/html/html-quiz.md

**Comment by Ebazhanov** [comment]
Thanks for typing @lnugraha
