### ISSUE TITLE
Linux - New Question

### ISSUE THREAD

**Issue by M-Razavi** [Ebazhanov/linkedin-skill-assessments-quizzes#1346]
![linux1](https://user-images.githubusercontent.com/6397404/112730758-bca2bb80-8f4c-11eb-9683-f5e51d168e7e.png)

**Comment by Ebazhanov** [comment]
@M-Razavi your questions has been added https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/master/linux/linux-assesment.md#L299-L299

Thank you 👍
