### ISSUE TITLE
EXCEL — New Questions

### ISSUE THREAD

**Issue by andreeferreira** [Ebazhanov/linkedin-skill-assessments-quizzes#1353]
<img width="977" alt="Screenshot 2021-03-29 at 12 30 04" src="https://user-images.githubusercontent.com/49101040/112831478-e4e50400-908b-11eb-958e-eba81469ac9d.png">
<img width="976" alt="Screenshot 2021-03-29 at 12 32 56" src="https://user-images.githubusercontent.com/49101040/112831483-e6aec780-908b-11eb-86a9-900441938f9b.png">
<img width="1016" alt="Screenshot 2021-03-29 at 12 34 13" src="https://user-images.githubusercontent.com/49101040/112831484-e7475e00-908b-11eb-830e-10e9c287a5d6.png">

**Comment by Ebazhanov** [comment]
Thank you @andreeferreira :sunny:
