### ISSUE TITLE
React New Question

### ISSUE THREAD

**Issue by kpehl** [Ebazhanov/linkedin-skill-assessments-quizzes#1362]
Given the following code, what does this React element look like?

`React.createElement(
  "h1"
  null
  "What's happening?"
);`

- `<h1 props={null}>What's happening?</h1>`
- `<h1 id="null">What's happening?</h1>`
- `<h1 id="component">What's happening?</h1>`
- `<h1>What's happening?</h1>`

Correct answer: `<h1>What's happening?</h1>`

**Comment by Ebazhanov** [comment]
Sorry for delay @kpehl will add your answer today!
