### ISSUE TITLE
Kotlin questions

### ISSUE THREAD

**Issue by rdquispe** [Ebazhanov/linkedin-skill-assessments-quizzes#1368]
![Screen Shot 2021-04-01 at 8 52 50 AM](https://user-images.githubusercontent.com/4944113/113305768-fbc46a00-92c8-11eb-8cb5-4540051a026c.png)
![Screen Shot 2021-04-01 at 8 52 08 AM](https://user-images.githubusercontent.com/4944113/113305772-fcf59700-92c8-11eb-88f7-c7b7631a33dd.png)
![Screen Shot 2021-04-01 at 8 57 23 AM](https://user-images.githubusercontent.com/4944113/113305775-fe26c400-92c8-11eb-9011-e1be49d4660b.png)
![Screen Shot 2021-04-01 at 8 58 30 AM](https://user-images.githubusercontent.com/4944113/113305779-febf5a80-92c8-11eb-96ad-2d08c8808e8f.png)
![Screen Shot 2021-04-01 at 8 51 34 AM](https://user-images.githubusercontent.com/4944113/113305781-ff57f100-92c8-11eb-92ac-9256c4df76d5.png)
![Screen Shot 2021-04-01 at 8 56 54 AM](https://user-images.githubusercontent.com/4944113/113305785-ff57f100-92c8-11eb-9e17-f71199033b99.png)
![Screen Shot 2021-04-01 at 8 50 30 AM](https://user-images.githubusercontent.com/4944113/113305788-ff57f100-92c8-11eb-8458-575531583376.png)
![Screen Shot 2021-04-01 at 8 56 12 AM](https://user-images.githubusercontent.com/4944113/113305790-fff08780-92c8-11eb-9ecf-72cfd4c6df17.png)
![Screen Shot 2021-04-01 at 8 49 32 AM](https://user-images.githubusercontent.com/4944113/113305792-fff08780-92c8-11eb-8b8d-d0748332fa6b.png)
![Screen Shot 2021-04-01 at 8 55 39 AM](https://user-images.githubusercontent.com/4944113/113305794-00891e00-92c9-11eb-81a4-972246c152d6.png)
![Screen Shot 2021-04-01 at 8 48 02 AM](https://user-images.githubusercontent.com/4944113/113305795-00891e00-92c9-11eb-8d8f-a19087b94a52.png)
![Screen Shot 2021-04-01 at 8 55 03 AM](https://user-images.githubusercontent.com/4944113/113305796-0121b480-92c9-11eb-8467-1f4ab16efdbe.png)
![Screen Shot 2021-04-01 at 9 00 32 AM](https://user-images.githubusercontent.com/4944113/113305798-0121b480-92c9-11eb-85bb-4fb617b60a65.png)
![Screen Shot 2021-04-01 at 8 54 15 AM](https://user-images.githubusercontent.com/4944113/113305799-01ba4b00-92c9-11eb-92ea-31d2668cd0b7.png)
![Screen Shot 2021-04-01 at 8 59 25 AM](https://user-images.githubusercontent.com/4944113/113305802-0252e180-92c9-11eb-85f3-3e3ba9bfb928.png)

**Comment by Ebazhanov** [comment]
@lnugraha Thank you Leo, great job 👍

**Comment by Ebazhanov** [comment]
and thank you @rdquispe for rising this issue :hibiscus:
