### ISSUE TITLE
Q9 answer in /c++/c++quiz.md is incorrect

### ISSUE THREAD

**Issue by benliepert** [Ebazhanov/linkedin-skill-assessments-quizzes#1374]
v1 and v2 are pointers. v1 = v2, therefore *v1 and *v2 are the same vector. 
The answer should be *v1:{1,2,3,4,5}; *v2:{1,2,3,4,5};

**Comment by Ebazhanov** [comment]
@benliepert thank you for your answers and explanation 👍  I see that it is already was added, so will close it now!
