### ISSUE TITLE
React JS - 2 slides

### ISSUE THREAD

**Issue by Ebazhanov** [Ebazhanov/linkedin-skill-assessments-quizzes#1409]
<img width="1013" alt="Screen_Shot_2021-04-03_at_2 14 32_PM" src="https://user-images.githubusercontent.com/13170022/113909434-f8087a00-97d7-11eb-85b0-28ce9f5b3c25.png">
<img width="1329" alt="Screen_Shot_2021-04-03_at_2 13 19_PM" src="https://user-images.githubusercontent.com/13170022/113909448-fb036a80-97d7-11eb-8906-e61490980570.png">

**Comment by Prathamkrishna** [comment]
the first answer is option b

**Comment by Muskan298Rawal** [comment]
The first Answer is A. And for the second question it is D.

**Comment by Ebazhanov** [comment]
Thank you for your input guys 👍  @Prathamkrishna @Muskan298Rawal 
I am going to add those questions today!
