### ISSUE TITLE
For the C# quiz I would like to add 4 more questins that I have found yesteday. Also I would suggest a small correction on a existing one

### ISSUE THREAD

**Issue by LiviuSosu** [Ebazhanov/linkedin-skill-assessments-quizzes#1426]
Hello!

Yesterday (08.04.2021) I have took and passed the C# quiz, thanks to this repository. 

I would like to give back, as a thank you, four questions that I have not found it on your list.

I have took pictures in order to elimenate doubth that I am lying.

I will also post the answers that I ##believe## that are correct.

1. How are C# classses limited?
[x] They do not support multiple inheritance.
[ ] They support multiple inheritance.
[ ] They can have only a set number of properties.
[ ] They ca have only a set number of methods.

2. What function do namespaces perform?
[ ] Namespaces calculate code coverage at runtime.
[ ] Namespaces compile application code together at compile time.
[ ] Namespaces group code together into a single repository.
[x] Namespaces separate code into groupings, control access, and void naming collisions.

3. What is the correct way to write a public propery with a private backing field?
[ ]
```
private int _password;
pubic int Password = { get; set; }
```
[ ]
```
private int _password;
public int Password = _password;
```
[ ]
```
private int _password;
public int Password
{
  get -> _password;
  set-> _password = value;
}
```
[x]
```
private int _password;
public int Password
{
  get { return _password; }
  set { _password = value; }
}
```
4. What is a threadpool?
[ ] a collection of synchronous methods created during initialization that cannot be reused
[x] a collection of threads created during initialization that can be reused
[ ] a collection of threads only recognized at compile time that can be reused
[ ] a collection of asynchronous methods created at compile time that cannot be reused

Again, I have marked the correct answeres because I cosider so. Even if I passed the quiz, that does not mean that I am totally right, therefore it would be great if a second pair of eyes could take a look.

Ans regarding the second part of teh issue -  the typo, please see the last attached image. I explained there. It is not a big deal, I woill let it up to you if you would like to addapt it.

![New Question 1](https://user-images.githubusercontent.com/11800340/114161805-22ba1600-9931-11eb-9493-805791eb181b.PNG)
![New Question 2](https://user-images.githubusercontent.com/11800340/114175221-6c5f2c80-9942-11eb-80d8-093e45a3beb2.PNG)
![New Question 3](https://user-images.githubusercontent.com/11800340/114175224-6f5a1d00-9942-11eb-9fe0-50dfa708830b.PNG)
![New Question 4](https://user-images.githubusercontent.com/11800340/114175229-71bc7700-9942-11eb-98b8-49ffc76e41b8.PNG)
![Corrected question](https://user-images.githubusercontent.com/11800340/114175240-74b76780-9942-11eb-812e-80963eca33db.PNG)

**Comment by Ebazhanov** [comment]
@LiviuSosu thank you for screenshots 👍  and no worries about answers I successfully added them all ))))
https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/ff7096e587f8377902099c697bd518ec1f58fa4c/c#//c-sharp-quiz.md%23L459-L459
