### ISSUE TITLE
MySQL New question

### ISSUE THREAD

**Issue by teohangxanh** [Ebazhanov/linkedin-skill-assessments-quizzes#1450]
1. What is the maximum number of columns that can be used by a single table index?
2
4
8
16

2. Which command will return a list of triggers in the current database?
DISPLAY TRIGGERS;
SHOW TRIGGERS;
SELECT ALL TRIGGERS;
SELECT * FROM  information_schema.triggers;

3. Which statement is true about TIMESTAMP and DATETIME data types?
TIMESTAMP values require more bytes for storage than DATETIME values.
TIMESTAMP is stored without timezone, and DATETIME is stored in UTC values.
TIMESTAMP and DATETIME are both stored without time zone.
TIMESTAMP is stored in UTC values, and DATETIME is stored in without time zone.

4. What is the equivalent of mysqladmin reload command?
mysqladmind flush-threads
mysqladmind flush-tables
mysqladmind flush-privileges
mysqladmind flush-all

**Comment by Ebazhanov** [comment]
Thank you, @teohangxanh once again for raising this issue 👍 . All your new questions will add today!
