### ISSUE TITLE
New Java Questions

### ISSUE THREAD

**Issue by jibasham** [Ebazhanov/linkedin-skill-assessments-quizzes#1466]
![image](https://user-images.githubusercontent.com/33226928/115122918-9048f080-9f88-11eb-8e2c-bc9d56123317.png)

![image](https://user-images.githubusercontent.com/33226928/115122923-95a63b00-9f88-11eb-93bd-0c1a18e0610b.png)

![image](https://user-images.githubusercontent.com/33226928/115122969-d2723200-9f88-11eb-9555-7d3e8a3e5053.png)

**Comment by Ebazhanov** [comment]
Thank you guys @jibasham @lnugraha all questions are in our codebase now!
