### ISSUE TITLE
Hadoop - New questions

### ISSUE THREAD

**Issue by teohangxanh** [Ebazhanov/linkedin-skill-assessments-quizzes#1478]
![Screenshot (40)](https://user-images.githubusercontent.com/47458301/115500963-914f7b80-a22f-11eb-802c-55e546c52d6d.png)
![Screenshot (41)](https://user-images.githubusercontent.com/47458301/115500966-91e81200-a22f-11eb-9f7b-b6886dddd983.png)
![Screenshot (42)](https://user-images.githubusercontent.com/47458301/115500967-9280a880-a22f-11eb-8877-6cbc8c39ee60.png)
![Screenshot (43)](https://user-images.githubusercontent.com/47458301/115500969-9280a880-a22f-11eb-8906-b42f312aeef7.png)
![Screenshot (44)](https://user-images.githubusercontent.com/47458301/115500970-9280a880-a22f-11eb-8882-1e7c219cab50.png)
![Screenshot (45)](https://user-images.githubusercontent.com/47458301/115500971-93193f00-a22f-11eb-92b1-f4afa84a3b0c.png)

**Comment by Ebazhanov** [comment]
Thanks a lot @teohangxanh I added your questions 👍 
https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/master/hadoop/hadoop-quiz.md
