### ISSUE TITLE
Scala new questions

### ISSUE THREAD

**Issue by teohangxanh** [Ebazhanov/linkedin-skill-assessments-quizzes#1479]
![Screenshot (54)](https://user-images.githubusercontent.com/47458301/115502442-2bb0be80-a232-11eb-89bf-816576c6a7dd.png)
![Screenshot (55)](https://user-images.githubusercontent.com/47458301/115502445-2c495500-a232-11eb-89d4-89b4e57bb521.png)
![Screenshot (56)](https://user-images.githubusercontent.com/47458301/115502447-2ce1eb80-a232-11eb-8168-c6bcac5ea886.png)
![Screenshot (57)](https://user-images.githubusercontent.com/47458301/115502448-2ce1eb80-a232-11eb-96d8-3215ea003630.png)
![Screenshot (58)](https://user-images.githubusercontent.com/47458301/115502450-2ce1eb80-a232-11eb-923e-46eefeaa2177.png)
![Screenshot (46)](https://user-images.githubusercontent.com/47458301/115502452-2d7a8200-a232-11eb-848c-01722500da0b.png)
![Screenshot (47)](https://user-images.githubusercontent.com/47458301/115502454-2d7a8200-a232-11eb-9edb-1d8dd10a4089.png)
![Screenshot (48)](https://user-images.githubusercontent.com/47458301/115502455-2d7a8200-a232-11eb-9c31-eb5a5467a9bd.png)
![Screenshot (49)](https://user-images.githubusercontent.com/47458301/115502456-2e131880-a232-11eb-8777-c86b89879fda.png)
![Screenshot (50)](https://user-images.githubusercontent.com/47458301/115502458-2e131880-a232-11eb-831a-0db8418975c2.png)
![Screenshot (51)](https://user-images.githubusercontent.com/47458301/115502459-2e131880-a232-11eb-9abe-f58260fff763.png)
![Screenshot (52)](https://user-images.githubusercontent.com/47458301/115502460-2eabaf00-a232-11eb-9285-fa70e2c746fb.png)
![Screenshot (53)](https://user-images.githubusercontent.com/47458301/115502461-2eabaf00-a232-11eb-8ca6-67eeeb69a0a5.png)

**Comment by Ebazhanov** [comment]
Hello, @teohangxanh! Thanks a lot for your screenshot 👍  FYI all the questions is in our codebase now!
https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/master/scala/scala-quiz.md
