### ISSUE TITLE
MongoDB - new and updated questions

### ISSUE THREAD

**Issue by snakehead007** [Ebazhanov/linkedin-skill-assessments-quizzes#1501]
## new question
(Answer is `mongo`)
![image](https://user-images.githubusercontent.com/10829524/116371605-e4b36200-a80b-11eb-8b2d-dca38c0e29f3.png)
![image](https://user-images.githubusercontent.com/10829524/116371709-014f9a00-a80c-11eb-9f7f-0a16a3e034c9.png)
#### Q. How can you view the execution performance statistics for a query?
- [ ] `db.performance.members.aggregate([ {$match: {gender: "Female"}}, {$group: {_id:{city:"$city"}, number: {$sum: 1}}}, {$sort : {number: -1}}])`

- [ ] `db.members.aggregate([ {$match: {gender: "Female"}}, {$group: {_id: {city: "$city"}, number:{$sum:1}}}, {$sort: {number:-1}}]).eplain("executionStats")`

- [ ] `db.members.aggregate([ {$match: {gender: "Female"}}, {$group:{_id: {city: "$city"}, number: {$sum: 1}}}, {$sort: {number: -1}}]).explain()`

- [ ] `db.members.aggregate([ {$match: {gender: """Female"""}}, {$group: {_id: {city: """$city"""}, number: {$sum:1}}}, {$sort: {number: -1}}]).number()`
## updated (sentencing was different)
![image](https://user-images.githubusercontent.com/10829524/116371631-e9781600-a80b-11eb-85b0-6e1451249453.png)
![image](https://user-images.githubusercontent.com/10829524/116372015-4d024380-a80c-11eb-9bf3-509350185069.png)
![image](https://user-images.githubusercontent.com/10829524/116372024-4ecc0700-a80c-11eb-9237-7b03b41b7c83.png)

**Comment by Ebazhanov** [comment]
Thanks @snakehead007 great job 👍
