### ISSUE TITLE
HTML - 7 new questions

### ISSUE THREAD

**Issue by snakehead007** [Ebazhanov/linkedin-skill-assessments-quizzes#1502]
![image](https://user-images.githubusercontent.com/10829524/116375294-707abd80-a80f-11eb-9c10-ddf98849b939.png)
![image](https://user-images.githubusercontent.com/10829524/116375301-72448100-a80f-11eb-9733-67b15b1ae8e0.png)
![image](https://user-images.githubusercontent.com/10829524/116375314-740e4480-a80f-11eb-9411-784002aa8bb8.png)

![image](https://user-images.githubusercontent.com/10829524/116375406-8a1c0500-a80f-11eb-9122-6081c7feed94.png)

![image](https://user-images.githubusercontent.com/10829524/116375419-8d16f580-a80f-11eb-9aad-a5f201a2f4e6.png)
![image](https://user-images.githubusercontent.com/10829524/116375432-90aa7c80-a80f-11eb-9c84-e4736e05021e.png)

![image](https://user-images.githubusercontent.com/10829524/116375454-956f3080-a80f-11eb-9156-b245711220e1.png)

**Comment by Ebazhanov** [comment]
:pray:
