### ISSUE TITLE
Python

### ISSUE THREAD

**Issue by leo-smi** [Ebazhanov/linkedin-skill-assessments-quizzes#1506]
![image](https://user-images.githubusercontent.com/20663547/116596130-70a3b780-a8fa-11eb-959a-b71959e786a4.png)
![image](https://user-images.githubusercontent.com/20663547/116596202-80230080-a8fa-11eb-8e94-1fb196d9c0c3.png)
![image](https://user-images.githubusercontent.com/20663547/116596229-874a0e80-a8fa-11eb-8467-3545b00b87d2.png)

**Comment by Ebazhanov** [comment]
@leo-smi thanks great job for creating this issue 👍 
all the questions in live now 
https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/master/python/python-quiz.md

**Comment by leo-smi** [comment]
Thnak you!
