### ISSUE TITLE
C# Regex

### ISSUE THREAD

**Issue by Kebechet** [Ebazhanov/linkedin-skill-assessments-quizzes#1519]
In C# [Q32](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/master/c%23/c-sharp-quiz.md)
Is probably a mistake. Word boundary is specified with `\b`, 
Src: https://www.regular-expressions.info/wordboundaries.html

**Comment by Ebazhanov** [comment]
Thanks for your request but not sure that I understand what should be done, can you please write more details @Kebechet? Thank you in advance!

**Comment by Kebechet** [comment]
Sorry I specified wrong question. Not Q8 but Q32(edited):
_Q32. What character would you use to start a regular expression pattern at a word boundary?_
I think that the answer should be \b not \w. But somebody with better regex udnerstanding should confirm this claim.

**Comment by Ebazhanov** [comment]
@Kebechet FYI we still have an option to ask on stackoverflow in case if you will wait for too long :point_up:

**Comment by DevChive** [comment]
@Ebazhanov, could you link to the StackOverflow question?  I'm interested to see the results of this as well - frankly, I don't often work with RegEx.

**Comment by Ebazhanov** [comment]
well I did not do it and have no plan to do it, sorry @DevChive

**Comment by Ebazhanov** [comment]
FYI @Kebechet i added your suggestion with reference link, so this issue is solved :metal:
btw great job, thanks for raising this issue :pray:

**Comment by Ebazhanov** [comment]
![image](https://user-images.githubusercontent.com/13170022/124565422-4e6e6e80-de42-11eb-902f-2985c3e226f6.png)
