### ISSUE TITLE
Front End Development 

### ISSUE THREAD

**Issue by pohern** [Ebazhanov/linkedin-skill-assessments-quizzes#1535]
It appears this is a new quiz on LinkedIn, with no answers in this repo

**Comment by Ebazhanov** [comment]
true 💯 , thanks for reminder @pohern 👍

**Comment by a2softech** [comment]
yes, please update, Front-end Development Assessment, repository

**Comment by Ebazhanov** [comment]
good plan guys, but first we should create this quiz, it is not exist sofar. I am feeling positive drive from you @a2softech, have a good day!

**Comment by Ebazhanov** [comment]
FYI guys :point_right: https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/master/front-end-development/front-end-development-quiz.md
