### ISSUE TITLE
Missing Questions

### ISSUE THREAD

**Issue by kaushalarwal** [Ebazhanov/linkedin-skill-assessments-quizzes#1615]
The following 2 questions are not there in the list:

What is the difference between heap and stack?
Which method do you need to call in order to suppress finalization of an object?

**Comment by Ebazhanov** [comment]
@kaushalarwal thanks a lot for creating this issue, but could you also provide questions and all answers together? If not I will close this issue. Thank you in advance!

**Comment by TDLemonNovecento** [comment]
Here are other questions that are missing:


What is a difference between global variable and persistent variables?
o Global variables have a higher performance overheadthan persistent variables.
o Global variables remain in memory after clear all; persistent variables do not.
o Global variables can be used to cache data in memory; persistent variables cannot.
o Global variables are accessible outside the function scope; persistent variables are not.

I think here the last option is correct (though I am not a matlab pro)

How is the random seed for MATLAB's random number generator first initializedin a MATLAB Session?
o Seed is undefined until it is initialized by the user.
o Seed is set to a value based on the current time when user first calls rand()
o Seed is set to a value based on the current time on startup.
x Seed is set to a static default value on startup.
(See https://ch.mathworks.com/help/matlab/math/why-do-random-numbers-repeat-after-startup.html for reference)

**Comment by TDLemonNovecento** [comment]
Aaand one more

At what will MATLAB look first for a called function?
o functions on the path
o built-in functions
o functions within the current file
o functions within the current directory

**Comment by Ebazhanov** [comment]
Thank you guys @kaushalarwal @TDLemonNovecento! 👍  everything were successfully added https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/master/matlab/matlab-quiz.md
