### ISSUE TITLE
No google ads answer 

### ISSUE THREAD

**Issue by codenamekozak** [Ebazhanov/linkedin-skill-assessments-quizzes#1645]
Please post google ads quiz ans for LinkedIn.advance thanks

**Comment by Ebazhanov** [comment]
Hello, @codenamekozak! I added questions https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/master/google-ads/google-analytics-quiz.md
of course I don't know the answers 
So want to close your issue FYI
