### ISSUE TITLE
Add answers to Eclipse questions.

### ISSUE THREAD

**Issue by monkrus** [Ebazhanov/linkedin-skill-assessments-quizzes#1648]
Add answers to Eclipse questions 16-22

https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/master/eclipse/eclipse-quiz.md

**Comment by Ebazhanov** [comment]
good catch @monkrus looking forward to see the answers soon! :point_up:

**Comment by Suvradippaul** [comment]
Hello @Ebazhanov, can I work on this issue ??
Thank You

**Comment by Ebazhanov** [comment]
@Suvradippaul sure, thank you in advance! 👍
