### ISSUE TITLE
Some questions to be added into the php quiz

### ISSUE THREAD

**Issue by gudata** [Ebazhanov/linkedin-skill-assessments-quizzes#1652]
![Selection_105](https://user-images.githubusercontent.com/25951/120757327-19a48a00-c519-11eb-94a9-44da890381b0.png)
![Selection_103](https://user-images.githubusercontent.com/25951/120757346-1f9a6b00-c519-11eb-954d-824d17d7c184.png)
![Selection_102](https://user-images.githubusercontent.com/25951/120757356-22955b80-c519-11eb-83ad-2e35cfc1dc30.png)
![Selection_101](https://user-images.githubusercontent.com/25951/120757369-2628e280-c519-11eb-9e5e-c835e7d0a6a5.png)
![Selection_100](https://user-images.githubusercontent.com/25951/120757380-2923d300-c519-11eb-9bdf-4b03713a2e74.png)

**Comment by gudata** [comment]
Please add warning in the php quiz that some of the questions are badly abbreviated and are difficult to search.

**Comment by Ebazhanov** [comment]
how to do it @gudata :confused:? if you have any suggestion I would be happy to accept them, any PR's are welcome :pray:

**Comment by Ebazhanov** [comment]
@gudata thanks for rising the issue, @lnugraha thanks for implementing!
