### ISSUE TITLE
mysql question

### ISSUE THREAD

**Issue by gudata** [Ebazhanov/linkedin-skill-assessments-quizzes#1654]
![Selection_108](https://user-images.githubusercontent.com/25951/120761163-9174b380-c51d-11eb-82c9-13ff66071b79.png)

**Comment by gudata** [comment]
![Selection_107](https://user-images.githubusercontent.com/25951/120761204-9afe1b80-c51d-11eb-8fa0-2b9d3fc480e8.png)

**Comment by Ebazhanov** [comment]
Thanks a lot @gudata @gudata! :beers:
