### ISSUE TITLE
Java Assessment missing questions

### ISSUE THREAD

**Issue by Selanda** [Ebazhanov/linkedin-skill-assessments-quizzes#1660]
In taking the Java Assessment today I found several questions that were not included in [java/java-quiz.md](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/master/java/java-quiz.md).

<hr>

What is the value of myCharaceter after line 3 is run?

```
1: public class Main {
2:   public static void main (String[] args) {
3:     char myCharacter = "piper".charAt(3);
4:   }
5: }
```

- [ ] p
- [ ] r
- [ ] e
- [ ] i

<hr>

When should you use a static method?

- [ ] when your method is related to the object's characteristics
- [ ] when you want your method to be available independently of class instances
- [ ] when your method uses an object's instance variable
- [ ] when your method is dependent on the specific instance that calls it

<hr>

What phrase indicates that a function receives a copy of each argument passed to it rather than a reference to the objects themselves?

- [ ] pass by reference
- [ ] pass by occurrence
- [ ] pass by value
- [ ] API call

<hr>

In Java, what is the scope of a method's argument or parameter?

- [ ] inside the method
- [ ] both inside and outside the method
- [ ] neither inside nor outside the method
- [ ] outside the method

<hr>

What is the output of this code?

```
public class Main {
  public static void main (String[] args) {
    int[] sampleNumbers = {8, 5, 3, 1};
    System.out.println(sampleNumbers[2]);
  }
}
```

- [ ] 5
- [ ] 8
- [ ] 1
- [ ] 3

<hr>

Which change will make this code compile successfully?

```
1: public class Main {
2:   String MESSAGE ="Hello!";
3:   static void print(){
4:     System.out.println(message);
5:   }
6:   void print2(){}
7: }
```

- [ ] Change line 2 to `public static final String message`.
- [ ] Change line 6 to `public void print2(){}`.
- [ ] Remove the body of the `print2` method and add a semicolon.
- [ ] Remove the body of the `print` method.

**Comment by Ebazhanov** [comment]
Great job @Selanda @lnugraha! :metal:
