### ISSUE TITLE
React Q46 What value of button will allow you to pass the name of the person to be hugged?

### ISSUE THREAD

**Issue by garkuwa** [Ebazhanov/linkedin-skill-assessments-quizzes#1716]
Hello everybody,

I might be wrong, but I believe React Q46 has a wrong answer or is misleading.

**What value of button will allow you to pass the name of the person to be hugged?**

```
class Huggable extends React.Component {
  hug(id) {
    console.log("hugging " + id);
  }

  render() {
    let name = "kitteh";
    let button = // Missing Code
    return button;
  }
}
```
If I want the `kitteh` value to be passed into button when it's clicked, I'd write something like:
```
...
let button = <button onClick={() => this.hug(name)}>Hug Button</button>
 return button;
```

However, the answer is `<button onClick={(name) => this.hug(name)>Hug Button</button>`, which in my opinion means that the `hug` method would get the click event every time the button is clicked, and this is not what the question asks.

**Comment by Ebazhanov** [comment]
Hello, Taras @garkuwa! Thanks for the great explanation, can you create pull request with your suggestion? Thank you in advance!

**Comment by garkuwa** [comment]
I'll prepare a PR soon

**Comment by Ebazhanov** [comment]
Since the answer were successfully modified, going to close this issue FYI @garkuwa
