### ISSUE TITLE
Pull updates from my fork (Autodesk Fusion 360)

### ISSUE THREAD

**Issue by djayor** [Ebazhanov/linkedin-skill-assessments-quizzes#1752]
Hi,
I'm trying to add some Q&A from other skills that are not listed, but I don't have permissions.
Can you pull the changes from my [fork](https://github.com/djayor/linkedin-skill-assessments-quizzes) to help the community?

Thanks

**Comment by Ebazhanov** [comment]
Hello, @djayor! Thanks creating this ticket, yes I can do it easily but if you have time you can try to do it again like all other people make sure you follow Tips from this [gist](https://gist.github.com/rradfar/88f3f0375f8c9dc16c5658e3e9b4e739) 
what I wanted from is to try again but before please unfork my repo and do this action again 
- Fork 
- Clone 
Or maybe you helps Tips from this [gist](https://gist.github.com/rradfar/88f3f0375f8c9dc16c5658e3e9b4e739) as I said - `To sync a fork` or `To reset a local master branch to the upstream`

Best of luck and let me know if I should do copy/past 👍

**Comment by Ebazhanov** [comment]
I am sure you managed it, since I merged your PR's, well done!!!!
