### ISSUE TITLE
 Answer given  for Wordpress 43rd question skill test 

### ISSUE THREAD

**Issue by MrObOt07** [Ebazhanov/linkedin-skill-assessments-quizzes#1812]
Which software development principle, often used in WordPress, aims to reduce the repetition of code?
 RRR
 WET
 DRY
 KISS
 
 Answers - DRY(Don't Repeat Yourself)

**Comment by Ebazhanov** [comment]
thanks @MrObOt07 👍  I added it directly to master, if you find something else feel free create pull request, will be happy to merge! Have a great day!
