### ISSUE TITLE
Replace corrupt images for Microsoft Excel Q77, Q79, Q80 and Q81

### ISSUE THREAD

**Issue by monkrus** [Ebazhanov/linkedin-skill-assessments-quizzes#1971]
Please replace corrupt images under Q77, Q79, Q80, and Q81.

https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/master/microsoft-excel/microsoft-excel-quiz.md

**Comment by RhnSharma** [comment]
I would like to take this one.
