### ISSUE TITLE
Excel Q31 has incorrect answer

### ISSUE THREAD

**Issue by Leader-board** [Ebazhanov/linkedin-skill-assessments-quizzes#1995]
https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/master/microsoft-excel/microsoft-excel-quiz.md

> Q31. Which Excel add-in will help you find a target result by varying multiple inputs to a formula?

It's given as 3, but the answer is 1. Goal Seek has only one input variable that can be entered (see screenshot):

![image](https://user-images.githubusercontent.com/42085404/127329981-b3e5dfc0-b599-460f-9e52-a9757c5a02cf.png)

**Comment by Ebazhanov** [comment]
@Leader-board thanks for your catch and explanation 👍 , can you please create pull request we can merge it quickly?

**Comment by Leader-board** [comment]
@Ebazhanov Would you be able to do it for me, since you (but not I) have pull access?

**Comment by Ebazhanov** [comment]
yes sure, just want to double check what is the right answer, pls write it down
thank you in advance!
![image](https://user-images.githubusercontent.com/13170022/128599516-409e3e9f-a302-4242-83d4-a43f13302457.png)

**Comment by Leader-board** [comment]
Sorry @Ebazhanov, I was referring to Q10. Specifically,

> Q10. When using Goal Seek, you can find a target result by varying ___ at most.

It is given as "three inputs", but should be "one input"

**Comment by Ebazhanov** [comment]
ok, got it 👍  thanks again @Leader-board for your great input!
will update it now!
