### ISSUE TITLE
C (Programming Language), Q2

### ISSUE THREAD

**Issue by baermb** [Ebazhanov/linkedin-skill-assessments-quizzes#2007]
The answer appears to be incorrect.
Currently:
 A is greater then B C is fun!

Should be:
A is greater then B
C is fun!

Either that or the endline should be removed from  the 'printf("A is greater than B\n");' statement.

**Comment by Ebazhanov** [comment]
Hello, @baermb! Thanks for suggestions can you please take a look again is it correct now (I did formatting a little bit) 
https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/master/c-(programming-language)/c-quiz.md
thank you in advance! 
![image](https://user-images.githubusercontent.com/13170022/128599205-67fca454-c1c9-4413-bb77-0cf4e480ad88.png)

not sure about removing `printf` maybe it comes originally from the question.

**Comment by Ebazhanov** [comment]
@baermb thanks for raising this issue, going to close it. If you feel that there is still something to improve pls let me know! Thanks
