### ISSUE TITLE
Linux - Question 37, the answer is wrong

### ISSUE THREAD

**Issue by emilas44** [Ebazhanov/linkedin-skill-assessments-quizzes#2012]
Correct answer is:  "configuring DNS name servers"
/etc/hostname is for "setting the hostname"

actually none of the answers is correct.... in /etc/hosts you set the mappings for domain names and IP addresses

**Comment by Ebazhanov** [comment]
Thanks for investigation @emilas44 👍 , I will leave it as `configuring DNS name servers` because as you said it might be the most close to the right answer.
