### ISSUE TITLE
Missing question in Microsoft Word Accessment

### ISSUE THREAD

**Issue by AdvMaple** [Ebazhanov/linkedin-skill-assessments-quizzes#2068]
![image](https://user-images.githubusercontent.com/46006210/129469641-66f8ac9e-92b3-40da-a038-93b6188451ad.png)

Answer I used: Use the Clipboard to copy and paste text into the Word document

**Comment by Ebazhanov** [comment]
Thanks a lot @AdvMaple, i have added your question to codebase! If you have anything else pls let me know!
