### ISSUE TITLE
no answers to Google AD??

### ISSUE THREAD

**Issue by cheesemate** [Ebazhanov/linkedin-skill-assessments-quizzes#2122]
Please provide solution's to google ad assessment.
Keep doing this great work 
Thanks

**Comment by Ebazhanov** [comment]
Hello, @cheesemate please check it out now https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/master/google-ads/google-analytics-quiz.md should be more answers! Feel free to raise an issue if you need anything else! 
Thanks a lot @alexiismua for your valuable contribution! 👍
