### ISSUE TITLE
To Add one more question in php 

### ISSUE THREAD

**Issue by usmanehsan0613** [Ebazhanov/linkedin-skill-assessments-quizzes#2146]
if( 1 == true){
     echo "1";
 }
 
 if( 1 === true){
     echo "2";
 }
 
 if("php" == true){
     echo "3";
 }
 
 if("php" === false){
     echo "4";
 }

Options are 

// 134
 // 13
 //1 
 // 123

Correct one is 13, because === also checks for type on both sides.

**Comment by Ebazhanov** [comment]
Hello, @usmanehsan0613! Thanks for the new question, could you also add the question itself please, like on format below:

```
Q... This is the question
- [ ]
- [ ]
- [ ]
```

**Comment by usmanehsan0613** [comment]
Q-- What below print will print

      if( 1 == true){
            echo "1";
      }
      
      if( 1 === true){
          echo "2";
      }
      
      if("php" == true){
          echo "3";
      }
      
      if("php" === false){
          echo "4";
      }

- [-] 134
- [x] 13
- [-] 1
- [-] 123

//  Prints 13,  on PHP Version 7.3.28

**Comment by Ebazhanov** [comment]
Thanks for quick reply @usmanehsan0613 👍 , done!
