### ISSUE TITLE
In Spring Framework Assessment

### ISSUE THREAD

**Issue by sanskriti1234** [Ebazhanov/linkedin-skill-assessments-quizzes#2163]
![image](https://user-images.githubusercontent.com/25322828/132003692-2b375afd-e56b-4756-9810-eb692dbdc881.png)
This Question not added also 
question No.  
49, 52, 50 
don't have Answers.

**Comment by Ebazhanov** [comment]
Thanks for raising the issue @sanskriti1234 👍 , I have added your question! all good!
