### ISSUE TITLE
Add more questions on Django

### ISSUE THREAD

**Issue by ba1x** [Ebazhanov/linkedin-skill-assessments-quizzes#2183]
**Q52. You are building a web application using a React front end and a Django back end. For what will you need to provision?**

- [ ] an NGINX web server
- [ ] a NoSQL database
- [ ] a larger hard drive
- [ ] CORS middleware

**Q53. To expose an existing model via an API endpoint, what do you need to implement?**

- [ ] an HTTP request
- [ ] a JSON object
- [ ] a query
- [ ] a serializer

**Q54. How would you stop Django from performing database table creation or deletion operations via migrations for a particular model?**

- [ ] Run the `migrate` command with `--exclude=[model_name]`.
- [ ] Move the model definition from `models.py` into its own file.
- [ ] Set `managed=False` inside the model.
- [ ] Don't run the `migrate` command.

**Comment by Ebazhanov** [comment]
Thank you for your great input @ba1x, done! :muscle:
