### ISSUE TITLE
Add more questions on Linux

### ISSUE THREAD

**Issue by ba1x** [Ebazhanov/linkedin-skill-assessments-quizzes#2184]
**Q56. How does TCP Wrappers differ from a firewall?**

- [ ] Firewalls are only service specific, whereas TCP Wrappers can block all traffic.
- [ ] TCP Wrappers works at the network layer, so it blocks traffic before the firewall even sees it.
- [ ] Firewalls easily spawn commands to operate on connection data, whereas TCP Wrappers cannot.
- [ ] TCP Wrappers works at the application layer, so it can make access decisions on encrypted data.

**Q57. As root, you set execute permissions for user, group, and other on a directory. Now users can do what?**

- [ ] They can execute files in it.
- [ ] They can traverse it.
- [ ] They can read files in it.
- [ ] They can delete files in it.

**Q58. What will this command print?**

```
echo "Thu Jun 4 15:45:45 PDT 2020" | cut -f3 -d" " 
```

- [ ] It will print nothing.
- [ ] Thu Jun 4 15:45:45 PDT 2020
- [ ] 0.6567708333333333
- [x] 4

**Q59. How can you improve this code snippet?**

```
if ls /etc/passwd &> /dev/null
then
    echo "exists"
fi
```

- [ ] The code snippet cannot be improved, this is a valid way of checking for the existence of a file.
- [ ] Use Bash's built-in `[[ ]]` test conditions instead of the `ls` command.
- [ ] The redirect to `/dev/null` will silence the return code invalidating the conditional. Removing the redirect will solve this.
- [ ] The `ls` command will output the name of the file to the screen. Running `ls` in quiet mode will improve the code snippet.

**Comment by Ebazhanov** [comment]
Thank you @ba1x :fire:, I have just added your questions! Have a good day!
