### ISSUE TITLE
Issue regarding Unity 3d answer

### ISSUE THREAD

**Issue by ankiii07** [Ebazhanov/linkedin-skill-assessments-quizzes#2196]
I here provide correct answer of the Unity skill test of rest questions
![WhatsApp Image 2021-09-11 at 01 46 01](https://user-images.githubusercontent.com/66520710/132912673-28f777e6-5c94-4bad-94f5-5376dc823375.jpeg)
![WhatsApp Image 2021-09-11 at 01 46 01 (2)](https://user-images.githubusercontent.com/66520710/132912677-ca75780d-5a04-4165-9177-2e146f7ba889.jpeg)
![WhatsApp Image 2021-09-11 at 01 46 01 (1)](https://user-images.githubusercontent.com/66520710/132912679-15bd4931-d175-4246-9416-abe3af4ad8e4.jpeg)

**Comment by Ebazhanov** [comment]
Thank you @ankiii07 👍 , I have updated as you suggested! 
https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/master/unity/unity-quiz.md
