### ISSUE TITLE
There is no ANSWER in Q54 >> linux

### ISSUE THREAD

**Issue by yusufadell** [Ebazhanov/linkedin-skill-assessments-quizzes#2200]
Q54. To elevate privileges using the sudo command, a user must .

I believe that it would like the following
​
- [ ] enter the root user's password
- [x] enter their own password
- [ ] enter the sudo user's password
- [ ] change to the root group

**Comment by Ebazhanov** [comment]
Hello, @yusufadell! I found some reference link for this question https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/a40f2d6aa51592d1361e135297c55096be0077c8/linux/linux-assesment.md#L437-L437

If you still think that your answer is right please provide some reference or explanation, thank you in advance!

**Comment by Ebazhanov** [comment]
Thank you Guys! Great job! :beers:
