### ISSUE TITLE
Photoshop wrong answer

### ISSUE THREAD

**Issue by dasut** [Ebazhanov/linkedin-skill-assessments-quizzes#2244]
Which command makes it easier to adjust selected areas of color in two images in order to make them similar?

The answer is Match Color, not Hue/Saturation.

This was one of my practice questions I was doing to see how confident I should be with the answers on this repo.

**Comment by Ebazhanov** [comment]
Thanks @dasut, updated 👍 
https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/master/adobe-photoshop/adobe-photoshop-quiz.md
