### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by dasut** [Ebazhanov/linkedin-skill-assessments-quizzes#2245]
Q26.Which of these would give a block element rounded corners?

 corner-curve: 10px
 border-corner: 10px
 border-radius: 10px
 corner-radius: 10px

correct answer is corner-radius, not border-radius

**Comment by dasut** [comment]
This might be my mistake. A very similar question was graded with corner-radius being the answer. I then came across the question again, and the posted answer is the correct one. It's possible there was a very similar question that had a different answer.

**Comment by Ebazhanov** [comment]
FYI found some prof from official doc here it is 
https://www.w3schools.com/css/css3_borders.asp

**Comment by anmol-19** [comment]
I think border radius should be the correct answer.
you can crosscheck it from here also - https://www.w3schools.com/css/css3_borders.asp

**Comment by Ebazhanov** [comment]
Thank you Guys 👍  will close this issue, let's keep `border-radius: 10px` as the right answer. Have a great day!
