### ISSUE TITLE
Word question missing to help everyone

### ISSUE THREAD

**Issue by cffnascimento** [Ebazhanov/linkedin-skill-assessments-quizzes#2311]
![WhatsApp Image 2021-10-01 at 10 54 40 AM](https://user-images.githubusercontent.com/91706968/135549913-0cd3585a-6a08-4043-8b3f-2e872d286ad9.jpeg)

**Comment by Ebazhanov** [comment]
@cffnascimento @parikhparth23 thank you guys! 👍
