### ISSUE TITLE
New Git quizz question

### ISSUE THREAD

**Issue by ODGodinho** [Ebazhanov/linkedin-skill-assessments-quizzes#2316]
Just wanted to send this new question on the Git test, I'm not sure of the answer, if anyone knows create a PR.

![Screenshot_1](https://user-images.githubusercontent.com/8422396/135700894-e5b19624-ecf6-4b35-9bf3-0b55cbf3ac2b.png)

**Comment by Itashamodi** [comment]
I want to work on this. Please assign me

**Comment by ODGodinho** [comment]
> I want to work on this. Please assign me

wouldn't it be just to open a PR, with the link to this issue?

how do I attribute you to that?
