### ISSUE TITLE
C (Programming Language), Q35 discussion

### ISSUE THREAD

**Issue by SzymonKrzanowski** [Ebazhanov/linkedin-skill-assessments-quizzes#2322]
There is no answer, I think it should be:
#ifndef MYLIB_H
#define MYLIB_H

// mylib.h content

#endif /* MYLIB_H */

**Comment by Onkar-Birajdar** [comment]
Hey, Thanks for pointing it out. I have done the work for it. Issue resolved. Please accept my pull request.

**Comment by parikhparth23** [comment]
@Onkar-Birajdar, thanks for the fix. It would be good if you also close the issues (if you have the permission) which are fixed so that it does not appear in `Issues` section.

**Comment by Ebazhanov** [comment]
THank you @SzymonKrzanowski for raising this issue 🥇 , thank you @parikhparth23 @Onkar-Birajdar for supporting 👍 !
