### ISSUE TITLE
microsoft-word/microsoft-word-quiz.html Q62 same as Q5

### ISSUE THREAD

**Issue by invidu** [Ebazhanov/linkedin-skill-assessments-quizzes#2419]
Q62 is incorrect and the same question as Q5.

I would've pulled it and corrected it myself, but I'm abso-bloody-lutely new to this and I couldn't figure out how to do this. Would appreciate if someone can tell me.

**Comment by Ebazhanov** [comment]
solved thank you guys 👍 ! @invidu, @ruslanbes
