### ISSUE TITLE
2 new questions for Java

### ISSUE THREAD

**Issue by parikhparth23** [Ebazhanov/linkedin-skill-assessments-quizzes#2424]
<img width="1204" alt="Screen Shot 2021-10-13 at 9 29 52 AM" src="https://user-images.githubusercontent.com/10181201/137176508-8c0b99a5-7467-4988-9ee7-bfb30545e008.png">

<img width="1141" alt="Screen Shot 2021-10-13 at 9 35 06 AM" src="https://user-images.githubusercontent.com/10181201/137176523-f3d25e57-9893-4260-9477-ed6fab959f56.png">

**Comment by parikhparth23** [comment]
I am working on it.

**Comment by Ebazhanov** [comment]
👍
