### ISSUE TITLE
Update question text for Q23 MS Word

### ISSUE THREAD

**Issue by wolfkin** [Ebazhanov/linkedin-skill-assessments-quizzes#2532]
just updating a question on the MS Word Assessment

[Q23](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/master/microsoft-word/microsoft-word-quiz.md#q23-what-can-you-not-insert-into-a-word-document-from-the-insert-tab)

> #### Q23. What can you **NOT** insert into a Word document from the Insert tab?
> 
> - [x] a sketch
> - [ ] a symbol
> - [ ] a 3D model
> - [ ] an equation

It should be updated to be

#### Q23. Which object type can you *not* insert into a Word document from the **Insert** tab?

- [x] a sketch
- [ ] a symbol
- [ ] a 3D model
- [ ] an equation

```
#### Q23. Which object type can you *not* insert into a Word document from the **Insert** tab?

- [x] a sketch
- [ ] a symbol
- [ ] a 3D model
- [ ] an equation
```

As per 
![image](https://user-images.githubusercontent.com/6678474/138361721-cace68a9-07f0-4106-81fe-fc3f5f971e31.png)

**Comment by masoudk1990** [comment]
@grzegorzp4tyk Yes correct answer is 2. [Here is the reference](https://stackoverflow.com/a/44913313/1573267)
@Ebazhanov I added this in #2697 two days ago, I think this issue is safe to get closed.

**Comment by GalexyN** [comment]
I believe this is resolved as well can't find the pr for it though @Ebazhanov

**Comment by Ebazhanov** [comment]
Thank you @wolfkin for raising this issue and @GalexyN for reminder 👍
