### ISSUE TITLE
Update Quetion and answers for Q67 MS Outlook

### ISSUE THREAD

**Issue by wolfkin** [Ebazhanov/linkedin-skill-assessments-quizzes#2533]
[Link](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/master/microsoft-outlook/microsoft-outlook-quiz.md#q67-you-are-viewing-your-calendar-in-work-week-view-and-see-a-thin-horizonatal-line-running-iewing-your-calendar-in-work-week-view-and-see-a-thin-horizontal-line-running-across-all-days-at-the-230-pm-position-what-does-this-tell-you)

Currently
>### Q67. You are viewing your calendar in work week view and see a thin horizonatal line running IEWING YOUR CALENDAR IN WORK WEEK VIEW AND SEE A THIN HORIZONTAL LINE RUNNING ACROSS ALL DAYS AT THE 2:30 P.M. POSITION. WHAT DOES THIS TELL YOU?

Should be

### Q67. You are viewing your calendar in Work Week view and see a thin horizontal line running across all days at the 2:30 p.m. position. What does this tell you?

- [ ] Your next appointment is at 2:30 p.m.
- [ ] You have a recurring appointment at 2:30 p.m.on each day of the week.
- [ ] Your calendar is free from 2:30 p.m. on.
- [ ] The current time is 2:30 p.m.

```
### Q67. You are viewing your calendar in Work Week view and see a thin horizontal line running across all days at the 2:30 p.m. position. What does this tell you?

- [ ] Your next appointment is at 2:30 p.m.
- [ ] You have a recurring appointment at 2:30 p.m.on each day of the week.
- [ ] Your calendar is free from 2:30 p.m. on.
- [ ] The current time is 2:30 p.m.
```
(answer unconfirmed)

![image](https://user-images.githubusercontent.com/6678474/138365609-aef6aff2-3b93-4e0c-b790-6f1f7d1e2df5.png)

**Comment by blackmoonfank** [comment]
![image](https://user-images.githubusercontent.com/14941607/141050159-1a8bdd31-d173-416f-ba65-c3b6f4ca3b78.png)

I agree with answer ,
