### ISSUE TITLE
IT Operations Quiz

### ISSUE THREAD

**Issue by AlexAVL** [Ebazhanov/linkedin-skill-assessments-quizzes#2570]
Many of the IT operations questions are inaccurate, ambiguous, or have the wrong answer marked as correct.

This questionnaire would screen out people that have a high level of IT knowledge, and make any company using it seem like they don't know the field.

E.g.

Q2 - USB-C can support display port, but does not always have DLP Alt mode
Q3 - The Front IO panel contains the power etc. switches
Q4 - Sometimes you need to hold shift to get to recovery mode to fix an issue like that
Q5 - Several monitors have resolution selection
Q10 - Mass storage (m.2) is often on the motherboard, as is active cooling on high end boards
Q11 - RAID was originally Redundant Array of Inexpensive Disks, and is still commonly referred to as that
Q11 - With a modular PSU (as mentioned later), this would be used for the PSU side too
Q17 - An SSD can be connected over Serial Attached SCSI, and often is
Q19 - The answer has nothing to do with keeping the computer running longer
Q20 - The drive also reads media, because a CD/DVD is a storage medium. Storage media and media files are both media of different types.

I could go on.

**Comment by Ebazhanov** [comment]
Hello, @AlexAVL! Thank you for your effort and issue if you think we can improve something feel free to create pull request with reference links to the right answers or explanation thank you!

**Comment by AlexAVL** [comment]
@Ebazhanov It's not that it needs improving, it needs completely rewriting. This will be causing active harm to candidates applying to jobs and the companies that use it. I would suggest you take the quiz down or mark it as not for use until someone can produce a new one.

**Comment by Ebazhanov** [comment]
ok, got your idea FYI I am not going to hide or remove this quiz
