### ISSUE TITLE
Q63 AWS Format in MD file

### ISSUE THREAD

**Issue by ckvignesh** [Ebazhanov/linkedin-skill-assessments-quizzes#2588]
This needs change... have raised a PR for it.
![Before](https://user-images.githubusercontent.com/61013244/139628449-94537bb6-e597-4f5e-b441-533995a5e638.png)

**Comment by Ebazhanov** [comment]
Thanks for raising this issue, I saw your PR related to this improvements! Good job! 👍

**Comment by ckvignesh** [comment]
Thanks :)
