### ISSUE TITLE
About Q27 on Java assessment

### ISSUE THREAD

**Issue by doriancuentas** [Ebazhanov/linkedin-skill-assessments-quizzes#2590]
> Q27. Which statement is NOT true?
>     An anonymous class may specify an abstract base class as its base type.
>     An anonymous class does not require a zero-argument constructor.
>     An anonymous class may specify an interface as its base type.
>     An anonymous class may specify both an abstract class and interface as base types.

Question 27 on Java assessment [Q27](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/master/java/java-quiz.md#q27-which-statement-is-not-true) is really confusing, if is referring to the base class, there is no need for a zero-argument constructor on base class; if is referring to the anonymous class the constructor is not required as well.
```
package main;

public class Test{
    public static abstract class T{
        protected String i;
        // public T(){ //Zero-Parameter constructor no needed
        //     System.out.println("Zero constructor");
        // }
        public T(String i){
            this.i = i;
            System.out.println("Non-Zero constructor");
        }
        public void p(){
            System.out.println(this.i);
        }
        public abstract void b();
    }
    public static void main(String[] args){
        T t = new T("Hola"){
            {//this constructor is not required 
                this.i = "- " + this.i;
            }
            public void b(){}
        };
        t.p();
    }
}

// output tested with java 8 & 11
$ javac main/Test.java && java main.Test
Non-Zero constructor
- Hola

```

**Comment by Ebazhanov** [comment]
Thanks for deep dive and detail explanation, any suggestion what we can do with this? e.g. you can add your code in playground and add this link with reference or do something please feel free create PR

**Comment by doriancuentas** [comment]
Current "right" answer is :
- "An anonymous class does not require a zero-argument constructor."

I think thing the right answer is :
- An anonymous class may specify both an abstract class and interface as base types.

because that would be the statement that comply with the "**NOT** true" condition

I would change the answer and add this explanation
**Explanation**: anonymous classes implicitly specify only one base.

My reasoning is that anonymous classes cannot implement more than one parent, unless there is another way apart from the example code I provided.

**Comment by Ebazhanov** [comment]
yes, why not we can add one more answer and add explanation, please feel free to create PR! Have a great day Dorian!
