### ISSUE TITLE
A question with two Answers -- Linux Question #33

### ISSUE THREAD

**Issue by killerfrost22** [Ebazhanov/linkedin-skill-assessments-quizzes#2606]
Linux Question #33 which has two answers 
Please explain why these two didn't work. 
Thank you!
![4f4daef189041d8a499c2d3ba8cb11a](https://user-images.githubusercontent.com/36581618/140588861-77b10d4f-bb00-4ffb-a6c6-271c5931e365.png)

**Comment by Ebazhanov** [comment]
I saw your PR @killerfrost22, it was successfully merged. Please let me know if we can close this issue

**Comment by killerfrost22** [comment]
Yup. We can close this
