### ISSUE TITLE
Add new questions for Maven 

### ISSUE THREAD

**Issue by bilal966** [Ebazhanov/linkedin-skill-assessments-quizzes#2658]
There are couple of news questions introduced by LinkedIn.

**Comment by bilal966** [comment]
> Hello @bilal966 , thank you for submitting an issue! 👍 We highly appreciate it if you work on it as well.

would you please assign this issue to me?

**Comment by Ebazhanov** [comment]
well done, thank you for your contribution @bilal966! 👍
