### ISSUE TITLE
Add Questions to PHP

### ISSUE THREAD

**Issue by fencerven** [Ebazhanov/linkedin-skill-assessments-quizzes#2668]
**Which script might be used to continue a user's search for music, across different webpages?**

```
1 <?php
2 start_session();
3 $music = $_SESSION['music'];
4 ?>
```
 
```
1 <?php
2    session_start();
3    $music = $SESSION['music'];
4 ?>
```
 
```
1 <?php
2   start_session();
3   $music =$session['music'];
4 ?>
```
 
```
1 <?php
2  session_start();
3  $music = $_SESSION['music'];
4 ?>
```

**Which PHP script finds the earliest and latest dates from an array?**
```
1 <?php
2 $dates = array('2018-02-01', '2017-02-02', '2015-02-03');
3 echo "Latest Date: ". max($dates)."\n";
4 echo "Earliest Date: ". min($dates)."\n";
5 ?>
```
 
```
1 <?php
2 $dates = array('2018-02-01', '2017-02-02', '2015-02-03');
3 echo "Latest Date: ". min($dates)."\n";
4 echo "Earliest Date: ". max($dates)."\n";
5 ?>
```
 
```
1 <?php
2 $dates = array('2018-02-01', '2017-02-02', '2015-02-03');
3 echo "Latest Date: ". ($dates)."\n";
4 echo "Earliest Date: ". ($dates)."\n";
5 ?>
```
 
```
1 <?php
2 $dates = array('2018-02-01', '2017-02-02', '2015-02-03');
3 echo "Latest Date: " max($dates)."\n";
4 echo "Earliest Date: " min($dates)."\n";
5 ?>
```

**What is the resulting output of this for statement?**
```
1  $kilometers = 1;
2 for (;;) {
3    if ($kilometers > 5) break;
4       echo "$kilometers kilometers = ".$kilometers*0.62140. " miles. <br />";
5    $kilometers++;
6  }
```

1 kilometers = 0.6214 miles.
2 kilometers = 1.2428 miles.
3 kilometers = 1.8642 miles.
4 kilometers = 2.4856 miles.
5 kilometers = 3.107 miles. 
 
1 kilometers = 0.6214 miles.
2 kilometers = 1.2428 miles.
3 kilometers = 1.8642 miles
4 kilometers = 2.4856 miles.
5 kilometers = 3.107 miles.
6 kilometers = 3.7284 miles.
 
2 kilometers = 1.2428 miles.
3 kilometers = 1.8642 miles.
4 kilometers = 2.4856 miles.
5 kilometers = 3.107 miles.  
 
FATAL ERROR syntax error, unexpected ')', expecting ';' on line number 2

**Comment by Rafat97** [comment]
Which script might be used to continue a user's search for music, across different webpages?

Answer: (4)
```php
<?php
  session_start();
  $music = $_SESSION['music'];
 ?>
```

**Comment by Ebazhanov** [comment]
yes sure, go ahead @Rafat97, thanks

**Comment by Rafat97** [comment]
@Ebazhanov , Check the PR [#2669 ](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/pull/2669)
