### ISSUE TITLE
New question to Object Oriented Programming skill badge quiz

### ISSUE THREAD

**Issue by grzegorzp4tyk** [Ebazhanov/linkedin-skill-assessments-quizzes#2716]
### What is the most accurate example of the Liskov substitution principle? (needs choosing right answer and some explanation)

- [ ] 1.
```java
    public class Car{
        public void fly(){}
    }
    public class Tesla extends Car{}
    public class Honda extends Car{}
```
- [x] 2.
```java
    public class Car{
    }
    public class FlyingCar extends Car{
        public void fly(){}
    }
    public class Tesla extends FlyingCar{}
    public class Honda extends Car{} 
```
- [ ] 3.
```java
    public class Car{
    public void fly(){}
    }
    public class Tesla Car{}
    public class Honda Car{}
```
- [ ] 4.
```java
    public class Car{
    }
    public class FlyingCars extends Car{
        public void fly(){}
    }
    public class Tesla FlyingCar{}
    public class Honda Car{} 
```

**Comment by grzegorzp4tyk** [comment]
> The principle defines that objects of a superclass shall be replaceable with objects of its subclasses without breaking the application. That requires the objects of your subclasses to behave in the same way as the objects of your superclass. 

That would mean the answer no. **2** is correct.

based on:
[1](https://www.digitalocean.com/community/conceptual_articles/s-o-l-i-d-the-first-five-principles-of-object-oriented-design#liskov-substitution-principle)
[2](https://stackify.com/solid-design-liskov-substitution-principle/)

**Comment by masoudk1990** [comment]
@grzegorzp4tyk Yes correct answer is 2. Here is the reference
@Ebazhanov I added this in #2697 two days ago, I think this issue is safe to get closed.

**Comment by Ebazhanov** [comment]
Thanks you @grzegorzp4tyk for PR and @masoudk1990 for support, closing
