### ISSUE TITLE
Q9 on Ms Project

### ISSUE THREAD

**Issue by ValyKay** [Ebazhanov/linkedin-skill-assessments-quizzes#2731]
I'm not sure of this, but I think the right answer might be "Calculate project after each edit is set to Off". The hint being "The schedule has 10,000 tasks" and the fact that the Gantt Chart does not update.

**Comment by Ebazhanov** [comment]
thanks @ValyKay, good catch 👍 updated https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/master/microsoft-project/microsoft-project-quiz.md
