### ISSUE TITLE
No answers to Solidworks

### ISSUE THREAD

**Issue by mnrazamohamed** [Ebazhanov/linkedin-skill-assessments-quizzes#2737]
No answers marked in solidworks. Please give answers to solidworks. Thank you

## SOLIDWORKS
Q30. How can you standardize lists (including the data types, the format, and more) within your organization?
 [ ] Create a custom app.
 [ ] Change object permissions.
 [ ] Use a group of site columns.
 [ ] Change user permissions for lists.

Q33. A user wants to be notified when a certain file changes. What can achieve this?
[ ] an object alert
[ ] a document alert
[ ] a site alert
[ ] a library alert

Q34. When a user tries to create a new document in a SharePoint library, the default option is not Microsoft Word. What setting do you need to change in the library?
[ ] site template
[ ] document template
[ ] versioning
[ ] audience targeting

**Comment by asbillt** [comment]
I created a pull request to add in answers and source links for questions 9 and 10.

**Comment by Vinay-1122** [comment]
Q7-A
