### ISSUE TITLE
Correct Q54 in Node.JS

### ISSUE THREAD

**Issue by edosrecki** [Ebazhanov/linkedin-skill-assessments-quizzes#2814]
https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/master/node.js/node.js-quiz.md#q54-how-would-you-determine-the-number-of-cluster-instances-to-start-when-using-the-cluster-module

`const numInstances = process.cpus().length;` is incorrect.
`const numInstances = require('os').cpus().length;` is correct.

**Comment by GalexyN** [comment]
Resolved in #2815

**Comment by Ebazhanov** [comment]
@edosrecki @GalexyN thank you guys! good job 👍
