### ISSUE TITLE
Convert Markdown to JSON object API?

### ISSUE THREAD

**Issue by ethanosullivan** [Ebazhanov/linkedin-skill-assessments-quizzes#2840]
Utilizing the this repo, would it be possible to have a JSON feed generated by the markdown files? So long as all of the quizzes follow the same format, it can look like something below.

I did a quick search for a Markdown to JSON and this looks like a possible implementation: [markdown-to-json](https://www.npmjs.com/package/markdown-to-json)

```json
{
  "version": "1.0.4",
  "updated": "2021-12-07T00:00:00.000Z",
  "skill": "Java",
  "resource": [
    "@sumanas27",
    "@ruslanbes",
    "@PROCW"
  ],
  "questions": [
    {
      "number": 1,
      "question": "Given the string \"strawberries\" saved in a variable called fruit, what would `fruit.substring(2, 5)` return?",
      "choices": [
        "rawb",
        "raw",
        "awb",
        "traw"
      ],
      "answer": "raw"
    },
    {
      "number": 2,
      "question": "How can you achieve runtime polymorphism in Java?",
      "choices": [
        "method overloading",
        "method overrunning",
        "method overriding",
        "method calling"
      ],
      "answer": "method overriding"
    }
  ]
}
```

**Comment by Ebazhanov** [comment]
Interesting idea and I remember someone already did that check it out here
![image](https://user-images.githubusercontent.com/13170022/146667953-01ad817a-1d71-403a-b992-d517b7628f17.png)
https://discord.com/channels/814212907075502150/841408311559585813/851152247287185408

**Comment by ethanosullivan** [comment]
Thanks for the share @Ebazhanov, I was able to check out the repo and [find another one created by someone else](https://github.com/Sharpness-B/linked-practice).

However, this is just doing the whole conversion into a website rather than exposing an API to something like I mentioned above. Would you know the best way to handle that?

**Comment by ethanosullivan** [comment]
After looking around GitHub's docs, they have an API where you can pull the repo contents already:

### [Get a repository README for a directory](https://docs.github.com/en/rest/reference/repos#get-repository-content)

As a result, you can find all of the repo content by using:
```
https://api.github.com/repos/Ebazhanov/linkedin-skill-assessments-quizzes/contents
```

Then, just have some script run through a loop to get the Markdown file sources using the following URL structure by replacing the `{SKILL}` placeholder:
```
https://api.github.com/repos/Ebazhanov/linkedin-skill-assessments-quizzes/contents/{SKILL}/{SKILL}-quiz.md
```

Now that the path to the Markdown files are available through the API, the next part is to have it convert to a JSON object to finalized the new API.

**Comment by Ebazhanov** [comment]
I am fine, you can do it 💯 ! if you need anything from me, you can find me in discord chat
