### ISSUE TITLE
Python assessment - two more questions

### ISSUE THREAD

**Issue by Mahmoudgalalz** [Ebazhanov/linkedin-skill-assessments-quizzes#2842]
two new questions 
With their answers  

![image](https://user-images.githubusercontent.com/42272376/146996649-222eb408-8f61-4615-85c4-eed0c42eb24e.png)
there's another one but I don't know how to contribute

**Comment by Mahmoudgalalz** [comment]
![Screenshot (28)](https://user-images.githubusercontent.com/42272376/146996828-1d79fe80-ab53-4611-a075-81c634f10f0e.png)

**Comment by fbrandao** [comment]
Heads up, the answer for the second question is wrong. You can quickly verify that by testing that expression on a terminal/script.
**The correct answer is list(reversed(range(1,11)**

**Comment by GalexyN** [comment]
Please assign @Ebazhanov  I can update the python.md with their contributions and add some refs

**Comment by GalexyN** [comment]
This as well @Ebazhanov 

Resolved in #2872

**Comment by Ebazhanov** [comment]
Thanks a lot @Mahmoudgalalz for creating this ticket 👍  and @GalexyN for your PR 🥇

**Comment by Mahmoudgalalz** [comment]
Its my pleasure @Ebazhanov
