### ISSUE TITLE
Hello my link is not correct

### ISSUE THREAD

**Issue by Mahmoudgalalz** [Ebazhanov/linkedin-skill-assessments-quizzes#2847]
Hello, I'm sorry but
Someone add me in contrubers with a wrong link 
the correct one is
www.github.com/mahmoudgalalz

Thanks❤

**Comment by Ebazhanov** [comment]
thanks letting me know, should be updated now )))
FYI all contributers plugin takes automatically default url, but in your case it took the link from your profile ![image](https://user-images.githubusercontent.com/13170022/147127512-d8400f51-3e7d-4811-a8c0-749052cc1ecf.png)
updated

**Comment by Mahmoudgalalz** [comment]
I own the other account but it for my student pack on github
Okay thanks btw
