### ISSUE TITLE
JSON - New Assessment Question

### ISSUE THREAD

**Issue by ethanosullivan** [Ebazhanov/linkedin-skill-assessments-quizzes#2854]
Here are a new question that I discovered when taking the [JSON assessment](https://ebazhanov.github.io/linkedin-skill-assessments-quizzes/json/json-quiz.html). I also selected my answer, but happy to have someone double-check to make sure it's correct:

```markdown
### Which code is a valid JSON equivalent of the key/value pair shown that also preserves the data type?

variance: -0.0823

- [ ] variance: "-0.0823"
- [ ] variance: -0.0823
- [x] "variance": "-0.0823"
- [ ] "variance": "\-0.0823"
```

![image](https://user-images.githubusercontent.com/23202467/147275970-8e62e01c-e076-4567-95f6-4807f5e30a8b.png)

**Comment by GalexyN** [comment]
PR to resolve this issue @Ebazhanov #2897
