### ISSUE TITLE
MySQL - New Assessment Questions

### ISSUE THREAD

**Issue by ethanosullivan** [Ebazhanov/linkedin-skill-assessments-quizzes#2855]
Here are some new questions that I discovered when taking the [MySQL assessment](https://ebazhanov.github.io/linkedin-skill-assessments-quizzes/mysql/mysql-quiz.html). I wasn't confident in my answers, so maybe someone else can chime-in.

```markdown
### How are permissions implemented in MySQL?
- [ ] encrypted algorithms
- [ ] access control lists
- [ ] user settings
- [ ] administrator schema

### Inside a transaction, several operations need to be performed. What would you do if an exception happens during that transaction?
- [ ] `UNDO`
- [ ] `UNCOMMIT`
- [ ] `ROLLBACK`
- [ ] `REVERSE`
```

**Comment by BHARGAVPATEL1244** [comment]
maybe ROLLBACK is answer of question-2

**Comment by Ebazhanov** [comment]
@ethanosullivan fyi, the issue have been resolved by @lnugraha

**Comment by ethanosullivan** [comment]
@Ebazhanov I checked out the MySQL page with the changes, but I only see them pasted without an answer being selected. I think they shouldn't show up unless the correct answer has been selected.

![image](https://user-images.githubusercontent.com/23202467/149344126-5c3c7995-6ed4-421e-82c4-516fbdbe1ce4.png)

**Comment by Ebazhanov** [comment]
Thanks Ethan @ethanosullivan for pointed about this, as you wish I will keep this issue open until we will get answer, have a good day!

**Comment by BHARGAVPATEL1244** [comment]
In MySQL, the user permissions are granted to the MySQL user account which determines operations that can be performed in the server.

**Comment by BHARGAVPATEL1244** [comment]
Oracle Rollback statement asks the Oracle database to rollback the entire transaction which means that it will undo or omit any work or changes that may be done by the current transaction (INSERT UPDATE OR DELETE) and the database will be brought to the previous state (which means the state of the database before the current transaction was created or started) and also it can be used to manually force any corrupt or in-doubt transaction to omit its changes and restore the database to the previous state.
