### ISSUE TITLE
REST APIs - New Assessment Question

### ISSUE THREAD

**Issue by ethanosullivan** [Ebazhanov/linkedin-skill-assessments-quizzes#2878]
Here's a new question that I discovered when taking the [REST APIs assessment](https://ebazhanov.github.io/linkedin-skill-assessments-quizzes/rest-api/rest-api-quiz.html). I answered to the best of my abilities, but I'd to have someone double-check to make sure it's correct:

```markdown
### Q1. Which REST constraint specifies that each request should stand on its own and not have a specific required order?
- [x] Uniform Interface
- [ ] Cacheable
- [ ] Stateless
- [ ] Client-Server
```

**Comment by Ebazhanov** [comment]
Thank you @ethanosullivan, added by @lnugraha

**Comment by ethanosullivan** [comment]
@Ebazhanov Was the answer confirmed that it's the correct one? I just want to make sure so we don't give the wrong info.

**Comment by Ebazhanov** [comment]
Well, I do not know, let's wait for confirmation! Thank you @ethanosullivan for your note 👍

**Comment by lucianmoldovanu** [comment]
My opinion is that the correct answer here is Stateless.

https://restfulapi.net/rest-architectural-constraints/#stateless
"...The server will not store anything about the latest HTTP request the client made. It will treat every request as new. No session, no history..."
