### ISSUE TITLE
New question for the Machine Learning Assessment

### ISSUE THREAD

**Issue by tgamauf** [Ebazhanov/linkedin-skill-assessments-quizzes#2879]
**Your data science team is often criticized for creating reports that are boring or too obvious. What could you do to help improve the team?**

- [ ] Suggest that the team is probably underfitting the model to the data.
- [ ] Suggest that unsupervised learning will lead to more interesting results.
- [ ] Make sure that they are picking the correct machine learning algorithms.
- [ ] Encourage the team to ask more interesting questions.

I would say "Encourage the team to ask more interesting questions.", but that's just a guess :)

**Comment by Ebazhanov** [comment]
Thank you @tgamauf, your issue were resolved by @lnugraha
