### ISSUE TITLE
Google Analytics - New Assessment Questions

### ISSUE THREAD

**Issue by ethanosullivan** [Ebazhanov/linkedin-skill-assessments-quizzes#2880]
Here are some new questions that I discovered when taking the [Google Analytics assessment](https://ebazhanov.github.io/linkedin-skill-assessments-quizzes/google-analytics/google-analytics-quiz.html). I also selected my answer to the best of my ability, but I'd like someone double-check to make sure it's correct:

```markdown
### Q1. You operate a website that has a three-step sign-up process. However, each step of the sign-up process loads at the same URL. If you wanted to assign a unique URL to each step and track it within Google Analytics as a pageview, what would you do?
- [ ] Use virtual pageviews.
- [ ] Configure a campaign URL.
- [ ] Use the preview tag.
- [x] Use event tracking.

### Q2. It is a best practice to always have one of what kind of view?
- [ ] property
- [ ] custom
- [ ] segmented
- [x] unfiltered

### Q3. You send an email including a link to your website without any UTM parameters. A visitor clicks that link from a secured (https) email platform such as Gmail. What source is shown for that traffic?
- [ ] Email
- [x] Referral
- [ ] (other)
- [ ] Direct
```

Additionally, I was looking around and [found this website with some of the questions for this assessment](https://prosolution342.blogspot.com/2021/02/%20Linkedin%20Assessment%20Test%20Google%20Analytics%20question-answers.html). Perhaps it's worth doing a cross-reference to see any additional Q&A that can be added to this repo.

**Comment by Ebazhanov** [comment]
Thank you @ethanosullivan, your questions were added by @lnugraha
