### ISSUE TITLE
Javascript quiz missing references on a majority of answers and missing answer entirely on some questions

### ISSUE THREAD

**Issue by GalexyN** [Ebazhanov/linkedin-skill-assessments-quizzes#2883]
Hi @Ebazhanov 

Was doing a run through of the javascript quiz and it looks like a majority of them are missing reference links. I can take this issue as well

**Comment by ethanosullivan** [comment]
@GalexyN Are reference links a requirement to the answers though? I was under the impression that they were optional. Although having the links is helpful insight to explain the correct answer.

**Comment by GalexyN** [comment]
> @GalexyN Are reference links a requirement to the answers though? I was under the impression that they were optional. Although having the links is helpful insight to explain the correct answer.

Hi @ethanosullivan 

Not sure if its required or not @Ebazhanov can answer that. However I was going to run through the file anyways to solidify knowledge so I was going to make updates anyways. Overall it'll help save someone a click in the future. Seems like a win-win to me.

PR opened #2887

**Comment by GalexyN** [comment]
Resolved through #2887 

@Ebazhanov

**Comment by Ebazhanov** [comment]
Thanks a lot 🎉 , closing!
