### ISSUE TITLE
Power BI - New Assessment Questions

### ISSUE THREAD

**Issue by voleka-ocrv** [Ebazhanov/linkedin-skill-assessments-quizzes#2903]
Hi! There are six new question I faced in Power BI skill assessment.
### Q1. A group admin for an app workspace cannot _______ in their workspace.
- [ ] remove users from the group
- [ ] manage group membership
- [ ] add users to the group
- [x] remove users from Power BI

### Q2. In general, you should not add DAX calculated columns to your data moder if you are able to do what?
- [x] all of these answers
- [ ] Create the columns in Power Query during data load
- [ ] Create a measure instead
- [ ] Have it added to the data source

### Q3. In the Power BI service, accessing a dataset for an uploaded Power BI file allows you what capabilities?
- [ ] the ability to see all of the dataset only in Power BI cloud services, but not in Power BI Desktop
- [x] front-end access to all data queries within this source without the ability to make back-end changes
- [ ] connections to all the data queries and the ability to make ETL modifications to existing data
- [ ] the option to select a single query from within the dataset and build new ETL processes form it

### Q4. What is the recommended level of security for data extensions?
- [ ] Prompt the user before load
- [ ] Allow any extension to load without warning
- [x] Allow only certified extensions to load
- [ ] Load certified extensions and prompt the user for noncertified extensions

### Q5. Your data model includes a Members data table and ten other tables, including these the lookup tables with unique IDs: City, State, and Country. How can you improve your data model for Power BI?
A. Combine City, State, and Country into one lookup table
B. Move City, State, and Country to the Member table
C. Combine City and State into one lookup table and remove the Country table
D. Leave the model as it is.
- [ ] A or C
- [x] A
- [ ] D
- [ ] A or B

### Q6. Before you can use a custom visualization from the Power BI Marketplace, you need to ________ in, then ______ it to your Power BI account.
- [ ] download; upload
- [x] purchase; import
- [ ] purchase; upload
- [ ] upload; download

**Comment by Ebazhanov** [comment]
Thank you @voleka-ocrv for new questions I have added them https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/master/microsoft-power-bi/microsoft-power-bi-quiz.md
