### ISSUE TITLE
OOP New Questions

### ISSUE THREAD

**Issue by gmbarrera** [Ebazhanov/linkedin-skill-assessments-quizzes#2904]
![imagen](https://user-images.githubusercontent.com/2257451/148303465-748ee278-c536-4ffd-8d0d-032c78d21da5.png)
![imagen](https://user-images.githubusercontent.com/2257451/148303473-dc938c86-cc50-421d-b46b-616640712fd2.png)
![imagen](https://user-images.githubusercontent.com/2257451/148303483-68141503-4af6-4c7b-8cb8-3c42270e6c83.png)
![imagen](https://user-images.githubusercontent.com/2257451/148303500-1847c479-2e58-4c51-9113-b8a3aa2d1d55.png)
![imagen](https://user-images.githubusercontent.com/2257451/148303510-64e4dd78-8626-4268-ba1b-ff2b8812331e.png)

**Comment by Ebazhanov** [comment]
Thank you @gmbarrera, everything were added by @lnugraha! 👍
