### ISSUE TITLE
React

### ISSUE THREAD

**Issue by gudata** [Ebazhanov/linkedin-skill-assessments-quizzes#2914]
Here is one question but I am not sure for the answer.

What value of button will allow you to pass the name of the person to be hugged?

```
class Huggable extends React.Component {
  hug(id) {
    console.log("hugging " + id);
  }
  render() {
    let name = "kitteh";
    let button = // Missing code
    return button;
  }
}
```

- [x] <button onClick={(name) => this.hub(name)}>Hug Button</button>
- [ ] <button onClick={this.hug(e, name)}>Hug Button</button>
- [ ] <button onClick={(e) => this.hug(name, e)}>Hug Button</button>
- [ ] <button onClick={(e) => this.hug(name, e)}>Hug Button</button>

**Comment by Ebazhanov** [comment]
Thank you @gudata, @lnugraha! 👍
