### ISSUE TITLE
Microsoft Outlook - New Assessment Questions / Answer changes

### ISSUE THREAD

**Issue by QuestionableGuise** [Ebazhanov/linkedin-skill-assessments-quizzes#2923]
Answer Wording Changes

Q23. You created a meeting for next Friday at 1 p.m., and several invitees have accepted. How do you change only your version of the meeting to 12 p.m. to allow yourself time to set up?

- [  ] Open the calendar in Day, Week, or Work Week view and drag the start time to 12 p.m.
- [  ] Double-click the meeting to open its form, change the start time, and close the form.
- [ x ] You cannot-instead, create a separate appointment for yourself from 12 p.m. to 1 p.m.
- [  ] Double-click the meeting to open its form, change the reminder to 1 hour, and click Save.

-----
-----

New Questions

You have been tasked with inviting 75 people to an event. You do not need to track whether or not they intend to attend. To save time, what should you do?

- [  ] Add all recipients to the Bcc Field.
- [  ] Turn off Request Responses under Response Options.
- [  ] Use mail merge to send the invitations.
- [  ] Add "NRR (no response required)" to the subject line

What would be the best way to have emails sent directly to you in your Inbox, but hide emails for later review when you are in the Cc line?

- [ x ] Create a Ccd folder, and then create a rule to move all messages where you are on the Cc line to that folder.
- [  ] Create a rule to move all messages where you are in the Cc line to the Deleted items folder.
- [  ] Turn on Focused Inbox.
- [  ] Create a rule to apply conditional formatting to all messages where you are in the Cc line.

-----
-----

Answer

Q45. Right-click a message that was incorrectly organized and select Always Move to Focused

Q48. as a search folder (Smart Folder on Mac)
NOTE: New answer wording is: as a search folder(Windows) or Smart Folder (Mac)

Q56. Right-click the email and select Find Related > Messages from sender.

-----
-----

Typos

Q49. When you compose and email... > When you compose an email...

**Comment by Ebazhanov** [comment]
Thank you @QuestionableGuise for the new questions and correction, updated https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/master/microsoft-outlook/microsoft-outlook-quiz.md
