### ISSUE TITLE
Typo for git question 22?

### ISSUE THREAD

**Issue by jdhao** [Ebazhanov/linkedin-skill-assessments-quizzes#2926]
The correct commands should be `git show refs/heads/push-notifications`. Note `heads` not `head`.

Link to question: https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/master/git/git-quiz.md#q22-you-find-that-your-project-has-a-tag-and-branch-both-named-push-notifications-which-causes-confusion-when-trying-to-print-out-given-reference-how-can-you-specify-which-branch-you-want-to-look-at

**Comment by Ebazhanov** [comment]
Thank you @jdhao, good catch 👍  i have updated!
