### ISSUE TITLE
nodejs missing questions

### ISSUE THREAD

**Issue by gudata** [Ebazhanov/linkedin-skill-assessments-quizzes#2935]
![2022-01-14-19:11:18_1920x1080](https://user-images.githubusercontent.com/25951/149556736-627f86cf-01d4-419d-b879-e995beaf7acc.png)
![2022-01-14-19:06:25_1920x1080](https://user-images.githubusercontent.com/25951/149556748-1f8cee2d-d071-4d77-95a6-3742633a7ab2.png)

**Comment by Ebazhanov** [comment]
Thanks you @gudata once again for this issue with screenshots, the questions have been added https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/master/node.js/node.js-quiz.md
