### ISSUE TITLE
Unknown Question in Front-End Development 

### ISSUE THREAD

**Issue by Meow-Meow-Overlord** [Ebazhanov/linkedin-skill-assessments-quizzes#2940]
![Untitled](https://user-images.githubusercontent.com/97819790/149647859-78bfff58-a3ac-4cee-9c5a-3d7858860b28.png)
The answer is code that provides modern functionality to browsers that don't support it. 
Source: https://developer.mozilla.org/en-US/docs/Glossary/Polyfill

Should I make a pull request for this? This is my first time using Git and I don't know the rule of interaction yet.

**Comment by Ebazhanov** [comment]
> ![Untitled](https://user-images.githubusercontent.com/97819790/149647859-78bfff58-a3ac-4cee-9c5a-3d7858860b28.png) The answer is code that provides modern functionality to browsers that don't support it. Source: https://developer.mozilla.org/en-US/docs/Glossary/Polyfill
> 
> Should I make a pull request for this? This is my first time using Git and I don't know the rule of interaction yet.

Hello, @Meow-Meow-Overlord! Sorry for later reply, yes any PR are welcome, they should not be perfect with content )))
can you please review PR https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/pull/2971
thank you in advance!
