### ISSUE TITLE
Q64. What is not a java keyword

### ISSUE THREAD

**Issue by onurakan** [Ebazhanov/linkedin-skill-assessments-quizzes#2950]
In the following question. "What" should be changed with "which"

Q64. **What** is not a java keyword

https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/master/java/java-quiz.md

**Comment by Ebazhanov** [comment]
Hello, @onurakan! fyi based on your issue, @masoudk1990 already have created PR https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/pull/2972

Can you please review it, thank you in advance!

**Comment by onurakan** [comment]
> Hello, @onurakan! fyi based on your issue, @masoudk1990 already have created PR https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/pull/2972
> 
> 
> 
> Can you please review it, thank you in advance! 

Thanks. Great Job

**Comment by masoudk1990** [comment]
@onurakan Thank you for reviewing it.
@Ebazhanov  Although this issue is in Closed state but I can't find the changes that I've made in Master branch.

**Comment by Ebazhanov** [comment]
> @onurakan Thank you for reviewing it. @Ebazhanov Although this issue is in Closed state, I can't find the changes that I've made in Master branch.

fyi, creator of this issue can close his issue in anytime and merge actions is not sync with closing an issue! 
I was away from my desc going to merge related PR now, thank you guys @onurakan, @masoudk1990
