### ISSUE TITLE
Multiple questions are missing from multiple quizzes - how can we extract them?

### ISSUE THREAD

**Issue by Ravelair** [Ebazhanov/linkedin-skill-assessments-quizzes#2951]
Is it at all possible? Or do we have to just know the correct answer and then make a pull request?

**Comment by Ebazhanov** [comment]
Hello, @Ravelair
thanks for the question, you can create PR
- without answer
- with correct answer (without reference)
- with correct answer (with reference)

we also can ask for support from people who is more experience
feel free to open PR for futher discussion 👍
