### ISSUE TITLE
OOP add missing question: Q: What parameters are required to be passed to a class constructor?

### ISSUE THREAD

**Issue by xavio86** [Ebazhanov/linkedin-skill-assessments-quizzes#2960]
Hi,
Just encountered a question that is missing in the docs:

**What parameters are required to be passed to a class constructor?**

![2022-01-20_15-07](https://user-images.githubusercontent.com/20542175/150356335-32ebfac5-52f4-4efc-8df7-a942afa7d277.png)

I answered **none** as other options didn't seem right to me.
I would only pass a service or parameter if its required by dependency injection configuration. Calling a parent is also not necessary.

**Comment by Jay206-Programmer** [comment]
It's now addressed in PR #2968.

**Comment by Ebazhanov** [comment]
@xavio86 fyi your issue have been resolved, thanks a lot for raising 👍
