### ISSUE TITLE
New Bash question: Wich operator sends the output of ls to a file for later use?

### ISSUE THREAD

**Issue by alopezme** [Ebazhanov/linkedin-skill-assessments-quizzes#2961]
- ls < filelist.txt
- ls ¦ filelist.txt
- ls > filelist.txt (Correct one)
- ls - filelist.txt

**Comment by Ebazhanov** [comment]
Hello, @alopezme can you please review this PR https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/pull/2976

Thank you in advance!

**Comment by alopezme** [comment]
Hello, I agree with the changes
