### ISSUE TITLE
cybersecurity new questions

### ISSUE THREAD

**Issue by JawadPy** [Ebazhanov/linkedin-skill-assessments-quizzes#2985]
found those new questions on cybersecurity quiz:

#### How many keys would be necessary to accommodate 100 users in an asymmetric cryptography system?
- [ ] 400
- [ ] 300
- [ ] 100
- [ ] 200

#### What is the difference between DevOps and DevSecOps?
- [ ] 
- [ ] 
- [ ] 
- [ ] 

#### Which compliance framework governs requirements for the U.S. healthcare industry?
- [ ] 
- [ ] 
- [ ] 
- [ ] 

#### When does static application security testing require access to source code?
- [ ] 
- [ ] 
- [ ] 
- [ ] 

#### Your organization services customer orders with a custom ordering system developed in-house. You are responsible for recommending a cloud model to meet the following requirements:
 
 - Control of security required for regulatory compliance
 - Legacy application and database support
 - Scalability to meet seasonal increases in demand
 
 Which cloud model is the best option for these requirements?
- [ ] 
- [ ] 
- [ ] 
- [ ] 

####  You have just conducted a port scan of a network. There is no well-known port active. How do you find a webserver running on a host, which uses a random port number?
- [ ] 
- [ ] 
- [ ] 
- [ ] 

####  You need to disable the camera on corporate devices to prevent screen capture and recording of sensitive documents, meetings, and conversations. Which solution would be best suited to the task?
- [ ] 
- [ ] 
- [ ] 
- [ ] 

options for those question will be attached, sorry if this is painful but also there's no time to copy them from Inspect...
don't cheat just use it to get some knowledge guys *wink* 

![Screenshot 2022-01-27 054926](https://user-images.githubusercontent.com/98477272/151285606-d6f73582-ae06-413e-b857-cd3d13516bfc.png)

![Screenshot 2022-01-27 054802](https://user-images.githubusercontent.com/98477272/151285578-923ecce0-37c3-4a7e-a1a9-13f9aa330fe7.png)

![Screenshot 2022-01-27 055101](https://user-images.githubusercontent.com/98477272/151285642-68ccc502-ada2-4a1e-842d-16e60857fa2c.png)

![Screenshot 2022-01-27 055211](https://user-images.githubusercontent.com/98477272/151285650-eb20913a-18b7-483d-91ff-753d6d59441c.png)

![Screenshot 2022-01-27 055332](https://user-images.githubusercontent.com/98477272/151285661-49b45313-8ba0-4432-b3af-262bd3236411.png)

**Comment by Ebazhanov** [comment]
@JawadPy thanks a lot for the screenshot 💪 , all the questions have been added.
