### ISSUE TITLE
No answers in Autodesk Fusion 360

### ISSUE THREAD

**Issue by ankurshkl877** [Ebazhanov/linkedin-skill-assessments-quizzes#2994]
Q4. In simulation, which constraint prevents movement in a specific direction?

- [ ]  frictionless
- [ ]  prescribed displacement
- [ ]  pin
- [ ]  fixed

Q5. In the CAM workspace, which strategy removes a part's interior cavity?
 

- [ ] Slot
- [ ]  2D Pocket
- [ ]  Bore
- [ ]  2D Contour

Q6. What does the Zebra Analysis tool do?
 

- [ ] It applies a metal render.
- [ ]  It fixes bodies.
- [ ]  It checks a body's continuity.
- [ ]  It splits bodies apart.

Q7. Which command creates a plane at the midpoint between two faces or work planes?
 

- [ ] Midplane
- [ ]  Plane Tangent to Face at Point
- [ ]  Offset Plane
- [ ]  Plane at Angle

Q8. Which hole type automatically enters a diameter value based on the type of fastener it will accomodate?
 

- [ ] Clearance
- [ ]  Simple
- [ ]  Drilled
- [ ]  Through

Q9. Which workspace creates components made from thin, premade material formed into specific shapes?

- [ ]  Mesh
- [ ]  Simulation
- [ ]  Animation
- [ ]  Sheet Metal

Q10. What is required to invite other people into your project folder?
 

- [ ] a name
- [ ]  an email address
- [ ]  an IP address
- [ ]  a phone number

Q11. Which tool connects two joints in a way that the motion of one joint can drive the motion of another joint?
 

- [ ] Drive Joints
- [ ]  As-built Joint
- [ ]  Motion Study
- [ ]  Motion Link

Q12. Which joint type allows components to translate along two axes and rotate around a single axis?
 

- [ ] slider
- [ ]  revolute
- [ ]  planar
- [ ]  pin-slot

Q13. Which view shows a drawing part at an enlarged scale?

- [ ]  detail view
- [ ]  section view
- [ ]  base view
- [ ]  projected view

Q14. Which file type is not a drawing output?
 

- [ ] DWG file
- [ ]  CSV file
- [ ]  STEP file
- [ ]  PDF file

Q15. What command do you use to understand the relationship between multiple joints?

- [ ]  Lock
- [ ]  Animate Joint
- [ ]  Animate Model
- [ ]  Motion Link

Q16. What translator converts the screen toolpath into language the CNC machine understands?

- [ ]  a post processor
- [ ]  G-code
- [ ]  NC-code
- [ ]  a code

**Comment by Ebazhanov** [comment]
That's fine, we have many other not answered questions, I would prefer to close this issue!
