### ISSUE TITLE
Missing HTML Question ASCII

### ISSUE THREAD

**Issue by Lagicrus** [Ebazhanov/linkedin-skill-assessments-quizzes#3034]
*HTML Skill Assessment:*

Q: How would you mark up a piece of ASCII art (an emotion) in an accessible way?

- [ ] `<pre role="emotion" aria-label="ASCII emotion of a shrug">¯\_(ツ)_/¯</pre>`
- [ ] `<pre role="img" aria-label="ASCII emotion of a shrug">¯\_(ツ)_/¯</pre>`
- [ ] `<dfn title="ASCII emotion of a shrug">¯\_(ツ)_/¯</dfn>`
- [ ] `<label for="art">ASCII emotion of a shrug</label><pre role="img" id="art">¯\_(ツ)_/¯</pre>`

![image](https://user-images.githubusercontent.com/24227350/151802629-1f159a14-cfb6-465b-b45e-11042790c065.png)

**Comment by samr1ddh1** [comment]
Hey There I would love to work on this.
