### ISSUE TITLE
HTML Missing Question metadata

### ISSUE THREAD

**Issue by Lagicrus** [Ebazhanov/linkedin-skill-assessments-quizzes#3035]
Q: "Which example is a standard way in HTML5 for adding author metadata to a page?"

- [ ] `<metadata name="author" content="Author Name">`
- [ ] `<meta name="author">Author Name</meta>`
- [ ] `<meta name="creator" content="Author Name">`
- [ ] `<meta name="author" content="Author Name">`
![image](https://user-images.githubusercontent.com/24227350/151803194-7248a937-7db8-40f2-8188-461a19e53d08.png)

**Comment by samr1ddh1** [comment]
Hey there ! I will work on this.

**Comment by Ebazhanov** [comment]
Thank you guys for your effort, closed!
