### ISSUE TITLE
HTML Missing Questions <head>

### ISSUE THREAD

**Issue by Lagicrus** [Ebazhanov/linkedin-skill-assessments-quizzes#3036]
Q: "Which choice is valid markup for a <head> element?

- [ ] `<head class="Page Section Information" id="head"><title>Page Title</title></head>`
- [ ] `<head><title>Page Title</title><img src="favicon.ico" alt=""></head>`
- [ ] `<head><title>Page Title</title><address>email@example.com</address></head>`
- [ ] `<head><title>Page Title</title><data value="email">email@example.com</data></head>`
![image](https://user-images.githubusercontent.com/24227350/151804295-7231f90d-4de9-4208-8411-37cc2a5eed51.png)

**Comment by Ebazhanov** [comment]
@Lagicrus thank you for creating this issue, done 👍 
https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/master/html/html-quiz.md#q102-which-choice-is-valid-markup-for-a-head-element
