### ISSUE TITLE
Node - Question #34 - No valid answer.

### ISSUE THREAD

**Issue by 3therios** [Ebazhanov/linkedin-skill-assessments-quizzes#3039]
Using the Vercel test quiz app, under the Node category, there is no valid answer for question # 34.
I'm unsure if the questions are always in the same order, but below is a screenshot after submitting an answer.

![Screen Shot 2022-02-01 at 10 26 13 am](https://user-images.githubusercontent.com/7747232/151889865-aea13e6e-43bd-41cc-b61b-61eec778850d.png)

**Comment by Ebazhanov** [comment]
Thanks you @3therios for submitting the problem, good catch 👍 
i have moved this directly to to App dashboard fyi https://github.com/linkedin-faq/quizzes-practice-app/issues/5
