### ISSUE TITLE
Python repeated questions

### ISSUE THREAD

**Issue by rjsilvestre** [Ebazhanov/linkedin-skill-assessments-quizzes#3063]
Question 102 is repeated on question 110.
Question 103 is repeated on question 111.

Also, I am not sure if the question 102/110 answer is correct:
#### Q102. Which mode is not a valid way to access a file from within a Python script?

- [ ] write('w')
- [ ] scan('s')
- [x] append('a')
- [ ] read('r')

Append is a valid mode: [https://docs.python.org/3/library/functions.html#open](url).

**Comment by Ebazhanov** [comment]
thank you @rjsilvestre I have added your question 👍
