### ISSUE TITLE
Linux missing question 

### ISSUE THREAD

**Issue by molinto** [Ebazhanov/linkedin-skill-assessments-quizzes#3066]
![Screenshot from 2022-02-04 16-17-32](https://user-images.githubusercontent.com/279285/152564900-0adff693-b1fa-479d-b59a-3c2be305efaa.png)

**Comment by Ebazhanov** [comment]
Thank you @molinto done 👍

**Comment by Ebazhanov** [comment]
done 👍 , thank you @molinto
