### ISSUE TITLE
Incorrect answer for Golang

### ISSUE THREAD

**Issue by Maracko** [Ebazhanov/linkedin-skill-assessments-quizzes#3074]
Inside the golang assessment quiz, I think you provided a wrong answer for question 39.

https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/master/go/go-quiz.md

![image](https://user-images.githubusercontent.com/56165587/152654343-9d58bbcd-f2bc-4c81-8b82-ef87e0b99730.png)

The idiomatic way to organize binaries is inside the `cmd` folder. `pkg` should be used for libraries and such without binaries

**Comment by Maracko** [comment]
I would correct it myself but didn't get that question inside my quiz so am not sure if LinkedIn considers it correct. If they do, an issue should be raised with them first.

**Comment by Ebazhanov** [comment]
@ruslanbes, @Imolai can you guys take a look? thanks

**Comment by Imolai** [comment]
> @ruslanbes, @monkrus, @Imolai can you guys take a look please? thanks

@Ebazhanov sure

**Comment by Imolai** [comment]
@Ebazhanov yes, @Maracko is right. The common way to have several executables in your project to have a `cmd` directory and a directory per executable inside it.

See:

- <https://stackoverflow.com/questions/9985559/organizing-a-multiple-file-go-project/51942843#51942843>
- <https://medium.com/@benbjohnson/structuring-applications-in-go-3b04be4ff091>
- <https://medium.com/golang-learn/go-project-layout-e5213cdcfaa2>

**Comment by Ebazhanov** [comment]
thanks a lot @Imolai, very detailed feedback 💪  it is enough!

**Comment by Maracko** [comment]
Created a PR with corrected answer 🙂
