### ISSUE TITLE
No options on 5th question in JavaScript module

### ISSUE THREAD

**Issue by Anuragchindaliya** [Ebazhanov/linkedin-skill-assessments-quizzes#3078]
![image](https://user-images.githubusercontent.com/61020079/152692718-1e102061-3710-409a-b61a-ee37ecd70663.png)

**Comment by Ebazhanov** [comment]
@nhemnt can you please take look, maybe you can fix it? thank you in advance!

**Comment by Ebazhanov** [comment]
@Anuragchindaliya your issue should be solved now, thank you @nhemnt for quick fix!
