### ISSUE TITLE
objective-c missing questions

### ISSUE THREAD

**Issue by 3xception** [Ebazhanov/linkedin-skill-assessments-quizzes#3106]
<img width="1206" alt="Screen Shot 2022-02-11 at 11 53 19 PM" src="https://user-images.githubusercontent.com/65983963/153697319-25217ec8-dae7-4019-ba3d-70d3758f7a20.png">

<img width="1231" alt="Screen Shot 2022-02-11 at 11 51 18 PM" src="https://user-images.githubusercontent.com/65983963/153697325-62f77e9d-8f81-4a14-9a36-cb60df2ecb48.png">

**Comment by Ebazhanov** [comment]
@3xception thank you for screenshot, added https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/master/objective-c/objective-c-quiz.md
