### ISSUE TITLE
mysql new question

### ISSUE THREAD

**Issue by cazacubogdan** [Ebazhanov/linkedin-skill-assessments-quizzes#3116]
[
![m1](https://user-images.githubusercontent.com/3471768/153768076-82c1cf79-9464-491b-83d1-312d9fa977c0.JPG)
](url)

a new question came up today... unfortunately i do not have the time at this point to add it myself, but someone else maybe it has the time...

**Comment by Ebazhanov** [comment]
already in codebase https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/master/mysql/mysql-quiz.md
