### ISSUE TITLE
Python 2 new Questions

### ISSUE THREAD

**Issue by maheshdbabar9340** [Ebazhanov/linkedin-skill-assessments-quizzes#3135]
Question 1. 
![Screenshot (2125)](https://user-images.githubusercontent.com/53929423/154434548-b756acae-d7de-4647-9a4c-d3bce2640386.png)

Correct Ans is Option 1. => because of level of indentation after the for loop. 

Question 2. 
![Screenshot (2124)](https://user-images.githubusercontent.com/53929423/154434805-5eaa3782-ab3e-49e4-b5ed-f0d3e7f5b63a.png)

**Comment by Ebazhanov** [comment]
added to codebase, thanks
