### ISSUE TITLE
Some missing jquery questions

### ISSUE THREAD

**Issue by fusionneur** [Ebazhanov/linkedin-skill-assessments-quizzes#3169]
![7](https://user-images.githubusercontent.com/7840350/155012851-5f5ecbdc-dc5e-40ac-b46d-9acc3da4ab9d.PNG)
![2](https://user-images.githubusercontent.com/7840350/155012855-770ae7c2-b182-4fc7-b484-7447a52b3a49.PNG)
![3](https://user-images.githubusercontent.com/7840350/155012856-c522650b-335f-4a32-9095-5a4366dd096f.PNG)
![4](https://user-images.githubusercontent.com/7840350/155012858-04a6ff68-372c-407a-9abd-baa4c523c4b2.PNG)
![5](https://user-images.githubusercontent.com/7840350/155012859-0965a9bb-8b85-41f6-975c-6fff6eebcf6b.PNG)
![6](https://user-images.githubusercontent.com/7840350/155012861-7d55891a-a838-4fc7-8e97-29b1edfb9d0c.PNG)

**Comment by Ebazhanov** [comment]
all question already in the repo, thank you @fusionneur
