### ISSUE TITLE
Missing Windows Server Questions

### ISSUE THREAD

**Issue by fusionneur** [Ebazhanov/linkedin-skill-assessments-quizzes#3172]
![4](https://user-images.githubusercontent.com/7840350/155027800-9231ce24-1cee-488c-a03b-6c06415957fd.PNG)
![1](https://user-images.githubusercontent.com/7840350/155027805-c05a61b1-f2cc-4254-8447-efacbc0e421f.PNG)
![2](https://user-images.githubusercontent.com/7840350/155027807-27925de9-584c-4721-bf54-7de6efa9f15b.PNG)
![3](https://user-images.githubusercontent.com/7840350/155027809-6a61d64b-866d-408d-bbda-b5376c0a1a45.PNG)

**Comment by Ebazhanov** [comment]
Thanks @fusionneur 👍 , all questions have been added!
