### ISSUE TITLE
Missing Windows Server questions

### ISSUE THREAD

**Issue by 3xception** [Ebazhanov/linkedin-skill-assessments-quizzes#3181]
<img width="1173" alt="Screen Shot 2022-02-23 at 1 20 34 AM" src="https://user-images.githubusercontent.com/65983963/155271067-c345f89a-adad-4515-82c3-32d2b4e5ad76.png">
<img width="1189" alt="Screen Shot 2022-02-23 at 1 17 07 AM" src="https://user-images.githubusercontent.com/65983963/155271069-41d36a77-ac45-4304-b4d6-e0780d171c66.png">

**Comment by Ebazhanov** [comment]
Thank you @3xception 🌹 , question added
