### ISSUE TITLE
Git new questions

### ISSUE THREAD

**Issue by pauladanielafarias** [Ebazhanov/linkedin-skill-assessments-quizzes#3191]
![Captura de Pantalla 2022-02-24 a la(s) 21 08 16](https://user-images.githubusercontent.com/47432769/155866336-63a151f9-7b3c-4558-bee6-425826fa9b6d.png)

**Q: _What is the staging area or index?_**
- an area that stores commits prior to them being pushed to the remote repository
- an area containing stash entries that can applied to the working files
- an area where changes from a branch in the remote repository are stored before they are applied to a local branch
- [x] **an area that stores information about changes that will be included in the next commit**

---

![Captura de Pantalla 2022-02-24 a la(s) 21 06 34](https://user-images.githubusercontent.com/47432769/155866403-b928052b-6d82-4ffe-ace7-7a52ac5ed3ba.png)

**Q: _What features do repository managers such as GitHub provide beyond Git?_**
- [x] **Repository managers provide an online service for hosting Git repositories that include collaboration features such as pull requests, issue tracking, and peer reviews.**
- Repository managers provide an enhanced command-line tool that is used to manage multiple local repositories.
- Repository managers are proprietary versions of Git that do not include enhanced features.
- Repository managers distribute repositories across multiple locations on a user's workstation, providing redundant storage that allows for quick backup and recovery.

---

![Captura de Pantalla 2022-02-24 a la(s) 21 05 08](https://user-images.githubusercontent.com/47432769/155866513-b9d06d9a-0196-4890-bd7a-19dcccb47418.png)

**Q: _What command would you use to stage changes to the index strictly for properties files in the current directory?_**
- [x] __git add *.properties__
- git add %.properties
- git add .properties
- git add properties

---

![Captura de Pantalla 2022-02-24 a la(s) 21 03 25](https://user-images.githubusercontent.com/47432769/155866587-51769f8e-249b-4836-b17d-7395009934ba.png)

**Q: _What are untracked files?_**
- files in the local repository that have not been merged into the master branch
- staged files that Git does not know about because the have not been committed
- [x] **files in the working directory that Git does not know about because the have not been staged or committed**
- files in the remote repository that Git does not know about because they have not been tagged

---

![Captura de Pantalla 2022-02-24 a la(s) 21 02 02](https://user-images.githubusercontent.com/47432769/155866713-26e5de9c-2d48-47ac-8dca-69c231313082.png)

**Q: _What command takes changes from the master branch on the remote repository origin and merges them to the local checked-out branch?_**
- git checkout origin
- git commit -u origin
- [x] **git pull origin master**
- git push origin master

---

![Captura de Pantalla 2022-02-24 a la(s) 21 00 39](https://user-images.githubusercontent.com/47432769/155866924-9a9137f4-6f80-428a-9a70-f9844bf1b3eb.png)

**Q: _What type of Git hook could be used to validate that a commit message contains a ticket number?_**
- pre-commit
- [x] **commit-msg**
- applypatch-msg
- prepare-commit-msg

---

![Captura de Pantalla 2022-02-24 a la(s) 20 59 29](https://user-images.githubusercontent.com/47432769/155867047-9193db79-a3ef-48c5-935a-bf0debfd0ebd.png)

**Q: _What is the difference between `git stash pop` and `git stash apply`?_**
- `git stash pop` pushes the topmost commit to the current branch, while `git stash apply` caches the last commit in the current branch.
- [x] **`git stash pop` applies the topmost entry in the stash to the working files and removes it from the stash, while `git stash apply` applies the topmost entry in the stash to the working files but leaves it in the stash.**
- `git stash pop` merges the topmost commit to the current branch, while `git stash apply` merges the last commit in the current branch.
- `git stash pop` applies the topmost entry in the stash to the working files but leaves it in the stash, while `git stash apply` applies the topmost entry in the stash to the working files and removes it from the stash.

---

![Captura de Pantalla 2022-02-24 a la(s) 20 57 27](https://user-images.githubusercontent.com/47432769/155867223-240b2d13-eeee-4307-a8db-c6cb2b3b39d9.png)

**Q: _Describe what these Git commands do to the commit history:_**
```
git reset --hard HEAD~5
git merge --squash HEAD@{1}
```

- They merge the last five commits into a new branch.
- [x] **The current branch's HEAD is reset back five commits, then prior commits are squashed into a single commit.**
- They delete the last five commits.
- They reset the HEAD to the fifth commit in the repo, then merge to the master branch.

---

![Captura de Pantalla 2022-02-24 a la(s) 20 55 32](https://user-images.githubusercontent.com/47432769/155867337-88f8b5f8-dd3c-4146-8e37-5eac7a0ccc90.png)

**Q: _After making some major changes to your code, you are a little nervous about committing. What command would you use to review the commit prior to making it?_**
- git commit --verify
- git notes show
- git commit preview
- [x] **git commit --dry-run**

---

**Comment by eikowagenknecht** [comment]
Here's another one:

![image](https://user-images.githubusercontent.com/1475672/160094128-4b7281e7-8648-46c2-9c94-3f989b1102ca.png)

**Comment by Ebazhanov** [comment]
Thanks a lot @pauladanielafarias for screens and your typing, great job 🌹 
Thank you @eikowagenknecht for your questions too. 👍 
all questions were successfully added
