### ISSUE TITLE
New HTML Assessment Question

### ISSUE THREAD

**Issue by VictorHeDev** [Ebazhanov/linkedin-skill-assessments-quizzes#3211]
Hello all, I took the LinkedIn HTML assessment today and received this question:

A designer gave you CSS code that should only run when the device rendering the page is in dark mode. How would you embed that code?

a. <style media="light-mode: false">/* CSS code */</style>
b. <style media="color-scheme: dark">/* CSS code */</style>
c. <style media="color-mode: dark">/* CSS code */</style>
d. <style media="prefers-color-scheme: darks">/* CSS code */</style>

Please let me know what you think! 

https://css-tricks.com/dark-modes-with-css/

**Comment by Trishadring** [comment]
question added with 
https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/pull/3219

**Comment by Ebazhanov** [comment]
Thank you @VictorHeDev, @Trishadring great job guys! 💪
