### ISSUE TITLE
New Google Ads Questions

### ISSUE THREAD

**Issue by VictorHeDev** [Ebazhanov/linkedin-skill-assessments-quizzes#3212]
Here are some new questions for the Google Ads quiz:

Maurice creates an ad heading that reads "Buy {Keyword:hats} Today". Which headline could not be displayed to a user for this ad?
a. Buy Caps Today
b. Buy Helmets Today
c. Buy Hats
d. Buy Fedoras Today

Why are aad extensions beneficial?
a. They increase the character count for descriptions and headlines
b. They expand the ad and tend to increase the clickthrough rate
c. They allow you to integrate your data with third-party platforms such as Google Analytics
c. They reduce the overall cost of your campaigns 

How do you calculate Clickthrough rate (CTR)?
https://support.google.com/google-ads/answer/2615875?hl=en

In a text ad, the display URL is made up of the domain from your final URL and up to two _______.
a. descriptions
b. paths
c. keywords
d. tracking tags

Within the Display Network, locations where your ad can appear are referred to as _______.
a. ad slots
b. placements
c. landing pages
d. displays

Which setting lets you monitor how certain criteria perform with your ads without limiting reach?
a. remarketing
b. conversion value
c. targeting
d. observation

Tory manages marketing for a hotel franchise with a thousand locations worldwide. Each hotel location has its own landing page. If Tory wanted to quickly generate search ads for every location, which ad type would be most beneficial?
a. Dynamic Search Ads
b. Responsive Search Ads
c. Universal Search Ads
c. Programmatic Search Ads

Which keyword is of the "phrase match" type?
a. [discount flight deals]
b. discount+flight+deals
c. "discount flight deals"
d. discount flight deals

Janice operates a brand-new dry cleaning business, with five locations throughout Ireland. What would be a good way to organize a campaign announcing the grand opening?
a. one campaign with an ad group for each location
b. one ad group containing all locations
c. one ad group for each service
d. one campaign for each location

Which factor does Google Ads consider when determining whether a remarketing list qualifies for a similar audiences list?
a. the average bid targeting the list
b. the average monthly spend targeting the list
c. the amount of revenue generated by the list
d. the number of visitors on the list

What is ad frequency?
a. the total number of impressions your advertisement receives
b. the total number of users who clicked on your advertisement
c. the number of times a single user will see your advertisement
d. the number of visitors who completed the checkout process

Which metric does not help in understanding your ROI?
a. production costs
b. frequency
c. revenue
d. cost per conversion 

Which choice represents the hierarchy of search campaigns in Google Ads?
a. ads > keywords > campaign
b. campaign > ad group > ads
c. keywords > campaign > ads
d. ad group > campaign > ads

If you continuously search for your own advertisement using Google, just to confirm that it appears, it is very likely that you will inflate your _____ and decrease your _____.
a. impressions; clickthrough rate
b. conversions; ROI
c. clickthrough rate; impressions
d. ROI; conversions

**Comment by Ebazhanov** [comment]
Thank you @VictorHeDev 👍 , all questions were added
