### ISSUE TITLE
Incorrect answer in Agile Methodologies Q73

### ISSUE THREAD

**Issue by kintz09** [Ebazhanov/linkedin-skill-assessments-quizzes#3215]
The question currently reads: 

>Q73. Which is NOT a principle of the Scaled Agile Framework?
>
> - Centralize decision-making
> - Apply systems thinking
> - Take an economic view
> - Unlock the intrinsic motivation of knowledge workers (correct)

When I answered this question, using the md2practice page, I was told the correct answer was D `Unlock the intrinsic motivation of knowledge workers`.

I looked up the 10 principles online and found them listed by [SAFe](https://www.scaledagileframework.com/safe-lean-agile-principles/) and [Wikipedia](https://en.wikipedia.org/wiki/Scaled_agile_framework).

Answer options B, C, and D are listed as principles at both links verbatim and therefore are principles of the Scaled Agile Framework. Answer option A should be the correct answer to this question. The actual principle option A is referencing is `Decentralize decision-making`. 

From what I'm seeing here, it looks like the correct answer simply needs to be changed to option A `Centralize decision-making`.

BTW - this resources is amazing! Thanks to all who put this together and maintain it.

**Comment by Ebazhanov** [comment]
Thanks @kintz09 good catch and thank you for investigation! If you want to create PR with your correction and adding explanation feel free!
