### ISSUE TITLE
New Microsoft Excel Questions!

### ISSUE THREAD

**Issue by natitivi** [Ebazhanov/linkedin-skill-assessments-quizzes#3217]
Two new questions:

A colleague shared an Excel file with you, and you want to display a worksheet that is hidden in it. How can you do that?
- Right-click any worksheet tab and select Unhide.
- On the View tab, click New Window.
- On the Home tab, click Unhide.
- On the Review tab click Unhide Sheet.

How do you remove only the conditional formatting from a cell and leave all other formatting intact?
- This is not possible-you can remove only all formatting from a cell.
- Select the cell. On the Home tab, click Conditional Formatting > Clear Rules > Clear Rules from Selected Cells.
- Right-click the cell and select Delete Conditional Formatting.
- Right-click the cell and select Remove Conditional Formatting.

**Comment by Trishadring** [comment]
issue can be closed. answers added my Marcodercin

**Comment by Ebazhanov** [comment]
Thank you @Trishadring, @natitivi 👍
