### ISSUE TITLE
Incorrect answers and duplicate questions in React

### ISSUE THREAD

**Issue by Knightwalker** [Ebazhanov/linkedin-skill-assessments-quizzes#3226]
Topic: React.js
Link - https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/master/react/reactjs-quiz.md

- Q99 is wrong and is duplicate of Q27. For Q99 i'm pretty sure that `webpack loaders are used to preprocess and transform files`. This is correctly answered in Q27.
- Q100 is wrong and is duplicate of Q39. For Q100 there is a whole article explaining the issue and could be referenced. This is correctly answered in Q39 https://medium.com/@wisecobbler/using-a-function-in-setstate-instead-of-an-object-1f5cfd6e55d1
- Q95 is wrong, the correct answer is `<button onClick={(e) => this.hug(name, e)}>Hug Button</button>;` tested with `npx create-react-app my-app --scripts-version react-scripts@^2` where class syntax is default

Therefore newly added Q99 and Q100 answers are not correct, while Q27 and Q39 are the correct ones. 
EDIT: This pull request https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/pull/3195 needs to be reverted and revised @Ebazhanov @ahmed0saber

**Comment by showduhtung** [comment]
To add to this, #95 is incorrect. 
https://ebazhanov.github.io/linkedin-skill-assessments-quizzes/react/reactjs-quiz.html#q95-what-value-of-button-will-allow-you-to-pass-the-name-of-the-person-to-be-hugged

The answer should be `<button onClick={(e) => hug(name, e)}>Hug Button</button>;`

**Comment by Knightwalker** [comment]
@showduhtung i've decided to check #95, to confirm your findings, however it seems that nobody really evaluated #95 the proper way. Your answer really seems correct, but maybe we are biased by functional react! I've spend a few minutes to actually check what happens here, becase we have a question, which asks for react with class syntax, so it would be wise to check with react scripts v2 where classes were the standard, therefore we can create a new react app to test this way `npx create-react-app my-app --scripts-version react-scripts@^2`

next if we check all answers, yours will say `'hug' is not defined` , so we need to reference the class with `this.hug`.
`<button onClick={(name) => this.hug(name)}>Hug Button</button>; // hugging [object Object]`
`<button onClick={this.hug(e, name)}>Hug Button</button>; // 'e' is not defined`
`<button onClick={(e) => hug(name, e)}>Hug Button</button>; // 'hug' is not defined `
`<button onClick={(e) => this.hug(name, e)}>Hug Button</button>; // hugging kitten -> correct answer`

I'm lazy to check Q97, but it seems that the whole pull request needs to be reverted because it's all wrong. Or we just make a new one and fix this.
