### ISSUE TITLE
Missing Linux assignment answers

### ISSUE THREAD

**Issue by mtosity** [Ebazhanov/linkedin-skill-assessments-quizzes#3229]
![image](https://user-images.githubusercontent.com/40803798/157075998-d8396f36-48a3-4435-ada7-a13bfce92650.png)

**Comment by sifisKoen** [comment]
Q.78: Generate RSA or DSA key pairs using ssh-keygen 
`ssh-keygen -t rsa -b 4096 -C "a comment"`

**Comment by Ebazhanov** [comment]
> The questions link: https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/master/linux/linux-assessment.md#q78-what-do-you-need-to-do-before-you-can-perform-ssh-passwordless-logins
> 
> I'm not confident in Linux, but I will happy to validate answers in pr 😁

Thank you in advance @mtosity
