### ISSUE TITLE
Wrong Answer is selected

### ISSUE THREAD

**Issue by viny2cool** [Ebazhanov/linkedin-skill-assessments-quizzes#3245]
Q23. You created a meeting for next Friday at 1 PM, and several invitees have accepted. How do you change only your version of the meeting to 12 PM to allow time to setup?

The answer should be:
You cannot-Instead, create a separate appointment for yourself from 12 PM to 1PM.

**Comment by Ebazhanov** [comment]
Hello, @viny2cool! would be great if you will leave the reference in which quiz this question located, for the future reference! Thanks

**Comment by viny2cool** [comment]
This is under Microsoft Outlook quiz.
