### ISSUE TITLE
REVIT ANSWERS IF SOMEONE CAN DO IT <3

### ISSUE THREAD

**Issue by cffnascimento** [Ebazhanov/linkedin-skill-assessments-quizzes#3252]
![WhatsApp Image 2022-03-06 at 20 35 33](https://user-images.githubusercontent.com/91706968/158009479-33575964-f50f-458d-bb4f-041a23564bf6.jpeg)
![WhatsApp Image 2022-03-06 at 20 36 05](https://user-images.githubusercontent.com/91706968/158009480-0dc38928-e0c6-4ca7-a786-d7fd2f553bc2.jpeg)
![WhatsApp Image 2022-03-06 at 20 36 40](https://user-images.githubusercontent.com/91706968/158009482-39cf315b-fb98-4710-8207-deefab520de9.jpeg)
![WhatsApp Image 2022-03-06 at 20 36 58](https://user-images.githubusercontent.com/91706968/158009484-c853f3c3-343b-4ae2-bbaa-669d04ccf0a7.jpeg)
![WhatsApp Image 2022-03-06 at 20 37 25](https://user-images.githubusercontent.com/91706968/158009486-9d482fc0-2a35-4591-967b-93c070d7bb6d.jpeg)
![WhatsApp Image 2022-03-06 at 20 37 53](https://user-images.githubusercontent.com/91706968/158009489-fda274d5-9005-47e4-a165-bbfda77659a2.jpeg)
![WhatsApp Image 2022-03-06 at 20 49 07](https://user-images.githubusercontent.com/91706968/158009491-81525a26-740d-4f31-b351-d8dd1697ea97.jpeg)
![WhatsApp Image 2022-03-06 at 20 32 41](https://user-images.githubusercontent.com/91706968/158009492-4f0c085f-d0f0-44f9-8094-bd92a2963c02.jpeg)
![WhatsApp Image 2022-03-06 at 20 33 00](https://user-images.githubusercontent.com/91706968/158009493-ba96417d-50b0-40a4-a02c-293b137c6364.jpeg)
![WhatsApp Image 2022-03-06 at 20 33 27](https://user-images.githubusercontent.com/91706968/158009495-e7bec499-b63a-4bb0-ab84-e2bdda98e59d.jpeg)
![WhatsApp Image 2022-03-06 at 20 33 50](https://user-images.githubusercontent.com/91706968/158009496-ed2d21e6-e5e2-440c-ac20-4a7cd7dcc7a5.jpeg)
![WhatsApp Image 2022-03-06 at 20 34 20](https://user-images.githubusercontent.com/91706968/158009497-942d3bfc-e141-4eeb-9a9a-ca8fecfda8ee.jpeg)
![WhatsApp Image 2022-03-06 at 20 34 42](https://user-images.githubusercontent.com/91706968/158009498-5bdf9480-3b49-4bbc-b840-02b947697488.jpeg)
![WhatsApp Image 2022-03-06 at 20 35 01](https://user-images.githubusercontent.com/91706968/158009499-aff89898-53df-46a6-91f6-476b5d011f02.jpeg)

**Comment by Ebazhanov** [comment]
Thanks for screenshots @cffnascimento, added https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/master/revit/revit-quiz.md
