### ISSUE TITLE
html rendering bug🐛 

### ISSUE THREAD

**Issue by Dhoni77** [Ebazhanov/linkedin-skill-assessments-quizzes#3253]
In
https://ebazhanov.github.io/linkedin-skill-assessments-quizzes/
Instead of html being rendered Markdown is being rendered.

Bug🐛 
```
<td><a href="c%23/c-sharp-quiz.md">C#</a></td>
<td><a href="c%2B%2B/c%2B%2Bquiz.md">C++</a></td>
<td><a href="c-(programming-language)/c-quiz.md">C (Programming Language)</a></td>
```
Fix :heavy_check_mark:
```
<td><a href="c%23/c-sharp-quiz.html">C#</a></td>
<td><a href="c%2B%2B/c%2B%2Bquiz.html">C++</a></td>
<td><a href="c-(programming-language)/c-quiz.html">C (Programming Language)</a></td>
```

**Comment by Ebazhanov** [comment]
@Dhoni77 thanks for suggestion, you mean change `md` format to `html`, not sure that I fully understand your idea and what we want to improve! Can you please create PR to see it in actions? Thank you in advance!

**Comment by Dhoni77** [comment]
Hi @Ebazhanov if you go to the below link you can find out that html is not being rendered!
https://ebazhanov.github.io/linkedin-skill-assessments-quizzes/c%2B%2B/c%2B%2Bquiz.md
And I think that I don't have access to the website source so I can't fix it😌

**Comment by Dhoni77** [comment]
Just change .md to .html that 'll work✨

**Comment by Ebazhanov** [comment]
got it now thanks, need to think about better approach, not sure that after switching to `html` all formatting will be the same
