### ISSUE TITLE
Javascript question Q96 seems to be marked the wrong answer.

### ISSUE THREAD

**Issue by willmustafa** [Ebazhanov/linkedin-skill-assessments-quizzes#3268]
![image](https://user-images.githubusercontent.com/55210887/158235886-cea4ea63-0e84-41e5-9810-0352a43ed80e.png)
The answer `animals.reverse()` is also wright isn't?

**Comment by Trishadring** [comment]
just checked and they both work.

**Comment by hamin-lee** [comment]
Should be both since 
animals.reverse() will make animals = ['eagle', 'jaguar'] and
animals.pop() pops from end of the list.
