### ISSUE TITLE
Maven Q 16 

### ISSUE THREAD

**Issue by nithish-thomas** [Ebazhanov/linkedin-skill-assessments-quizzes#3283]
#### Q16. Many organizations set up local mirrors to the Maven central repository. In order to leverage your company's Maven repository as a proxy for the Maven central repository, which element should you put into the settings.xml file?

- [ ] Replacements
- [ ] Proxies
- [ ] Mirrors
- [x] LocalRepositories

Local repository defines the path of the local copy of the repository on your machine something like C:\

shouldn't mirrors be the actual answer? https://maven.apache.org/settings.html#mirrors

**Comment by Ebazhanov** [comment]
thank you @nithish-thomas, added
