### ISSUE TITLE
Microsoft Excel Assessment

### ISSUE THREAD

**Issue by andrehunga** [Ebazhanov/linkedin-skill-assessments-quizzes#3337]
You want to restrict the values entered in a cell to a specified set, such as hop, skip, jump. Which type of data validation should you use?

- [ ] database
- [x] list
- [ ] input range 
- [ ] custom

**Comment by VLEU** [comment]
**list** would be the answer.

**Comment by Ebazhanov** [comment]
Thank you guys 👍, question was added!
