### ISSUE TITLE
Microsoft Excel Assessment

### ISSUE THREAD

**Issue by andrehunga** [Ebazhanov/linkedin-skill-assessments-quizzes#3338]
Given the image below, What happens if you type "P" in cell A6?
![FireShot Capture 149 - 2 png (1280×1024) - ](https://user-images.githubusercontent.com/39540175/159786272-659ace29-fae1-4171-8712-833062156bf1.jpg)

- [ ] The word "Perez" appears and immediately the active cell moves down
- [ ] The word "Perez" appears and the active cell remains in Edit mode.
- [ ] The letter "P" appears.
- [ ] A Pop-up list appears with the previous four names

**Comment by VLEU** [comment]
** The word "Perez" appears and the active cell remains in Edit mode.**

**Comment by Ebazhanov** [comment]
Thank you @VLEU @andrehunga, question and answer already in codebase
