### ISSUE TITLE
IT-Operations new question

### ISSUE THREAD

**Issue by Issac-Lopez** [Ebazhanov/linkedin-skill-assessments-quizzes#3340]
Tania was told to address an issue in the UEFI. How is it accessed?

- [ ] from the computer's startup menu
- [ ] by using the System Configuration Utility (MSCONFIG)
- [x] from the BIOS
- [ ] on the network
<img width="860" alt="itOperationsMissedQuestion" src="https://user-images.githubusercontent.com/92846820/159818015-061e2021-91a6-449d-88d3-7aa282fb5d55.PNG">

**Comment by Ebazhanov** [comment]
Thank you @Issac-Lopez question already in the repo
