### ISSUE TITLE
CSS skill assment - some question marks

### ISSUE THREAD

**Issue by JMJHautier** [Ebazhanov/linkedin-skill-assessments-quizzes#3343]
Hi there, 

in the CSS assessment,
 
 **Q43 ** is as follow: 
![image](https://user-images.githubusercontent.com/13255701/159917961-27a7e038-3120-4a88-8ebf-19b96adc9325.png)

The suggested answer would only select internal hyperlinks, sure, but only those that have no references. To select all internal hyperlinks of a page, one would need to select all href that _starts_ with "#", right? 

Hence, should'nt the right answer be: 
`   a[href^="#"]`
?

**Q112** has no answer indicated, but I guess it would be: 
![image](https://user-images.githubusercontent.com/13255701/159938478-d6e80ad9-02b6-433d-8ebb-d66278a34d47.png)

**Q119** also has no answers indicated, I guess it would be: 
![image](https://user-images.githubusercontent.com/13255701/159939589-5dccd1d5-a2d7-43fc-9763-4254b4a0c44a.png)

**Comment by masoudk1990** [comment]
@JMJHautier What you said about Q43 and Q112 is correct. But the correct answer for Q119 is:
```
section + p {
  color: blue;
}
```
It means select the first `<p>` immediately after `<section>`

**Comment by JMJHautier** [comment]
> @JMJHautier What you said about Q43 and Q112 is correct. But the correct answer for Q119 is:
> 
> ```
> section + p {
>   color: blue;
> }
> ```
> 
> It means select the first `<p>` immediately after `<section>`

Oh yeah, my bad. Thanks for the correction and related PR.
