### ISSUE TITLE
C# new question

### ISSUE THREAD

**Issue by eikowagenknecht** [Ebazhanov/linkedin-skill-assessments-quizzes#3354]
![image](https://user-images.githubusercontent.com/1475672/160087727-db396744-427d-4a56-9b7b-b154013040c9.png)

**Comment by eikowagenknecht** [comment]
Seems like 4 (People[^1]) is the answer since C# 8. Can someone confirm this? Then I'll create a PR ;-)

**Comment by masoudk1990** [comment]
@eikowagenknecht You are right, none of the options is correct. These options are correct (using range):
```
People[1..]
People[1..3]
People[1..^0]
People[^2..]
People[^2..3]
People[^2..^0]
```
Maybe this question was made before C# 8.0 (September 2019)

**Comment by wolfkin** [comment]
Question 69 indicates the answer is 

`People[..^2]`

**Comment by lnugraha** [comment]
Hi, just a short clarification. This question has appeared before as  Q#67 in C-sharp assessment.

**Comment by MarcinWatroba** [comment]
Even if that question would appear on version 1.0 it'd still be bad. Simple solution would be to use "None of the above" as an answer rather than "You can't do this..."

**Comment by pritam1309** [comment]
people[..^2]

**Comment by Ebazhanov** [comment]
as a solution/workaround we could add detailed explanation to this question and close this issue?

**Comment by masoudk1990** [comment]
I just unchecked the current chosen answer (which is obviously wrong) and added some explanations about the question and added a reference link to the current issue thread.
