### ISSUE TITLE
Front-End Development

### ISSUE THREAD

**Issue by Ebazhanov** [Ebazhanov/linkedin-skill-assessments-quizzes#3382]
![image](https://user-images.githubusercontent.com/13170022/160256136-e05bdf30-2b87-4c0e-a7e3-b3fe34d3887f.png)
![image](https://user-images.githubusercontent.com/13170022/160256150-e4695dd1-3aac-42a4-9f03-237da6ff042b.png)
![image](https://user-images.githubusercontent.com/13170022/160256159-7950e213-e394-4513-aafe-095c3135958d.png)

**Comment by SirDev97** [comment]
I'm on it! 🤓
