### ISSUE TITLE
Cybersecurity Assessment

### ISSUE THREAD

**Issue by Populationz** [Ebazhanov/linkedin-skill-assessments-quizzes#3401]
![Untitled](https://user-images.githubusercontent.com/29377581/160503293-3d1b3939-4efb-4799-ba02-d35f9eb3b69e.png)

**Comment by Populationz** [comment]
![Untitled](https://user-images.githubusercontent.com/29377581/160506206-43ccf3a4-5762-4976-a390-860931ea695b.png)

**Comment by Populationz** [comment]
![Untitled](https://user-images.githubusercontent.com/29377581/160506323-745e28cd-8f0c-45bc-b5e6-f163a8f3fdeb.png)

**Comment by Ebazhanov** [comment]
@Populationz thank you! 💪 
I have added all questions
