### ISSUE TITLE
Photoshop (outdated)

### ISSUE THREAD

**Issue by its0x08** [Ebazhanov/linkedin-skill-assessments-quizzes#3412]
Just tried Photoshop answers and got 2 of 15 from the answers list, 13 were new questions.

**Comment by Ebazhanov** [comment]
yes right! going to close it, thank you for raising this issue! 👍

**Comment by its0x08** [comment]
Well I was going to put the screenshots here so people can answer when they can, since I'm not pro in Photoshop theories.. 😁

**Comment by its0x08** [comment]
![1](https://user-images.githubusercontent.com/15280042/161383668-96377852-ea32-441e-b68e-4d6658f02358.png)
![2](https://user-images.githubusercontent.com/15280042/161383670-f16d654b-f33a-48ff-8ccc-e2f0cf3309f4.png)
![3](https://user-images.githubusercontent.com/15280042/161383672-da564e8e-aecf-4aa8-9ecc-022d5a076a5e.png)
![4](https://user-images.githubusercontent.com/15280042/161383673-90725b28-2f2b-44eb-8dcd-8731117bdaa0.png)
![5](https://user-images.githubusercontent.com/15280042/161383674-6379f5aa-019a-47eb-b840-9566b2c6d822.png)
![6](https://user-images.githubusercontent.com/15280042/161383677-ce6d1d8d-1c24-475f-9d58-c24dacfc1d98.png)
![7](https://user-images.githubusercontent.com/15280042/161383678-523b3f70-d6eb-402b-b4a7-4c79aab23f7a.png)
![8](https://user-images.githubusercontent.com/15280042/161383680-a54d7cc9-8834-4594-bc58-5f9ff1175c99.png)
![9](https://user-images.githubusercontent.com/15280042/161383683-1ea0747c-3ea9-4b2a-a052-b3f6fa14991b.png)
![10](https://user-images.githubusercontent.com/15280042/161383684-e70dc799-5fe1-44fa-839e-5ae5463e7503.png)
![11](https://user-images.githubusercontent.com/15280042/161383685-d06fc980-3200-45c4-a38f-2bafdc514c0f.png)
![12](https://user-images.githubusercontent.com/15280042/161383687-2fc7cee2-2843-4c21-b518-5f82337c4dd9.png)
![13](https://user-images.githubusercontent.com/15280042/161383688-55e44cde-f112-4299-bf0c-8f8a11a17881.png)
![14](https://user-images.githubusercontent.com/15280042/161383689-94acf9e8-3aea-4349-947c-e4a594e705b3.png)
![15](https://user-images.githubusercontent.com/15280042/161383690-3194b444-06e9-47f0-b8b0-5a1e2864ac3c.png)

**Comment by its0x08** [comment]
![1](https://user-images.githubusercontent.com/15280042/161383731-32a391fe-3aeb-49a2-9328-5be85a6bef06.png)
![2](https://user-images.githubusercontent.com/15280042/161383746-9b9e3777-7858-46e7-a054-2b0bdafd71e0.png)
![3](https://user-images.githubusercontent.com/15280042/161383747-1a81fc57-1ee4-4cbd-851b-ff78018a0119.png)
![4](https://user-images.githubusercontent.com/15280042/161383748-c87de813-311d-4e40-9d5d-b218bdc84982.png)
![6](https://user-images.githubusercontent.com/15280042/161383787-174891fd-ec41-4c41-98d6-9dfd2315b72e.png)
![8](https://user-images.githubusercontent.com/15280042/161383798-a3dbdf95-acb8-43ff-8bde-534c82ae7a32.png)
![11](https://user-images.githubusercontent.com/15280042/161383810-1f218398-d747-4ded-85e5-e4ba312f9e96.png)
![12](https://user-images.githubusercontent.com/15280042/161383816-a32cdbe8-0a1b-4de5-9ef7-cd2c343d9d60.png)
![13](https://user-images.githubusercontent.com/15280042/161383821-d3678802-b6c2-4b09-895b-2fdd10f078c3.png)
![15](https://user-images.githubusercontent.com/15280042/161383828-705a5f03-d50a-433d-9cd9-d37ae67247b1.png)
![14](https://user-images.githubusercontent.com/15280042/161383823-4f44f2a1-ff42-4a52-ab01-92ad6b5210ec.png)

**Comment by wolfkin** [comment]
send a PR for the first 5 questions. 6 remaining.

**Comment by Ebazhanov** [comment]
Thank you guys @its0x08 @wolfkin, great job! 💪 
i have added the rest of the questions

**Comment by its0x08** [comment]
You're welcome 😁
