### ISSUE TITLE
C++ New Question

### ISSUE THREAD

**Issue by sirNugg3ts** [Ebazhanov/linkedin-skill-assessments-quizzes#3430]
ScreenShot

![image](https://user-images.githubusercontent.com/28486181/161394378-ecec3278-ff7f-4591-9241-21c7c0379698.png)

**Comment by MohamedMamdouh18** [comment]
> ScreenShot
> 
> ![image](https://user-images.githubusercontent.com/28486181/161394378-ecec3278-ff7f-4591-9241-21c7c0379698.png)
answer will be first one: 
-->marks["Sinead"] = 22 ;

**Comment by Ebazhanov** [comment]
@sirNugg3ts @MohamedMamdouh18 thank you guys, have added question with correct answer 👍
