### ISSUE TITLE
New JQuery Questions

### ISSUE THREAD

**Issue by cybercommando** [Ebazhanov/linkedin-skill-assessments-quizzes#3449]
Question 1)
Answer) I answered: None of these - JQuery requires AJAX.
![Screenshot (26)](https://user-images.githubusercontent.com/65307303/161766105-5f45d6fe-e170-4f26-982c-6ae18f362098.png)

Question 2)
Answer) I answered: 4th option ($.ready( ... ).then( ... ){ ... })
![Screenshot (27)](https://user-images.githubusercontent.com/65307303/161766118-8ffc333b-c1d1-46a7-a996-768015ee9df7.png)

I attempted JQuery assessment on (05 Apr 2022) and found these two new questions. Just verify my answers and add these questions in list.

**Comment by Ebazhanov** [comment]
Thanks a lot @cybercommando 👍 , all questions were successfully added!
