### ISSUE TITLE
C (Programming Language)

### ISSUE THREAD

**Issue by Ebazhanov** [Ebazhanov/linkedin-skill-assessments-quizzes#3455]
![c3](https://user-images.githubusercontent.com/13170022/161910112-81cdf623-e1f0-4c75-84eb-0469993dfe8d.png)
![c2](https://user-images.githubusercontent.com/13170022/161910120-d4ab03f8-adff-41ad-b475-1495c3a566ff.png)
![c1](https://user-images.githubusercontent.com/13170022/161910122-d4de031d-2e3a-4362-a6aa-3c57c383bd8f.png)

**Comment by alescrocaro** [comment]
Q15 - strstr(str1, str2);
Q14 - Static functions can be accessed only in the file where they are declared;
Q13 - time_t.
@Ebazhanov

**Comment by Ebazhanov** [comment]
Thank you @alescrocaro 👍
