### ISSUE TITLE
New Microsoft Excel questions

### ISSUE THREAD

**Issue by MarkPuchalaII** [Ebazhanov/linkedin-skill-assessments-quizzes#3464]
I just finished the Microsoft Excel quiz and didn't see these questions on there. 
Not 100% sure I selected the right answers; Am I making this issue right?
![excelDuplicate](https://user-images.githubusercontent.com/11304487/162101157-69c82ab5-106d-49b7-9af8-d664b516b2c6.png)
![linkedInAssessmentExcel](https://user-images.githubusercontent.com/11304487/162101165-62c42ebf-82a7-453c-b5b9-226f8b19e562.png)

**Comment by ckullo** [comment]
@MarkPuchalaII 
You've already chosen the right answer.
I've added this questions

**Comment by Ebazhanov** [comment]
Thanks you guys @MarkPuchalaII @ckullo 🙏
