### ISSUE TITLE
AWS added 3 questions

### ISSUE THREAD

**Issue by maheshdbabar9340** [Ebazhanov/linkedin-skill-assessments-quizzes#3466]
![Screenshot (2415)](https://user-images.githubusercontent.com/53929423/162138306-a6adc321-e779-4aab-afa7-34133097cdce.png)
![2](https://user-images.githubusercontent.com/53929423/162138321-84104f78-8239-4e66-9f95-e013ffcedbe3.png)
![3](https://user-images.githubusercontent.com/53929423/162138345-b30ba709-f97a-4cb3-a02d-91c3850c6143.png)

**Comment by Ebazhanov** [comment]
Thank you @maheshdbabar9340 👍 
everything already in https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/master/aws/aws-quiz.md
