### ISSUE TITLE
Revit Skill Test

### ISSUE THREAD

**Issue by AkshayAjaykumar** [Ebazhanov/linkedin-skill-assessments-quizzes#3496]
Can someone please answer the questions for the Revit skill test please?

**Comment by parikhparth23** [comment]
Created a PR - https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/pull/4641

@Ebazhanov Please merge this [PR](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/pull/4641)
