### ISSUE TITLE
Copyrights

### ISSUE THREAD

**Issue by Yosoku** [Ebazhanov/linkedin-skill-assessments-quizzes#3499]
What kind of licenses are related to these quiz questions? Can I use them in my own application? Do I need to reference linkedin if I do?

**Comment by monkrus** [comment]
Hi @Yosoku ! Thank you for your inquiry.

No license is required if your application has an educational or testing purpose. Please mention our repository in your work so others can also benefit from it.

In the case of commercial usage, we ask for a 10% royalty fee as we put a lot of time and effort into maintaining this project.

Thank you,
@monkrus

**Comment by Yosoku** [comment]
Thank you for your quick response and highly appreciate your work. Have a nice day

**Comment by Timmmm** [comment]
Ha are you seriously trying to charge royalties on questions that you copied without permission from LinkedIn?

I'm surprised they haven't DMCA'd this repo already.
