### ISSUE TITLE
Microsoft Outlook

### ISSUE THREAD

**Issue by AkshayAjaykumar** [Ebazhanov/linkedin-skill-assessments-quizzes#3512]
Microsoft Outlook has many wrong answers. Failed the test even though most questions were from the list.

**Comment by wolfkin** [comment]
It would be helpful if you could identify questions with wrong answers so we can at least submit a PR to remove the answers

**Comment by monkrus** [comment]
@wolfkin @AkshayAjaykumar thank you for bringing this to our attention. The repository is updated every day. It is hard to guarantee to 100% match, but we believe in the goodwill of our contributors. Please contribute to Microsoft Outlook section and we will  gladly add you as contributors.
