### ISSUE TITLE
Front-end Development new question

### ISSUE THREAD

**Issue by the-central** [Ebazhanov/linkedin-skill-assessments-quizzes#3520]
![QQ](https://user-images.githubusercontent.com/96765227/163135417-d1b50d2c-1669-4756-a1b3-693314f35590.png)

**Comment by Ebazhanov** [comment]
thank you @the-central 👍  already in https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/master/front-end-development/front-end-development-quiz.md
