### ISSUE TITLE
Discussion

### ISSUE THREAD

**Issue by od-c0d3r** [Ebazhanov/linkedin-skill-assessments-quizzes#3525]
Hi there :wave: 

I just wanna talk about the pros and cons of hosting these READMEs and its impacts of LinkedIn recruiting Eco-system...

For me, I believe this Repo should be halted immediately, it's not an act of a professionals at all and its only making negative impacts on recruiters linkedin trust.
Also it makes us not working nor studying and only go for the easy solutions. 

Please i wanna read more about your point of view for having, using, or helping theses READMEs.

Thanks.

**Comment by monkrus** [comment]
Hi @od-c0d3r 

Thank you for your question! Allow me to give you an example.
Let`s say ,someone has a knife. One can cut a loaf of bread with it, or, possible an apple. However, you can easily hurt yourself or somebody else.

Same idea is here. This is a tool that can be used in many ways. We put a lot of of hours of free work in maintaining this repository for many years, and get a lot of  positive feedback. Many letters from our users. The scope of this repo is not limited with answering LinkedIn testing questions, but also help to prepare for the interview, use data for testing, in the app, and much more. 

This is where we stand, 
Respectfully,
@monkrus

**Comment by od-c0d3r** [comment]
Thanks @monkrus for your reply, 

I don't think this is the case here.
I'm literally reading now the repo README and it says `This repository is for those looking for answers to the LinkedIn assessment quiz questions or willing to help others by contributing to the tests.` and there is no mention for any interview preparations.

And since I see users creating issues ONLY to add questions from LinkedIn tests that are not existed in the READMEs.

The only Solution to this, is to delete all the READMEs, and help people go to study and READ instead of getting easy info using this repo to pass the tests.

If our decision didn't came out with any solution, at least we can add a disclaimer on the repo README, that you are professionally not responsible about any user could misbehaving your repo. and change any `linkedin` string occurrence from your READMEs. if you don't have time to do so i will volunteer.

at the end we are all looking towards our craft with responsibility.

Thanks for taking your time reading this.
Best

**Comment by monkrus** [comment]
Thank you for your input, we' ll think about it.When we create an issue, we assign it to you.

**Comment by monkrus** [comment]
Issue created, it is all yours

 https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/issues/3530
