### ISSUE TITLE
Add a professional liability disclaimer to the readme.

### ISSUE THREAD

**Issue by monkrus** [Ebazhanov/linkedin-skill-assessments-quizzes#3530]
We would like to update our readme file and add the following:

-professionally-looking disclaimer stating owners of the repository is not liable for any illegal usage of it.
-make it short and clear
-use official templates as a model 

Thank you!

**Comment by AlphaVS-76** [comment]
Can i be assigned this issue!

**Comment by monkrus** [comment]
@AlphaVS-76 Thank you for taking this issue!

**Comment by elenderg** [comment]
DISCLAIMER: The owners of this repository are not liable for any illegal usage of the content provided in this repository. The content is provided for informational and educational purposes only, and any actions taken by users of this repository are the responsibility of the user. By accessing this repository, you agree to hold the owners harmless from any claims, damages, or expenses arising from the use of the information provided.

**Comment by monkrus** [comment]
Thank you @elenderg.
@all-contributors please add @elenderg for content
