### ISSUE TITLE
Change the answers of Q11 in MySQL quiz

### ISSUE THREAD

**Issue by mikolajgawronski** [Ebazhanov/linkedin-skill-assessments-quizzes#3535]
While taking the quiz today I encountered a question that was on the list but It had different answers than in the document.

![Przechwytywanie](https://user-images.githubusercontent.com/54740661/163731146-ae4590ca-d833-4faa-9f27-7d7840084b01.PNG)

Note: I don't know if I had marked the correct answer, I think it's either A or B, that's why I'm adding this issue. I don't know if the older version of the question should be kept or replaced by the new one.

**Comment by Ebazhanov** [comment]
Thank you guys @mikolajgawronski, @wolfkin 💪
