### ISSUE TITLE
Ruby on Rails

### ISSUE THREAD

**Issue by Ebazhanov** [Ebazhanov/linkedin-skill-assessments-quizzes#3586]
![Captura_de_Tela_12](https://user-images.githubusercontent.com/13170022/165384252-3071d5b9-5841-4833-8771-52f1a8789c4c.png)
![Captura_de_Tela_11](https://user-images.githubusercontent.com/13170022/165384255-a6efc925-2a4d-4c48-a54e-3eb5dc3764f3.png)
![Captura_de_Tela_13](https://user-images.githubusercontent.com/13170022/165384259-45626c82-2a35-4646-8138-083460a3052a.png)
![Captura_de_Tela_14](https://user-images.githubusercontent.com/13170022/165384260-c40a6103-70ba-4f54-82c5-825d5cbf592f.png)
![Captura_de_Tela_15](https://user-images.githubusercontent.com/13170022/165384263-e12c4cbc-0af3-49c1-9987-e3c94b1ad4ab.png)
![Captura_de_Tela_16](https://user-images.githubusercontent.com/13170022/165384264-4e3bf583-ec5d-45cd-8fdb-08aa1f7d9e47.png)
![Captura_de_Tela_18](https://user-images.githubusercontent.com/13170022/165384266-451abd59-a773-4e83-a87c-6b1901ad6934.png)
![Captura_de_Tela_19](https://user-images.githubusercontent.com/13170022/165384270-8e55ba78-c227-496a-87b9-93e0b27c582f.png)

**Comment by mewthu2** [comment]
i hope i can help you =)
1/5 - D
3/15 - B
5/15 - A
6/15 - I don`t remember now, sorry
11/15 - A
13 /15- D
14/15 - D

**Comment by Ebazhanov** [comment]
thanks a lot @mewthu2 💪
