### ISSUE TITLE
Javascript , Q82

### ISSUE THREAD

**Issue by anuragmy** [Ebazhanov/linkedin-skill-assessments-quizzes#3595]
console.log('I');
setTimeout(() => {
  console.log('love');
}, 0);
console.log('Javascript!');

the answer is 1st options, but it is mention as last option

**Comment by ABHISHEKKURADIA** [comment]
The answer is:

"I 
Javascript
Love"

Because the setTimeout uses the time computation even when its zero and the script runs asynchronously, the console will display after Javascript.

**Comment by ABHISHEKKURADIA** [comment]
The answer is:

"I 
Javascript
Love"

Because the setTimeout uses the time computation even when its zero and the script runs asynchronously, the console will display after Javascript.

**Comment by ahjam-taoufik** [comment]
you are wrong Mr [anuragmy](https://github.com/anuragmy)
the answer is 2end , you can try it
