### ISSUE TITLE
New questions in Matlab

### ISSUE THREAD

**Issue by tmigot** [Ebazhanov/linkedin-skill-assessments-quizzes#3633]
Today, I had four new questions that weren't in the Matlab's list.

Which choice *cannot* add a directory to the search path?
- [ ] the **path** function
- [x] the **savepath** function
- [ ] using **Set Path** in the **Environment** menu
- [ ] the **addpath** function

Which is *not* a function to plot three-dimensional data?
- [ ] **mesh**
- [ ] **surf**
- [ ] **contour**
- [x] **grid**

At what will MATLAB look first for a called function?
- [ ] built-in functions
- [x] functions within the current directory
- [ ] functions on the path
- [ ] functions within the current file

What is the reason to save a MAT-file using the **v-7.3** flag?
- [ ] to use compression by default
- [ ] to ensure backward compatibility
- [x] to include a variable greater than 2GB
- [ ] to avoid HDF5 overhead in MAT-file

**Comment by tmigot** [comment]
For the first one, `savepath` only saves the current path
https://www.mathworks.com/help/matlab/ref/savepath.html
For the second, I want to say `grid` as it only display (or not) the grid on any plot:
https://www.mathworks.com/help/matlab/ref/grid.html
The link for the third:
https://www.mathworks.com/help/matlab/matlab_env/files-and-folders-that-matlab-accesses.html
The link for the last one: 
https://www.mathworks.com/matlabcentral/answers/169755-saving-variable-with-v7-3-flag-check

**Comment by grunsho** [comment]
This graph could be the result of which block of code? This graph could be the result of which block of code? 
[IMAGE](https://ibb.co/x2fJ05B)
• a = randn(1,1000); histogram(a) ylabel('counts')
• a = rand(1,1000); histogram(a) ylabel('counts')
• a = randi(1,1000); histogram(a) ylabel('counts')
• a = rng(1,1000); histogram(a) ylabel('counts')

**Comment by Ebazhanov** [comment]
@grunsho @tmigot @lnugraha thank you for your great input guys! 💪

**Comment by Ebazhanov** [comment]
@tmigot fyi i have added all the reference links
