### ISSUE TITLE
All were new questions excel

### ISSUE THREAD

**Issue by noobimpostor2** [Ebazhanov/linkedin-skill-assessments-quizzes#3634]
I could found other test solutions , but can't excel. 

First two attempts given by me, I have profiency in excel.although I couldn't clear. I directly given exams of other that were easy and clearable - Adobe powerpoint and Accounting. But can't with excel. Every question was new and couldn't be found in this document.

I hadn't took list ,but on next attempt i will.

**Comment by monkrus** [comment]
@noobimpostor2  LinkedIn constantly updates answers and questions, so some of them could be missing.We get new contributions every day, but can`t cover everything! Do contribute!

**Comment by noobimpostor2** [comment]
Ya I know. LinkedIn is most likely doing discrimination and biased
questions. Asks different difficulty questions to different people. I hate
this.
