### ISSUE TITLE
Kotlin Question 52

### ISSUE THREAD

**Issue by anupdey99** [Ebazhanov/linkedin-skill-assessments-quizzes#3638]
https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/master/kotlin/kotlin-quiz.md#q52-this-code-snippet-compiles-without-error-but-never-prints-the-results-when-executed-what-could-be-wrong

I believe the right answer is 2.

**Comment by Ebazhanov** [comment]
Thanks @anupdey99 updated 👍
