### ISSUE TITLE
JSON assessment doesn't get in the top 30%

### ISSUE THREAD

**Issue by pmrzygweb** [Ebazhanov/linkedin-skill-assessments-quizzes#3661]

**Comment by Nuung** [comment]
me too :')

**Comment by yktsang01** [comment]
i just attempted this one and got the same

**Comment by emanuele-em** [comment]
the same!

**Comment by monkrus** [comment]
@Nuung , @pmrzygweb , @emanuele-em As you all know, it is hard to guarantee that all the answers are 100% correct. The repository is in a state of correction on the daily basis. Please contribute to the JSON answers to improve their quality.
