### ISSUE TITLE
Linux

### ISSUE THREAD

**Issue by Ebazhanov** [Ebazhanov/linkedin-skill-assessments-quizzes#3677]
![q2](https://user-images.githubusercontent.com/13170022/168854768-41f37a38-d622-448c-83b0-797dd0c8a726.png)
![q1](https://user-images.githubusercontent.com/13170022/168854775-5c7de603-ee5d-4717-8b2e-e09ab4d5b7ff.png)

**Comment by Ebazhanov** [comment]
Thank you @Nuung for review, fyi I have copied it from discord chat without checking.

**Comment by victoriacheng15** [comment]
@Ebazhanov the 2nd question was added with #3724.

**Comment by Ebazhanov** [comment]
@victoriacheng15 @Nuung added your reference
