### ISSUE TITLE
Angular Q53 doesn't have an answer

### ISSUE THREAD

**Issue by masoudk1990** [Ebazhanov/linkedin-skill-assessments-quizzes#3686]
Q53. Describe the usage of this code
```
export interface AppSettings {
	title: string;
	version: number;
}
export const APP_SETTINGS = new Injection<AppSettings>('app.settings');
```

- [ ] The InjectionToken is adding an instance of the AppSettings to the root provider via the InjectionToken constructor call, making it automatically available to all NgModules, services and components throughout the Angular application without the need to inject it anywhere.

- [ ]  The InjectionToken is used to create a provider token for a non-class dependency. An Object literal can be provider as a value for the APP_SETTINGS dependency provider type that can then be injected into components, services, etc ..

- [ ]  The InjectionToken is used to create a dynamic decorator for the AppSettings that can be used on constructor parameters via an @AppSettings decorator.

- [ ]  This code has an error since you cannot use a TypeScript interface for the generic type on the InjectionToken
---
According to [this article](https://www.tektutorialshub.com/angular/injection-token-in-angular/#what-is-an-injection-token) I think correct answer is this:

_The InjectionToken is used to create a provider token for a non-class dependency. An Object literal can be provider as a value for the APP_SETTINGS dependency provider type that can then be injected into components, services, etc .._

But I prefer to confirm it with you guys before I commit any pull-requests related to this.

**Comment by Sync271** [comment]
Part of the reason for not having an answer could be that the question has `Injection` but all the answers refer to `InjectionToken`

**Comment by masoudk1990** [comment]
> Part of the reason for not having an answer could be that the question has `Injection` but all the answers refer to `InjectionToken`

I assumed they meant `InjectionToken` in the question.

**Comment by masoudk1990** [comment]
I just took a test and this question was among the questions. I can confirm that it is `InjectionToken` in the question and it should be fixed in the repo.
```
export interface AppSettings {
	title: string;
	version: number;
}
export const APP_SETTINGS = new InjectionToken<AppSettings>('app.settings');
```

**Comment by Kaushik-Iyer** [comment]
Can I try to work on this?

**Comment by masoudk1990** [comment]
> Can I try to work on this?

Sure. That would be nice :)

**Comment by Kaushik-Iyer** [comment]
I think I created a new pull request and made the required changes.

**Comment by masoudk1990** [comment]
Done in #3775
