### ISSUE TITLE
javascript: duplicated questions

### ISSUE THREAD

**Issue by jacklee814** [Ebazhanov/linkedin-skill-assessments-quizzes#3712]
I think the Q20 and Q88 are the same, do we need to remove one of them?

### Q.20
![image](https://user-images.githubusercontent.com/9951291/169689038-ecbef020-7bb9-419c-90c0-7109b36a6d35.png)

### Q.88
![image](https://user-images.githubusercontent.com/9951291/169689056-fea4c25a-243c-4d6b-88b6-c265a5788b19.png)

---------

It's the same content and answer but the question is a little different. lol

### Q.13

![image](https://user-images.githubusercontent.com/9951291/169689251-75825592-cccb-4522-abb5-a3757dd40f79.png)

### Q.91

![image](https://user-images.githubusercontent.com/9951291/169689261-3d67dc92-cfa0-4fc4-88ab-e20981589407.png)

---------

### Q.46

![image](https://user-images.githubusercontent.com/9951291/169689903-1fb491e3-00a7-491d-96fb-17739581cfd3.png)

### Q.98

![image](https://user-images.githubusercontent.com/9951291/169689896-5d9bae21-2916-4c6d-9d9a-28fa050f3a8a.png)

---------

### Q.64

![image](https://user-images.githubusercontent.com/9951291/169690313-5470915e-04e7-41e9-9f35-e55ea2a22e9e.png)

### Q.104

![image](https://user-images.githubusercontent.com/9951291/169690307-0aa59a83-bcc7-43ed-8c0e-e4c61be6c649.png)

---------

### Q.83

![image](https://user-images.githubusercontent.com/9951291/169690506-408a526c-2c9d-41d1-be06-419e36ae4f2f.png)

### Q.116

![image](https://user-images.githubusercontent.com/9951291/169690514-2ff10f80-da49-41ea-888a-9905c33707dc.png)

**Comment by ruslanbes** [comment]
A good training set for [duplicate detective](https://github.com/linkedin-faq/duplicate-detective) in future. It only auto-detected 2 of these

**Comment by Ebazhanov** [comment]
thank you all 🙏 , closing ...
