### ISSUE TITLE
Photoshop new questions

### ISSUE THREAD

**Issue by random42069** [Ebazhanov/linkedin-skill-assessments-quizzes#3726]
![1](https://user-images.githubusercontent.com/106121256/169917703-6c1126b3-7a8d-4bb5-b802-676d40eed227.png)
![2](https://user-images.githubusercontent.com/106121256/169917705-cd516f52-5950-4865-ad14-caf2f82eba24.png)
![3](https://user-images.githubusercontent.com/106121256/169917707-6bac2bda-e345-4af8-88f0-82712e2a6110.png)
![4](https://user-images.githubusercontent.com/106121256/169917709-a3b2a74b-8a98-4b3c-b148-d3f0c9fd1416.png)
![5](https://user-images.githubusercontent.com/106121256/169917710-b2b39e66-c50d-4936-84dd-cbacb0b8f8d5.png)
![6](https://user-images.githubusercontent.com/106121256/169917712-6fe2bacf-be6a-4463-b9ff-23827017c100.png)
![7](https://user-images.githubusercontent.com/106121256/169917713-0e43c153-83ff-4d32-9283-cf665b07accd.png)
![8](https://user-images.githubusercontent.com/106121256/169917714-64457da9-df67-4ae9-b6a2-faff63f823c4.png)
![9](https://user-images.githubusercontent.com/106121256/169917716-2c8f9b80-2a11-4e8e-86fb-6a36cf3089fa.png)
![10](https://user-images.githubusercontent.com/106121256/169917719-030fe4c0-4aad-4c47-be30-3559cfd809e6.png)
![11](https://user-images.githubusercontent.com/106121256/169917720-3c420d62-4c3f-46e8-99a2-851b71b3d212.png)
![12](https://user-images.githubusercontent.com/106121256/169917721-ed4f168e-d614-4d1f-bc22-d385bd1490c9.png)
![13](https://user-images.githubusercontent.com/106121256/169917722-d9f3139f-e6c8-451c-8dd7-4a9e05062c02.png)
![14](https://user-images.githubusercontent.com/106121256/169917723-e95d0fd6-e7dc-4cd4-a943-6caba7681e9a.png)
![15](https://user-images.githubusercontent.com/106121256/169917724-dde6aed1-550c-4775-a368-206183439186.png)

**Comment by Ebazhanov** [comment]
@MahendraBishnoi29 sorry for delay with answer, yes please!

**Comment by auchynnikau** [comment]
Just created PR #4826 for this issue. Some of this questions already have been added, so I just updated missing ones.
