### ISSUE TITLE
Q35. What NFS option allows the root user to access NFS shares as the root user?

### ISSUE THREAD

**Issue by debugx** [Ebazhanov/linkedin-skill-assessments-quizzes#3729]
The mistake in the Q35. What NFS option allows the root user to access NFS shares as the root user?
The correct answer is no_root_squash

**Comment by debugx** [comment]
It's about linux-assessment.md

**Comment by 101br03k** [comment]
@debugx i have made a new pull request, could you check it to see if its allright (#3734)
also it also contains another issue fix so dont mind that one.

**Comment by 101br03k** [comment]
the issue is fixed in pull request #3734

**Comment by Ebazhanov** [comment]
Great job guys! Thank you @debugx, @101br03k
