### ISSUE TITLE
List of Failed Quizzes

### ISSUE THREAD

**Issue by chase-watts** [Ebazhanov/linkedin-skill-assessments-quizzes#3736]
I did a test this week to see how reliable the answers in this project are.

I used no previous knowledge and I didn't use any other sources.  If a question wasn't in your repository, I skipped it (let it timeout).

I passed 61 quizzes and either failed or didn't take 32 quizzes.  I did not take any quizzes that weren't in your repository.

Here's a list of the quizzes that I failed or didn't take:

> Accounting
> Adobe Animate
> Adobe InDesign
> Adobe Lightroom
> Adobe Photoshop
> Adobe Premiere Pro
> Adobe XD
> After Effects
> ArcGIS Products
> AutoCAD
> Autodesk Fusion 360
> Autodesk Inventor
> Autodesk Maya
> Avid Media Composer
> Django
> Dreamweaver
> Eclipse
> Final Cut Pro
> iMovie
> Keynote
> Logic Pro
> Microsoft Power Automate
> Microsoft Project
> Pro Tools
> QuickBooks
> Revit
> Rhino 3D
> Scala
> SketchUp
> SOLIDWORKS
> Unity
> Visual Basic for Applications (VBA)

Hopefully someone finds this useful and it can help improve the repository.

**Comment by Ebazhanov** [comment]
@chase-watts thanks for the feedback, fyi I have added the column `Pass/Failed` based on your info
