### ISSUE TITLE
Microsoft Outlook (Missing Answers)

### ISSUE THREAD

**Issue by moahnass** [Ebazhanov/linkedin-skill-assessments-quizzes#3756]
These are questions that have NO selected answers in the Microsoft Outlook quiz.
- Q5
- Q10
- Q13
- Q17
- Q18
- Q20
- Q40
- Q41
- Q44
- Q45
- Q51
- Q51
- Q56
- Q62
- Q67
- Q68
- Q69
- Q70
- Q72
- Q73

**Comment by IanoNjuguna** [comment]
How can I tackle this?
