### ISSUE TITLE
Microsoft Word (Missing Answers)

### ISSUE THREAD

**Issue by moahnass** [Ebazhanov/linkedin-skill-assessments-quizzes#3757]
These questions have NO answers in the Microsoft Word quiz.
- Q83
- Q85
- Q86
- Q87
- Q88
- Q89
- Q90

**Comment by 101br03k** [comment]
Q85. all of these answers
Q87.  in red
Q88.  Insert alt text.
Q89. Insert a section break at the end of the first page.

**Comment by Ebazhanov** [comment]
thank you @101br03k for updates
