### ISSUE TITLE
MongoDB (Missing Answer)

### ISSUE THREAD

**Issue by moahnass** [Ebazhanov/linkedin-skill-assessments-quizzes#3758]
Q73 is void of a selected answer in the MongoDB quiz.

**Comment by Kaushik-Iyer** [comment]
I think the answer is db.stats(). Should I try to solve this issue now?

**Comment by moahnass** [comment]
I'm pretty sure db.stats() is the correct response.

**Comment by Ebazhanov** [comment]
thank you all for this improvements, well done! 💪
