### ISSUE TITLE
Jquery- Missing 

### ISSUE THREAD

**Issue by hammrxu** [Ebazhanov/linkedin-skill-assessments-quizzes#3764]
When you use custom Jquery selection extensions, such as :animated, on a page with lots of DOM elements, you can run into performance issues. What is the best practice for managing those issues?

> A Select $(document.body) first, then use .filter with the custom extension.
> B Use the custom extension with .has().
> C Start with the custom extension, then use .find with a selector that exists in CSS to limit the selection.
> D Start with a selection that exists in CSS, then refine the selection using .filter() with the custom extension.
![f57b2c7f4dfb5c0aa4631be33849c21](https://user-images.githubusercontent.com/25573980/171537254-03f8a8da-09ad-445a-8fdf-d8f0c4d737ef.png)

**Comment by Ebazhanov** [comment]
thank you @hammrxu 👍  I have added this question!
