### ISSUE TITLE
Microsoft Excel - missing questions 2/2

### ISSUE THREAD

**Issue by hammrxu** [Ebazhanov/linkedin-skill-assessments-quizzes#3766]
![42b5624e2026ab4a7a0910ad1832135](https://user-images.githubusercontent.com/25573980/171542422-fb55ec39-00e3-4c87-b6c0-600abcfc2865.png)

**Comment by 101br03k** [comment]
it is indeed =$B$1*B4

**Comment by Ebazhanov** [comment]
Great job 💯 , thank you guys!
