### ISSUE TITLE
SharePoint

### ISSUE THREAD

**Issue by Ebazhanov** [Ebazhanov/linkedin-skill-assessments-quizzes#3781]
![SP-04](https://user-images.githubusercontent.com/13170022/171808657-26d49503-7583-4cd2-bd62-07556fc3cc74.png)
![SP-03](https://user-images.githubusercontent.com/13170022/171808670-d13eac11-f0f8-4c42-8b88-bdba34dce232.png)
![SP-02](https://user-images.githubusercontent.com/13170022/171808671-902e6616-9146-48fc-9d3f-9fc6e2d1f63e.png)
![SP-01](https://user-images.githubusercontent.com/13170022/171808675-f3d4a266-f79d-4eaa-9cf6-1abdacc6f521.png)

**Comment by auchynnikau** [comment]
Resolving issue in #4769
