### ISSUE TITLE
IT Operations

### ISSUE THREAD

**Issue by Ebazhanov** [Ebazhanov/linkedin-skill-assessments-quizzes#3782]
![IT_operations](https://user-images.githubusercontent.com/13170022/171809498-041dfa6f-2063-45b0-a90e-3015254afd13.png)

**Comment by 101br03k** [comment]
PCMCIA (also known as PC Card) has been replaced with expresscard and that has been replaced with Thunderbold and Thunderbold is for peripherals.
MCA has been replaced by PCI
ISA has been replaced by PCI
PCI has been replaced with PCIe
so PCIe is the answer and also most common used in pc's for gpu's, network cards, storage expansion, sound cards and many more

**Comment by Ebazhanov** [comment]
Thank you @101br03k, @lnugraha 👊
