### ISSUE TITLE
Java

### ISSUE THREAD

**Issue by R-Ayush777** [Ebazhanov/linkedin-skill-assessments-quizzes#3787]
**New Question** 

![image](https://user-images.githubusercontent.com/78534043/171981336-cafe0fa3-e390-4a15-9cbc-fb4a7f193dc2.png)

**Comment by Kaushik-Iyer** [comment]
I think the first option is the correct option

**Comment by muratcanabay** [comment]
Option B is the correct one. [Narrowing casting](https://www.w3schools.com/java/java_type_casting.asp)

**Comment by lnugraha** [comment]
This question has been posted in Java (Q.127) before.

**Comment by Ebazhanov** [comment]
Alright thank you all, question was successfully added! 💯
