### ISSUE TITLE
React Q55 Potentially wrong ?

### ISSUE THREAD

**Issue by HeIp** [Ebazhanov/linkedin-skill-assessments-quizzes#3790]
Question 55 seems wrong / Strange
For Recap :

Q55. You have added a style property to the h1 but there is an unexpected token error when it runs. How do you fix this?
```
const element = <h1 style={ backgroundColor: "blue" }>Hi</h1>;
const element = <h1 style="backgroundColor: "blue""}>Hi</h1>;
X- const element = <h1 style=>Hi</h1>;
const element = <h1 style={blue}>Hi</h1>;
const element = <h1 style="blue">Hi</h1>;
```

Where the third answer is being marked as correct ?

**Comment by HeIp** [comment]
Clarification : I just noticed the Github Pages deployment render is showing it wrongly

**Comment by Ebazhanov** [comment]
the second option looks good to me
`const element = <h1 style={{backgroundColor: "blue"}}>Hi</h1>;`
@HeIp do you still want to correct anything?

**Comment by HeIp** [comment]
The selection answer is correct, jus the github pages render displays it incorrectly

**Comment by Ebazhanov** [comment]
ok, got it
I think it is looks good now 
![image](https://user-images.githubusercontent.com/13170022/176991111-23be28fb-ff4b-4008-b734-3dbaa4f12112.png)

feel free to reopen this issue if something you find incorrect
