### ISSUE TITLE
Visual Basic

### ISSUE THREAD

**Issue by Ebazhanov** [Ebazhanov/linkedin-skill-assessments-quizzes#3792]
![image](https://user-images.githubusercontent.com/13170022/172055459-9992660f-cb14-46a2-83b9-4043cb1b471d.png)
![image](https://user-images.githubusercontent.com/13170022/172055466-08650b96-7ce4-42a8-8a5a-0f7973511c19.png)
![image](https://user-images.githubusercontent.com/13170022/172055471-b839bdbf-3d51-46dc-a767-1ce121908841.png)
![image](https://user-images.githubusercontent.com/13170022/172055477-0acded31-9371-48ea-b32c-264b36f871b6.png)
![image](https://user-images.githubusercontent.com/13170022/172055491-287c51c3-9487-41d7-8a5e-bed12a38dbec.png)

**Comment by parikhparth23** [comment]
i am working on it

**Comment by parikhparth23** [comment]
Fix: https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/pull/4729

@Ebazhanov please merge the PR.
