### ISSUE TITLE
PHP

### ISSUE THREAD

**Issue by Ebazhanov** [Ebazhanov/linkedin-skill-assessments-quizzes#3793]
![image](https://user-images.githubusercontent.com/13170022/172055532-dfd55987-91a7-4a23-bb2f-777532576c04.png)
![image](https://user-images.githubusercontent.com/13170022/172055555-61780894-1393-4b23-af89-14cd37829a74.png)
![image](https://user-images.githubusercontent.com/13170022/172055558-012de29f-54c7-436b-acf9-7ed7e7c5eaa8.png)

**Comment by Sync271** [comment]
Can you assign this to me?
