### ISSUE TITLE
New Question - Google Cloud Platform (GCP)

### ISSUE THREAD

**Issue by incapdns** [Ebazhanov/linkedin-skill-assessments-quizzes#3804]
![image](https://user-images.githubusercontent.com/40347728/172439107-63320b45-d91c-446a-9d55-b89ffd0ad3f4.png)

**Comment by 101br03k** [comment]
Cloud Storage and BigQuery

**Comment by Ebazhanov** [comment]
Thank you guys @101br03k, @lnugraha for your great input! 💪

**Comment by Ebazhanov** [comment]
Thank you @incapdns for raising this issue + screenshot
