### ISSUE TITLE
C++ New Question

### ISSUE THREAD

**Issue by Paper-SSheets** [Ebazhanov/linkedin-skill-assessments-quizzes#3816]
![C++MissingQuestion](https://user-images.githubusercontent.com/43944573/172988824-d4355a24-9068-4abb-adb8-12f7263ac6dc.png)

**Comment by bagewadi-akram** [comment]
Protected

**Comment by Ebazhanov** [comment]
Thanks you @lnugraha, @Paper-SSheets the question was successfully added
