### ISSUE TITLE
Git New Question

### ISSUE THREAD

**Issue by Rushijaviya** [Ebazhanov/linkedin-skill-assessments-quizzes#3836]
![image](https://user-images.githubusercontent.com/59735978/173662123-01897b59-d1c0-41d7-9b84-9d59464556e6.png)

**Comment by 101br03k** [comment]
when a commit fron one branch needs to be copied into another branch
[reference 1](https://www.atlassian.com/git/tutorials/cherry-pick)
[reference 2](https://git-scm.com/docs/git-cherry-pick)

**Comment by Nierowheezy** [comment]
- Cherry picking in Git means to choose a commit from one branch and apply it onto another

**Comment by Rushijaviya** [comment]
Thank you, @101br03k  and @Nierowheezy, for your input. The answer is added to the question. Refer to #3845

**Comment by Rushijaviya** [comment]
we can close this now.

**Comment by Ebazhanov** [comment]
thanks you guys! 🎉
