### ISSUE TITLE
Question 65 about android is unanswered

### ISSUE THREAD

**Issue by lucioaguiar** [Ebazhanov/linkedin-skill-assessments-quizzes#3865]
Question 65 about android is unanswered.

> **Q65. Which approach is not recommended for providing a useful offline state in your app?**
> a) caching data
> b) storing data locally
> c) queuing outbound requests to action when connectivity has been lost
> d) always notifying users that connectivity has been lost

I believe the answer is letter (c) "queuing outbound requests to action when connectivity has been lost". I believe that if the device is not connected or has lost the connection, it has no reason to mount a queue or make several attempts at requests, depending on how this is done, it can occupy an amount of RAM memory and have unnecessary CPU usage, the problem is already was detected that it is the lack of connection, then you must wait for the connection to be re-established to continue with the process. I would answer letter (c), but I hope someone who has more knowledge and experience can answer in a more informed way than I do. I'm just opening the discussion.

Letter (a) and (b) provide a useful offline state as the app can save data, allowing the user to be able to use the app even without a connection and then when the connection is resumed this data will be used to continue the process interrupted by lack of connection.

Letter (d) also provides a useful offline state, depending on the type of application it is necessary for it to display warnings informing that the device is not connected to the internet, so that the user tries to reconnect the device and continue with the process, remembering that these notices cannot disturb the user or annoy him with too many notifications in the “status bar and notification drawer”. Below are some apps that warn about the lack of connection.

![letra4](https://user-images.githubusercontent.com/70476123/174444565-c0f318ff-16fd-48cc-b4ef-d0518d871bb0.png)

**Comment by monkrus** [comment]
@lucioaguiar, thank you!

Wow, this is a doctorate degree-level answer.

Kindly update Q65 with your comments.

As for us, we are adding you to the list of contributors.
Thank you!

@all-contributors please add @lucioaguiar for code
