### ISSUE TITLE
Q1 potentially wrong [cybersecurity-quiz.md]

### ISSUE THREAD

**Issue by Enuma029** [Ebazhanov/linkedin-skill-assessments-quizzes#3875]
according to my understanding of the shared responsibility model (see https://kirkpatrickprice.com/blog/whos-responsible-cloud-security/ or https://rewind.com/wp-content/uploads/2021/03/RWD_Shared_Responsibility_Graphics_V0.01_Graph1.jpg) I think the correct answer to Q1 in cybersecurity-quiz.md should be SaaS. Please verify my hypothesis.

**Comment by 101br03k** [comment]
by just googleling the shared responsibility model I also think the correct answer should be SaaS

**Comment by yktsang01** [comment]
Agree the answer should be SaaS. The question is asking **most** responsibility for the cloud provider.

Using https://rewind.com/wp-content/uploads/2021/03/RWD_Shared_Responsibility_Graphics_V0.01_Graph1.jpg as the reference, the major difference is who control/provide the "application". Under PaaS, the cloud consumer provides the application. Under SaaS the cloud service provider provides the application.

**Comment by monkrus** [comment]
@Enuma029, @yktsang01 agreed! Thank you for your contribution!
@all-contributors please add @Enuma029  for code.

**Comment by monkrus** [comment]
@all-contributors please add @yktsang01 for code
