### ISSUE TITLE
Autodesk Maya Test Questions Add

### ISSUE THREAD

**Issue by pathu17** [Ebazhanov/linkedin-skill-assessments-quizzes#3908]
1. What type of geometry works best for an nCloth shape?
a. alembic cache
b. triangle mesh
c. NURBS
d. quadrilateral mesh

2. Which tool is designed to enable an artist to manually retopologize a mesh?
a. Append to Polygon
b. Create Polygon
c. Sculpt
d. Quad Draw

![Screenshot (48)](https://user-images.githubusercontent.com/90762536/175879133-23a3fb27-dc2d-4546-ace5-699628997267.png)
![Screenshot (49)](https://user-images.githubusercontent.com/90762536/175879155-f7c2810b-205e-434d-ad39-dffe8b6895f9.png)
![Screenshot (50)](https://user-images.githubusercontent.com/90762536/175879180-43b1d236-ab19-4e89-b633-c0d76bbefdd8.png)
![Screenshot (55)](https://user-images.githubusercontent.com/90762536/175879301-479b4b86-ab6d-468e-8a0e-f3524b56b367.png)

![Screenshot (51)](https://user-images.githubusercontent.com/90762536/175879205-ded8bd31-a594-4448-8563-d6d87040fa08.png)
![Screenshot (52)](https://user-images.githubusercontent.com/90762536/175879222-9b6334f8-6b4e-4eb3-a2ab-0c80ae9ff940.png)
![Screenshot (53)](https://user-images.githubusercontent.com/90762536/175879234-a0c32633-e8a2-4e5f-9b28-bd08dc221053.png)
![Screenshot (54)](https://user-images.githubusercontent.com/90762536/175879282-e3d9a856-1747-4b7e-aeba-486872da373d.png)

![Screenshot (45)](https://user-images.githubusercontent.com/90762536/175879359-9f6fbf6d-1b94-4b5d-8faa-c5ab983b3819.png)
![Screenshot (46)](https://user-images.githubusercontent.com/90762536/175879370-e988af21-0545-4419-8192-4daf1d3cfe18.png)
![Screenshot (44)](https://user-images.githubusercontent.com/90762536/175879348-c79e6ff7-bed3-4b4d-b987-8b027e38b8d1.png)
![Screenshot (56)](https://user-images.githubusercontent.com/90762536/175879313-b18f4c12-486d-4eeb-8c58-a4c593ea558c.png)

![Screenshot (47)](https://user-images.githubusercontent.com/90762536/175879416-34424bb4-a1be-4c8b-b28a-d2dcd268f7f4.png)

**Comment by monkrus** [comment]
@pathu17 Please create a pull request in order to  add your questions to the repo [https://opensource.com/article/19/7/create-pull-request-github](url)

**Comment by Demoncyber1** [comment]
where is that answer questions?
