### ISSUE TITLE
New Java Question

### ISSUE THREAD

**Issue by jasminappleby** [Ebazhanov/linkedin-skill-assessments-quizzes#3915]
I ran into the following question when taking the Java Quiz today. 

Which data structure would you choose to associate the amount of rainfall with each month?

- [ ] Vector
- [ ] LinkedList
- [ ] Map
- [ ] Queue

I could not see my results but I selected LinkedList, which I think was correct?

**Comment by yktsang01** [comment]
Given the answers, I will choose Map because map is a key/value pair without creating new classes/objects. So can store the rainfall per month like 
`
Map<java.time.Month, Double> 
`
The other options will most likely need some new class to be meaningful
```
public class Rainfall {
private java.time.Month month;
private double rainfall;
} 
Vector<Rainfall>
LinkedList<Rainfall>
Queue<Rainfall>
```

**Comment by 201B153** [comment]
is this question added or not??
