### ISSUE TITLE
New Eclipse Questions

### ISSUE THREAD

**Issue by jasminappleby** [Ebazhanov/linkedin-skill-assessments-quizzes#3916]
Here are some new Eclipse questions I had noticed were not documented. I am unsure on the correct answers for these questions. Someone please review these and advise on the correct ones so they can be documented. 

</br></br>

How do you access the **Generate Getters and Setters** dialog, which allows the generation getter and setter methods for fields in the current type to be generated? 

- [ ] Use a custom key binding assigned to the command.
- [ ] Right-click the editor containing the file's source code and select **Source > Generate Getters and Setters**.
- [ ] all of these answers
- [ ] Select **Source > Generate Getters and Setters** from the menu bar.

</br></br>

You want to use Bugzilla for managing tasks. What is a prerequisite? 

- [ ] Install the Bugzilla plug-in.
- [ ] Add Bugzilla as a task repository.
- [ ] Select **Bugzilla** on the list of repositories in the **New Task** window.
- [ ] Create a new local task in the **Task List**.

<br/></br>

After opening a code file, you notice some of the syntax coloring is missing. What is the most likely problem? 

- [ ] The code is in a language that is too new for Eclipse to support.
- [ ] The perspective you are using is out of date.
- [ ] The code has the wrong file delimiters. 
- [ ] The code has an error.

</br></br>

What is *not* a method stub that Eclipse will create for you in the **New JUnit Test Case** window?

- [ ] setUp()
- [ ] tearDown()
- [ ] setUpClass()
- [ ] tearDownAfterClass()

</br></br>

How can you configure Content Assist to propose static members when the corresponding import statement is missing? 

- [ ] Click **Java > Editor > Content Assist > Missing Imports**.
- [ ] Click **Java > Editor > Content Assist > Favorites**.
- [ ] Click **Java > Editor > Content Assist > Advanced**.
- [ ] Click **Java > Editor > Content Assist**.

**Comment by monkrus** [comment]
@jasminappleby thank you! Please remember you can add unanswered questions to the repository, so someone can work on the later on. We then add you to the list of contributors.  
Thank you!
