### ISSUE TITLE
Microsoft Azure New Question and Undocumented Answer

### ISSUE THREAD

**Issue by jasminappleby** [Ebazhanov/linkedin-skill-assessments-quizzes#3917]
I have discovered one undocumented question from the Microsoft Azure assessment.

</br></br>

You have a set of SQL databases used with various PaaS applications with predictable usage patterns. You are planning to move these databases to Azure SQL and need to choose the right deployment option. Your priorities are minimizing costs, and having the ability to assign CPU and storage resources to individual database. Which option should you choose?

- [ ] SQL Managed Instance
- [ ] Azure SQL elastic pool
- [ ] SQL on Azure VMs
- [ ] Azure SQL Database

I chose Azure SQL Database, not sure if it is correct. 

</br></br>

Also Question number 54 does not have an answer correlated to it. I chose Event Hub for this question when taking the test, but again, I have no confirmation this is correct.

**Comment by MakendranG** [comment]
Hi @Ebazhanov 

I am interested in this issue. Can you plz assign me?

**Comment by MakendranG** [comment]
Hi @Ebazhanov

I have worked on this issue and raised a PR#https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/pull/4451

Kindly merge it.
