### ISSUE TITLE
HTML: weird answer

### ISSUE THREAD

**Issue by jpleboeuf** [Ebazhanov/linkedin-skill-assessments-quizzes#3924]
Hello,

here is a weird answer to Q91 I encountered preparing for the "HTML" quiz:

To the question "Which choice will produce the spanish word canción?", the correct answer checked is `canci&oacuten`, whereas it is not a valid HTML entity, since the semicolon is missing.
I think `canción` would pass since extended character sets are well supported by browsers nowadays.
Yet, it could be a typo and the semicolon is just missing, or... could this be a trap?

![Could this be a trap?](https://media2.giphy.com/media/l2YWhOEwfSAnJNJEQ/giphy.gif)

Any idea?

Pings: nobody.

Cheers,
and thanks again for this project!

**Comment by yktsang01** [comment]
No it's not a weird answer hence not a trap. In fact with or without the semicolon (;) makes no difference 
Do note the "o" is after the & => canción
If the "o" is before the & => cancio´n

https://www.w3schools.com/html/tryit.asp?filename=tryhtml_ent_o769 
FYI `&acute;` and same as `&#769;`

**Comment by jpleboeuf** [comment]
According to "[Why do HTML entity names with dec < 255 not require semicolon?](https://stackoverflow.com/questions/18689230/why-do-html-entity-names-with-dec-255-not-require-semicolon)", that an HTML entity works without semicolon is up to the browser's implementation, and should raise a parse error according to the specification.

From what I understand, since HTML5 supports UTF-8, `canción` should work in all browser supporting HTML5, whereas `canci&oacuten` should work only on those lax on the parsing.
