### ISSUE TITLE
Microsoft Power BI

### ISSUE THREAD

**Issue by Ebazhanov** [Ebazhanov/linkedin-skill-assessments-quizzes#3941]
![image](https://user-images.githubusercontent.com/13170022/177254473-44831985-da9b-4fb6-ab72-161f290bf242.png)
![image](https://user-images.githubusercontent.com/13170022/177254501-bb18ae89-4267-4ac0-ae7c-ab1231c08fba.png)

**Comment by Just2Deep** [comment]
i have created a PR for this, can you please check

**Comment by Ebazhanov** [comment]
@Just2Deep thanks for your contribution!
