### ISSUE TITLE
PHP New question

### ISSUE THREAD

**Issue by janjitsu** [Ebazhanov/linkedin-skill-assessments-quizzes#3952]
![Screenshot from 2022-07-06 18-32-09](https://user-images.githubusercontent.com/1727447/177623017-af008541-883c-4d3c-b1ea-551b40b316d5.png)

**Comment by janjitsu** [comment]
https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/pull/3953

**Comment by Ebazhanov** [comment]
thanks merged
