### ISSUE TITLE
Reading through to find a Question isnt easy

### ISSUE THREAD

**Issue by potato-Js** [Ebazhanov/linkedin-skill-assessments-quizzes#3957]
and pasting in other programs to search for questions is difficult to read because of the formatting and 
no text files, i suggest we start making text file copies of them to make things easier or a program to make searching for questions easier
``

**Comment by 101br03k** [comment]
you can copy the question and paste it in the search funcion (ctrl f) and find your question. 

> difficult to read because of the formatting

also every page has a source page and a clean one, scroll down to where the readme start and find the clean pages

**Comment by potato-Js** [comment]
thanks, i got it but i dont think theres a clean one, theres a only an md file, which if you copy the raw contents it not helpful and if you open the excuted md aka the formatted one , it 
<img width="441" alt="image" src="https://user-images.githubusercontent.com/103060805/178086902-9ad6e522-dc4f-46ae-822c-3f8cd26c0166.png">
also not helpful but i found a better one, the heading filter, it the 3 line and since the questions are headings you can easily search through the questions
