### ISSUE TITLE
AWS

### ISSUE THREAD

**Issue by Ebazhanov** [Ebazhanov/linkedin-skill-assessments-quizzes#3970]
![image](https://user-images.githubusercontent.com/13170022/178097230-d266e91f-b3cb-491a-99fb-29f72b14f1b5.png)

**Comment by 101br03k** [comment]
please close, same as AWS #3967

**Comment by Ebazhanov** [comment]
oh, here is the correct one, thanks @101br03k 
![image](https://user-images.githubusercontent.com/13170022/178100069-e3a08f8a-3bce-4f51-bc25-63a47f304a5f.png)

**Comment by Ebazhanov** [comment]
ooo yes it is the same closing now, 👍

**Comment by ckullo** [comment]
> oh, here is the correct one, thanks @101br03k ![image](https://user-images.githubusercontent.com/13170022/178100069-e3a08f8a-3bce-4f51-bc25-63a47f304a5f.png)


the answer is **amplify configure**.
here is the reference [https://docs.amplify.aws/cli/start/install/#option-2-follow-the-instructions](url)
