### ISSUE TITLE
[Cyber security] Unfortunately, you didn’t pass.

### ISSUE THREAD

**Issue by mohamedebrahim96** [Ebazhanov/linkedin-skill-assessments-quizzes#4032]
I made it exactly like that readme file.
https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/main/cybersecurity/cybersecurity-quiz.md

but the answers were wrong unfortunately

<img width="1162" alt="Screen Shot 2022-07-19 at 2 48 48 PM" src="https://user-images.githubusercontent.com/16405013/179733349-e6a2c648-5d2f-451f-a162-811a25b9d751.png">

**Comment by monkrus** [comment]
HI @mohamedebrahim96, very sorry to hear that.

We believe in good will of each contributor, and, as you understand, cannot verify each segment of the repository.
However, we will create a separate issue to verify the content of the Cyber security part of the quiz.

Thank you for bringing that to our attention!

**Comment by Ebazhanov** [comment]
@monkrus @mohamedebrahim96 fyi going to create related column to notify users that this quiz needs updating
