### ISSUE TITLE
Keynote assessment

### ISSUE THREAD

**Issue by Ebazhanov** [Ebazhanov/linkedin-skill-assessments-quizzes#4040]
![image](https://user-images.githubusercontent.com/13170022/179968485-64018287-c953-4731-900d-0f9f3aa0b297.png)
![image](https://user-images.githubusercontent.com/13170022/179968526-61952a27-cfe7-4a19-b3e6-8a6e05855700.png)
![image](https://user-images.githubusercontent.com/13170022/179968555-354ae143-9a2f-4ade-b765-ebff64d4cd6a.png)
![image](https://user-images.githubusercontent.com/13170022/179968583-8bc32c42-1962-45bf-a514-7d647ff65ebf.png)
![image](https://user-images.githubusercontent.com/13170022/179968618-24435beb-5d63-4764-8c9a-ccd5a4ad2f2b.png)
![image](https://user-images.githubusercontent.com/13170022/179968655-9dc24a48-4d63-4089-9fae-d14b6fc39da2.png)
![image](https://user-images.githubusercontent.com/13170022/179968683-b87b16bc-2716-4c51-b17a-9e69899f5a43.png)
![image](https://user-images.githubusercontent.com/13170022/179968722-cf82424f-ba71-4249-b7f4-867fedf6043b.png)
![image](https://user-images.githubusercontent.com/13170022/179968735-8c2192a3-496a-4b32-83a0-842287fa7466.png)
![image](https://user-images.githubusercontent.com/13170022/179968867-f17f1de7-7515-4da3-b27e-c41187ad41e9.png)
![image](https://user-images.githubusercontent.com/13170022/179968946-4b17448a-35b3-4545-8223-4a6c631e8b91.png)
![image](https://user-images.githubusercontent.com/13170022/179969064-02cf6a67-84d3-4f2f-9564-489de3958397.png)
![image](https://user-images.githubusercontent.com/13170022/179969083-a4ecbb0a-f7c6-40e4-ab63-46d185c87684.png)
![image](https://user-images.githubusercontent.com/13170022/179969119-2aa1ae6d-5949-4797-ad22-30a89f27cb48.png)

**Comment by auchynnikau** [comment]
Resolving issue in #4771 PR
