### ISSUE TITLE
Does Javascript Q92 has two correct answers?

### ISSUE THREAD

**Issue by oVerde** [Ebazhanov/linkedin-skill-assessments-quizzes#4041]
> ```
> let animals = ['jaguar', 'eagle'];
> //Missing Line
> console.log(animals.pop()); //Prints jaguar
> ```
> 
> - [ ] animals.filter(e => e === "jaguar");
> - [x] animals.reverse();
> - [ ] animals.shift();
> - [x] animals.pop();
> 

Am I missing something?

**Comment by Just2Deep** [comment]
@oVerde  yes, both are right.

**Comment by Ebazhanov** [comment]
Guys I would suggest we add comment under the question inside *.md file and close this issue

**Comment by monkrus** [comment]
Updated the repository, thank you for bringing this up.
