### ISSUE TITLE
Failed after taking JSON exam??

### ISSUE THREAD

**Issue by chaudharynabin6** [Ebazhanov/linkedin-skill-assessments-quizzes#4052]
i cannot even get pass mark after taking JSON exam??

**Comment by monkrus** [comment]
Hi @chaudharynabin6 ,  really sorry to hear that.

We believe in good will of each contributor, and, as you understand, cannot verify each segment of the repository.
However, we will create a separate issue to verify the content of the JSON part of the quiz.

Thank you for bringing that to our attention!

**Comment by Ebazhanov** [comment]
@monkrus @chaudharynabin6 fyi going to create related column to notify users that this quiz needs updating
