### ISSUE TITLE
Missing Question in Excel Assessment

### ISSUE THREAD

**Issue by psaezt** [Ebazhanov/linkedin-skill-assessments-quizzes#4079]
You realize that you named a table Quraters and you want to correct it to be Quarters. How could you accomplish this?

> On the **Table Design** tab (Windows) or **Table** tab (Mac), rename the table in the **Table Name** box.
> 
> Copy the table to another worksheet and rename it Quarters.
> 
> Right click in the table and select **Rename**.
> 
> On the **Table Design** tab (Windows) or **Table** tab (Mac), click **Name Manager**.

**Comment by Just2Deep** [comment]
Created a PR for this question

**Comment by Ebazhanov** [comment]
Thank you @psaezt, @Just2Deep 🤝
