### ISSUE TITLE
how can deploy this quizes in ubuntu 20?

### ISSUE THREAD

**Issue by johnfelipe** [Ebazhanov/linkedin-skill-assessments-quizzes#4088]

**Comment by johnfelipe** [comment]
Pls help me for deploy this quizzes in Ubuntu

**Comment by johnfelipe** [comment]
anyone?

**Comment by Ebazhanov** [comment]
let's chat in slack or discord, I hope we will find the solution!

**Comment by Ebazhanov** [comment]
as discussed, the question is related to different repo https://github.com/linkedin-faq/linkdin-quizzes/issues
