### ISSUE TITLE
Answer missing for Q74 in Microsoft Powerpoint

### ISSUE THREAD

**Issue by Just2Deep** [Ebazhanov/linkedin-skill-assessments-quizzes#4105]
![image](https://user-images.githubusercontent.com/48485675/181808333-032137b9-499c-4151-9bfd-89ace9519fb5.png)

**Comment by Hosein1358** [comment]
I suppose it should be the second choice: Compress all the pictures...

**Comment by MakendranG** [comment]
Hi @Ebazhanov 

I am interested in this issue. Can you plz assign me?

**Comment by MakendranG** [comment]
Hi @Ebazhanov

I have worked on this issue and raised a PR https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/pull/4635

Kindly merge it.
