### ISSUE TITLE
accounting assessment

### ISSUE THREAD

**Issue by GameOnGoddess** [Ebazhanov/linkedin-skill-assessments-quizzes#4142]
Added additional questions ss on Word file *** Hope this helps*

**Comment by GameOnGoddess** [comment]
[accounting assessment questions.docx](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/files/9243434/accounting.assessment.questions.docx)

let me know how i can help ***

**Comment by monkrus** [comment]
@GameOnGoddess Please add new questions to the repository by creating a pull request. 
Just in case, some info is here [https://opensource.com/article/19/7/create-pull-request-github](url)
Thanks!
