### ISSUE TITLE
Agile - Additional Questions

### ISSUE THREAD

**Issue by jefferies917** [Ebazhanov/linkedin-skill-assessments-quizzes#4144]
![New Question 1](https://user-images.githubusercontent.com/52199503/182418274-f2915a7a-4d60-476a-af4d-4ea7e57d8ad5.png)
![New Question 2](https://user-images.githubusercontent.com/52199503/182418311-7758bea7-f0f1-416a-a37c-9198319e8674.png)

**Comment by monkrus** [comment]
@jefferies917 Please create a pull request so we can add your questions to the repo.[https://opensource.com/article/19/7/create-pull-request-github](url)
