### ISSUE TITLE
Microsoft Power Point

### ISSUE THREAD

**Issue by Ebazhanov** [Ebazhanov/linkedin-skill-assessments-quizzes#4151]
![image](https://user-images.githubusercontent.com/13170022/182698874-89deefa9-59e2-4c90-bc37-e9a69cac03ef.png)
![image](https://user-images.githubusercontent.com/13170022/183008050-2d02a92a-7922-4fc6-9e3f-fc35427fdf1d.png)

**Comment by 101br03k** [comment]
@Ebazhanov 
Could you close this one please.

**Comment by Ebazhanov** [comment]
sure @101br03k thanks 👍
