### ISSUE TITLE
REST API Q47 might be wrong

### ISSUE THREAD

**Issue by mssayari** [Ebazhanov/linkedin-skill-assessments-quizzes#4190]
The question is 
**When a user attempts to access a record that is not their own, which HTTP response code is the most appropriate?**

Since the question mentioned **to access a record that is not their own**, when we deal with a record, it usually means we authenticated and the client identity is known to the server.

By considering below definitions shouldn't be  403?

[401 Unauthorized](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401)

> Although the HTTP standard specifies "unauthorized", semantically this response means "unauthenticated". That is, the client must authenticate itself to get the requested response.
    
[403 Forbidden](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403)

> The client does not have access rights to the content; that is, it is unauthorized, so the server is refusing to give the requested resource. Unlike 401 Unauthorized, the client's identity is known to the server.

**Comment by akalatksy** [comment]
Fully agree with  @mssayari

**Comment by masoudk1990** [comment]
Agreed. It obviously needs to get fixed.
