### ISSUE TITLE
Missing Rust questions

### ISSUE THREAD

**Issue by Ultracoil** [Ebazhanov/linkedin-skill-assessments-quizzes#4240]
![image](https://user-images.githubusercontent.com/111402760/185016023-e10c2df7-45e9-4579-bdd0-be6b03a2e2fc.png)
![image](https://user-images.githubusercontent.com/111402760/185016027-a8204efe-6b09-4b9d-8d58-9827e8585e38.png)
![image](https://user-images.githubusercontent.com/111402760/185016035-cf7f9b99-a8d5-47ec-b0cd-74337d935101.png)
![image](https://user-images.githubusercontent.com/111402760/185016047-ec1f0ce1-fddc-4870-a5ff-321db8000141.png)
![image](https://user-images.githubusercontent.com/111402760/185016058-19f416f1-ad80-42f3-b887-c8b696f77deb.png)
![image](https://user-images.githubusercontent.com/111402760/185016063-7927a880-3d3f-4c55-bbfb-b444ff5c5843.png)

I came across these questions which are not in this repo yet. Selected answers are not necesserily correct. I assume there are more questions which are not in this repo yet.

**Comment by 201B153** [comment]
Can I update the rust.md

**Comment by Ebazhanov** [comment]
closing thank you guys! 👍 
@Ultracoil @201B153
