### ISSUE TITLE
Amazon Web Services missing question

### ISSUE THREAD

**Issue by Muramas** [Ebazhanov/linkedin-skill-assessments-quizzes#4249]
![image](https://user-images.githubusercontent.com/2413847/185153596-6ab19f02-af2f-490c-8266-51148a9a4ecc.png)

**Comment by MakendranG** [comment]
Hi @Ebazhanov

I am interested in this issue. Can you plz assign me?

**Comment by MakendranG** [comment]
Hi @Ebazhanov 

I have worked on this issue and raised a PR https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/pull/4543

Kindly merge it.
