### ISSUE TITLE
Missing questions in Microsoft Excel

### ISSUE THREAD

**Issue by juanm55** [Ebazhanov/linkedin-skill-assessments-quizzes#4258]
If you double-click precisely on the line between the 2 columns the column gets resized to best fit the information inside all of the column
![image](https://user-images.githubusercontent.com/901558/185531985-09825d39-9f6b-4493-9c56-19e91cd2d30b.png)

They are both customizable, that's it
![image](https://user-images.githubusercontent.com/901558/185532018-1e177130-4dc3-40df-8de1-694eeda0c17b.png)

**Comment by 101br03k** [comment]
both given answers in the pictures are correct.

**Comment by Just2Deep** [comment]
I have added these questions to code base and created a PR. 
could you check @Ebazhanov

**Comment by SoyGoodPeople** [comment]
This is missing to 
<img width="849" alt="image" src="https://user-images.githubusercontent.com/2055407/185755494-0636ecf9-cf94-4b26-ab6b-50affde3abf0.png">

**Comment by Just2Deep** [comment]
Hi @Ebazhanov This is already added, you can close this.
