### ISSUE TITLE
Git new question

### ISSUE THREAD

**Issue by lcsvcn** [Ebazhanov/linkedin-skill-assessments-quizzes#4294]
![image](https://user-images.githubusercontent.com/6011385/186736002-ce439d1b-98b7-4d92-8290-2e5a679b3b8b.png)

**Comment by lcsvcn** [comment]
![image](https://user-images.githubusercontent.com/6011385/186736486-81126376-e2aa-4a5f-a4cf-79ce97f6ea8e.png)

**Comment by lcsvcn** [comment]
![image](https://user-images.githubusercontent.com/6011385/186737203-71bea3f6-3c7f-4f4e-97cb-dfe205d2533e.png)

**Comment by lcsvcn** [comment]
![image](https://user-images.githubusercontent.com/6011385/186737864-dd83edd3-d433-43b5-8502-dd44170506c1.png)

**Comment by lcsvcn** [comment]
Also I think most of the question for GIT session are wrong.

**Comment by MakendranG** [comment]
Hi @Ebazhanov

I am interested in this issue. Can you plz assign me?

**Comment by MakendranG** [comment]
Hi @Ebazhanov

I have worked on this issue and raised a PR https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/pull/4542

Kindly merge it.
