### ISSUE TITLE
Kotlin question update

### ISSUE THREAD

**Issue by lcsvcn** [Ebazhanov/linkedin-skill-assessments-quizzes#4295]
![image](https://user-images.githubusercontent.com/6011385/186739975-0f7f496e-8c53-40f0-b5f4-7d12743c7e93.png)

**Comment by lcsvcn** [comment]
![image](https://user-images.githubusercontent.com/6011385/186740487-f7c7f5ab-4024-4392-acae-736bf503bda3.png)

**Comment by auchynnikau** [comment]
This questions are already exist in `kotlin-quiz.md`. Number of questions: Q66 and Q80. We can close an issue.
