### ISSUE TITLE
new Python question

### ISSUE THREAD

**Issue by lcsvcn** [Ebazhanov/linkedin-skill-assessments-quizzes#4296]
![image](https://user-images.githubusercontent.com/6011385/186741082-157b33e2-837a-44c9-a805-436648640b39.png)

**Comment by Rushijaviya** [comment]
This question is already there in the Python quiz section. 
![image](https://user-images.githubusercontent.com/59735978/186969602-01c03425-01be-4a4e-baf6-94221dd2da01.png)

**Comment by Atharvk7** [comment]
The Answer is Median

**Comment by jdelucca** [comment]
Nothing needs to be done here please close the issue.

**Comment by auchynnikau** [comment]
@Ebazhanov issue can be closed
