### ISSUE TITLE
CSS Text Q93 - (I can't branch or make a pull request)

### ISSUE THREAD

**Issue by paulboundy99** [Ebazhanov/linkedin-skill-assessments-quizzes#4322]
Hi. 
I don't seem to be able to make a pull request or create a branch, but I'm happy to do so if I can.

I looked into this question and answer.

#### Q93. Which choice is _not a valid_ transition?

- [x] `transition: margin 1000ms ease-in-out;`
- [ ] `transition: color 1.3s ease-in;`
- [ ] `transition: position 400ms linear;`
- [ ] `transition: opacity 1s ease-in;`

I couldn't pick an invalid choice, they all looked ok to me so I did some research.

W3Schools indicates position is not animatable:
https://www.w3schools.com/cssref/pr_class_position.asp
W3Schools doesn't list position as animatable.
https://www.w3schools.com/cssref/css_animatable.asp

MDN says does not list position as an attribute that is animatable. 
https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_animated_properties

The formal definition of the position attribute on MDN indicates it is Discrete, but I don't know what that means in this context.
https://developer.mozilla.org/en-US/docs/Web/CSS/position#formal_definition

I'd be inclined to say the correct answer, ie which is not a valid transition, is the third option:
- [x] `transition: position 400ms linear;`

I think the css application of transition and animation are the same at least as far as this question goes.

@Ebazhanov

**Comment by Ebazhanov** [comment]
@paulboundy99 thanks a lot for deep dive in this question, I have correct answer and add your reference links. Check it out here https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/main/css/css-quiz.md#q93-which-choice-is-not-a-valid-transition
