### ISSUE TITLE
Accounting

### ISSUE THREAD

**Issue by MrCruzx** [Ebazhanov/linkedin-skill-assessments-quizzes#4323]
HI, I tried the accounting one and it had different questions on it. Please advise, thank you for all your hard work, it is very appreciated.

**Comment by Ebazhanov** [comment]
Hello, @MrCruzx you are talking about question which you did not found in this file https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/main/accounting/accounting-quiz.md if it is like so just create PR with new question or post screenshot here.
