### ISSUE TITLE
New MySQL Question

### ISSUE THREAD

**Issue by Westly** [Ebazhanov/linkedin-skill-assessments-quizzes#4347]
![linkedin_new_mysql_question](https://user-images.githubusercontent.com/3219403/188340287-4f0ab81d-7911-41e4-a121-b48ab7b06bd9.png)

**Comment by smashcoder** [comment]
Option 2 : `JSON columns cannot be indexed directly`

Reference : https://www.compose.com/articles/mysql-for-your-json/#:~:text=The%20drawback%3F,in%20a%20full%20table%20scan.
