### ISSUE TITLE
New Microsoft Word Questions

### ISSUE THREAD

**Issue by valerka-php** [Ebazhanov/linkedin-skill-assessments-quizzes#4349]
![word-questions](https://user-images.githubusercontent.com/81385130/188405571-a14b4545-918d-48f4-ab61-a74ba006adf4.png)

a few new questions =)

**Comment by skarthik7** [comment]
1) select
2) strikethrough

**Comment by MakendranG** [comment]
Hi @Ebazhanov 

I am interested in this issue. Can you plz assign me?

**Comment by MakendranG** [comment]
Hi @Ebazhanov

I have worked on this issue and raised a PR #https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/pull/4540

Kindly merge it.
