### ISSUE TITLE
New CSS Questions

### ISSUE THREAD

**Issue by valerka-php** [Ebazhanov/linkedin-skill-assessments-quizzes#4355]
![css-questions](https://user-images.githubusercontent.com/81385130/188706141-d55dd86b-ee23-4d47-b86d-9b0621516d57.png)

a few new questions

**Comment by smashcoder** [comment]
For the First Question The Answer is second option :
`padding: 10px 10px 0px 0px;`

Explanation : 
Syntax of Padding are in the following ways :
 1] Four Values :=> padding: top right bottom left
 2] Three Values :=> padding: top (right & left) bottom
 3] Two Values :=> padding: (top & bottom) (right & left)

**Comment by alisha-takkar** [comment]
#4469
