### ISSUE TITLE
MySQL - Q38. What cannot have a trigger associated with it?

### ISSUE THREAD

**Issue by rafaeldjsm** [Ebazhanov/linkedin-skill-assessments-quizzes#4372]
ON : https://dev.mysql.com/doc/refman/5.7/en/create-trigger.html 

In this reference we can see that:  "You cannot associate a trigger with a TEMPORARY table or a view."

So I think the correct answer should be "TEMPORARY table"

**Comment by Ebazhanov** [comment]
https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/pull/4629
