### ISSUE TITLE
Accounting New Questions Not Included

### ISSUE THREAD

**Issue by Pascal-81** [Ebazhanov/linkedin-skill-assessments-quizzes#4374]
I have taken the accounting test and noticed that LinkedIn added more questions and they are not included in the updated accounting assessment section here. I still have only one try before having to wait for 3 months to retake the test again, and, unfortunately, I didn't write the new questions. is there a way that someone can add/update the accounting section to reflect the current quiz questions?
Thank you in advance

**Comment by auchynnikau** [comment]
Resolving issue in #4770
