### ISSUE TITLE
New Python Question

### ISSUE THREAD

**Issue by morgandavidson** [Ebazhanov/linkedin-skill-assessments-quizzes#4396]
![Capture d’écran de 2022-09-16 17-37-01](https://user-images.githubusercontent.com/44446741/190682056-a42f1c1e-470b-41fe-908c-790f2ad6aece.png)

**Comment by Ebazhanov** [comment]
@morgandavidson thanks for the new question it was added here https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/pull/4398/files
