### ISSUE TITLE
Maven

### ISSUE THREAD

**Issue by Ebazhanov** [Ebazhanov/linkedin-skill-assessments-quizzes#4405]
![image](https://user-images.githubusercontent.com/13170022/190898495-65a117dd-e228-4425-a070-d40fdeb1eef7.png)
![image](https://user-images.githubusercontent.com/13170022/190898508-8563218f-248b-435d-bb40-06ebc7a2999a.png)

**Comment by Avimathu** [comment]
May I take up this issue please?

**Comment by Ebazhanov** [comment]
@Avimathu i think it is already in codebase, you can take any other. Thanks
