### ISSUE TITLE
Agile Methodologies

### ISSUE THREAD

**Issue by Ebazhanov** [Ebazhanov/linkedin-skill-assessments-quizzes#4408]
![image](https://user-images.githubusercontent.com/13170022/190986970-bea90fc4-389b-49b1-a502-0c4675b39095.png)

**Comment by zghp** [comment]
Hi, do we need to reply to the question and then create a merge request? Not fully sure. And also, can we add translations to any of the quizzes?

**Comment by Ebazhanov** [comment]
> Hi, do we need to reply to the question and then create a merge request? Not fully sure. And also, can we add translations to any of the quizzes?

Hello, @zghp! 
- if this question is not exist in the https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/main/agile-methodologies/agile-methodologies-quiz.md
- yes sure you can add translation.
