### ISSUE TITLE
Front-end Development

### ISSUE THREAD

**Issue by Ebazhanov** [Ebazhanov/linkedin-skill-assessments-quizzes#4410]
![unknown](https://user-images.githubusercontent.com/13170022/191085040-905bb631-4ab6-4c65-91eb-ddbf3dbb74c1.png)

**Comment by evilgreen94** [comment]
in this case the correct answer is focus:visible 
![image](https://user-images.githubusercontent.com/98925322/191487836-41b4587c-76e5-4524-85b5-b2aa89f4b963.png)

**Comment by evilgreen94** [comment]
The answer is the second one, The :focus-visible pseudo-class applies while an element matches the [:focus] pseudo-class and the UA (User Agent) determines via heuristics that the focus should be made evident on the element. (Many browsers show a "focus ring" by default in this case.)

**Comment by catcecilia** [comment]
I believe this issue has been resolved (Q83)

**Comment by Ebazhanov** [comment]
Thanks a lot guys! :bouquet: closing
