### ISSUE TITLE
Adobe XD

### ISSUE THREAD

**Issue by Ebazhanov** [Ebazhanov/linkedin-skill-assessments-quizzes#4422]
![Q10](https://user-images.githubusercontent.com/13170022/191463800-13348d47-e0f5-46c1-abf0-cb6400a9eaf6.png)
![Q9](https://user-images.githubusercontent.com/13170022/191463810-e8be39d5-5335-49b2-8c78-cf8f560133a5.png)
![Q7](https://user-images.githubusercontent.com/13170022/191463812-7d929c07-53b6-40b1-85b8-f227de3a6dda.png)
![Q4](https://user-images.githubusercontent.com/13170022/191463816-e7e62525-7427-495f-bcf3-3bb3e508538e.png)
![Q5](https://user-images.githubusercontent.com/13170022/191463819-83e5b514-f623-4d5c-80e7-d92275121a2e.png)

**Comment by keerthanak-tw** [comment]
Please check PR #4757

**Comment by auchynnikau** [comment]
All answers are added, we can close this issue.
