### ISSUE TITLE
Python - incorrect answer? 

### ISSUE THREAD

**Issue by mohamed-tayeh** [Ebazhanov/linkedin-skill-assessments-quizzes#4430]
![image](https://user-images.githubusercontent.com/35163331/191834781-cf5825d7-bc39-4bad-a73f-014e8929acd3.png)

Can use a break statement and the value being searched can be the first element of the list, given that it is non-empty.

**Comment by Sambhav250703** [comment]
can i contribute in this issue?

**Comment by mohamed-tayeh** [comment]
@Sambhav250703 I will be contributing it today!
