### ISSUE TITLE
Python Q54 (BST) Wrong Answer

### ISSUE THREAD

**Issue by mehhran** [Ebazhanov/linkedin-skill-assessments-quizzes#4475]
Question asks for a True statement. The marked answer states:

> For any given Node in a binary Search Tree, the child node to the left is less than the value of the given node and the child node to its right is greater than the given node.

Which is incorrect. 

By [definition ](https://en.wikipedia.org/wiki/Binary_search_tree) each node should be greater than **all nodes in it's left subtree** and less than **all ones in its right subtree**.

As an example, the below tree meets the conditions stated in the answer, but it's not a BST because a node in the 8's left subtree is greater than it (11 is greater than 8).
```
       8
    /     \
   5      10
 /   \
3    11
```

**Comment by 201B153** [comment]
yes, the answer. should be (c) i.e.
> The top node of the binary search tree would be an arbitrary number. All the nodes to the left of the top node need to be less than the top node's number, but they don't need to ordered in any particular way.

![image](https://user-images.githubusercontent.com/89572392/193111979-541a7c26-0d4b-4654-b26c-edc338c490e3.png)

**Comment by 201B153** [comment]
I think u got it wrong, 
> For any given Node in a binary Search Tree, the child node to the left is less than the value of the given node and the child node to its right is greater than the given node.
states that the left will have less value than the parent node; therefore 11 is not available to put in the left subtree
check [!reference](https://www.freecodecamp.org/news/binary-search-trees-bst-explained-with-examples/)

**Comment by mehhran** [comment]
@201B153 
Yes, in the above example, _based on the wrong statement_, 11 will not be considered while checking the root.

A correct statement would be something like this:

For each node, the values of its _left **descendent** nodes_ are less than the value of the current node, and the values of its _right **descendent** nodes_ are greater than that of the current node. ([reference](https://www.freecodecamp.org/news/binary-search-trees-bst-explained-with-examples/))

So, in our example, while checking the node with value 8, we **should** check all the left subtree, including 11.
For more explanation I recommend reading [this](https://afteracademy.com/blog/check-if-a-binary-tree-is-BST-or-not).

**Comment by Ebazhanov** [comment]
Thanks you guys for collaboration! 👍
