### ISSUE TITLE
AWS Lambda 2 New Questions Added

### ISSUE THREAD

**Issue by maheshdbabar9340** [Ebazhanov/linkedin-skill-assessments-quizzes#4481]
![1](https://user-images.githubusercontent.com/53929423/193183800-0257b4e3-45d5-41bb-86e8-69017417bd0d.png)
![2](https://user-images.githubusercontent.com/53929423/193183817-3f06fbd1-fa01-4e96-9151-66b53f092b91.png)

**Comment by 201B153** [comment]
question No.  47 and first are same! Adding only second question.
