### ISSUE TITLE
Python question:  x=18  if x > 10: if x > 15: print ('A')

### ISSUE THREAD

**Issue by Bart-Source** [Ebazhanov/linkedin-skill-assessments-quizzes#4486]
![x18 python question](https://user-images.githubusercontent.com/64977445/193271180-e351424b-08ac-4882-9ffc-afadaf182316.jpg)
I assume the answer is A

**Comment by rsk2** [comment]
Yup, pretty sure the answer is the 4th option (A)

**Comment by Atharvk7** [comment]
Answer is 4 (A)

**Comment by payal1206** [comment]
Hi, I can take this 
Ans is 4(A)

**Comment by Ebazhanov** [comment]
closing, the question is already implemented! 🎉
