### ISSUE TITLE
add answers for quiz: .NET Core 3 Quiz Medium Level

### ISSUE THREAD

**Issue by LemmyK6** [Ebazhanov/linkedin-skill-assessments-quizzes#4489]
Hey, I can't find answer for quiz labeled ".NET Core 3 Quiz Medium Level"
it contains 22 questions but I barely get 7 out 22

**Comment by auchynnikau** [comment]
Looks like you're trying to pass an external quiz which is not a part of the LinkedIn Skill Assessment. This repo contains only LinkedIn quiz info.

**Comment by AdityaShaw1** [comment]
pls assign me

**Comment by Ebazhanov** [comment]
I agree with @auchynnikau, we only accept questions from Linkedin assessment. Closing issue
