### ISSUE TITLE
Add a code of conduct root file

### ISSUE THREAD

**Issue by chemben17** [Ebazhanov/linkedin-skill-assessments-quizzes#4493]
This helps with the community attitude with towards the projects and fellow members.
It also helps to maintain order of the page.

**Comment by Ebazhanov** [comment]
agree with your idea, I am welcome to any PR's 
here something from the past https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/main/CONTRIBUTING.md

**Comment by chemben17** [comment]
<p> You can assign it to me. I'm on it already </p>

**Comment by chemben17** [comment]
I've done it. 
i've a pull request already.
You can review, accept and merge.
