### ISSUE TITLE
Answer missing for question no, 79

### ISSUE THREAD

**Issue by codespirit7** [Ebazhanov/linkedin-skill-assessments-quizzes#4557]
The answer is missing for question no. 79 in [linkedin-skill-assessments-quizzes](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes)/[microsoft-power-point](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/tree/main/microsoft-power-point)/microsoft-power-point-quiz.md

**Comment by emanuele-em** [comment]
the answer is [x] transparency @codespirit7

**Comment by jdelucca** [comment]
The answer is correctly in the file, so this issue can be closed.
