### ISSUE TITLE
New ECLIPSE questions (without answer)

### ISSUE THREAD

**Issue by pdnmusic** [Ebazhanov/linkedin-skill-assessments-quizzes#4568]
#### Q00. You want to use Bugzilla for managing tasks. What is a prerequisite?

- [ ] Select **Bugzilla** on the list of repositories in the **New Task** window.
- [ ] Add Bugzilla as a task repository.
- [ ] Install the Bugzilla plug-in.
- [ ] Create a new local task in the **Task List**.

#### Q00. Which of these listed when searching via the **Quick Access** search bar?

- [ ] files in the current workspace
- [ ] all of these answers
- [ ] XML attribute values
- [ ] Java members

#### Q00. After opening a code file, you notice some of the syntax coloring is missing. What is the most likely problem?

- [ ] The code has an error.
- [ ] The code is in a language that is too new for Eclipse to support.
- [ ] The code has the wrong file delimiters.
- [ ] The perspective you are using is out of date.

#### Q00. When enabled for a specific section, what do the preferences in **Java > Editor > Folding** control?

- [ ] They cause the section of the class to be collapsed when opened in a new editor.
- [ ] They cause those members to be placed automatically in a superclass, if present.
- [ ] They cause class members to be automatically ordered in accordance with the preferences.
- [ ] They cause the source code to autoformat as it is written.

**Comment by Ashwinip343** [comment]
Can you please assign me this?

**Comment by Ebazhanov** [comment]
Thank you all, questions in codebase!
