### ISSUE TITLE
New Amazon VPC question

### ISSUE THREAD

**Issue by MakendranG** [Ebazhanov/linkedin-skill-assessments-quizzes#4594]
1. In terms of Amazon VPC design, a VPC with a single public subnet is ideal for which of the following application designs?

**A single-tier application**	
A serverless application
A microservice application
A multi-tier application

2. If you stop and restart an EC2 instance, does it retain its private IP address?

**Yes, the instance retains its private IP addresses**
No, it retains only the public IP addresses.
No, it retains only the Elastic IP addresses.
No, it does not retain its private IP addresses.

All the Amazon EC2 instances you launch into a nondefault VPC are ______ by default.

stateless
protected	
public	
**private**

When you launch an instance into a dedicated-tenancy VPC, what happens?

**Your instance is automatically a Dedicated instance, regardless of the instance's specific tenancy attribute.** 
You receive an error message notifying you that you must set your instance's tenancy attribute to dedicated. 
Your instance launch fails, but AWS prompts you to launch a new one with the tenancy attribute set to dedicated.
Your instance launch fails immediately..

Use the _______ protocol in a VPC security group to communicate with a DB instance.

SSH
SSL
**TCP**
UDP

**Comment by parikhparth23** [comment]
Created a PR - https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/pull/4609

**Comment by MakendranG** [comment]
Hi @Ebazhanov 

I have worked on this issue and raised a PR https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/pull/4611

Kindly merge it.

**Comment by parikhparth23** [comment]
@MakendranG   #4609 is before #4611 ...

@Ebazhanov plz merge #4609

**Comment by Ebazhanov** [comment]
@MakendranG I know you have created an issue + type this questions but you have to be proud that Sr.Engineer from https://www.linkedin.com/in/parikhparth23/ take your issue, Guys you both doing great contribution! 🍺
