### ISSUE TITLE
Hacktoberfest submissions

### ISSUE THREAD

**Issue by wonhyeongseo** [Ebazhanov/linkedin-skill-assessments-quizzes#4680]
Hello, may you please consider the following PRs for Hacktoberfest 2022?
Thank you.

PR 1: https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/pull/4676
PR 2: https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/pull/4677
PR 3: https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/pull/4678
PR 4: https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/pull/4679

**Comment by Ebazhanov** [comment]
@wonhyeongseo have never see such way of reporting PR's, great idea! haha
