### ISSUE TITLE
Visio Assessment - Kindly add the following, not found on the existing Quiz Answers

### ISSUE THREAD

**Issue by ldc88** [Ebazhanov/linkedin-skill-assessments-quizzes#4695]
also, kindly check correct answer.

![Screenshot_7](https://user-images.githubusercontent.com/109124482/195005544-5e5d2455-5e14-4d5f-84ac-040d75df21c2.png)
![Screenshot_8](https://user-images.githubusercontent.com/109124482/195005553-2853bdba-de44-49a2-969e-08e1e8b0f4b7.png)

**Comment by MakendranG** [comment]
@Ebazhanov 

I am working on it.

**Comment by MakendranG** [comment]
Hi @Ebazhanov

I have worked on this issue and raised a PR https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/pull/4719

Kindly merge it.

**Comment by ldc88** [comment]
thank you so much.
will be contributing again to other issues!
more power
