### ISSUE TITLE
QuickBooks Assessments 

### ISSUE THREAD

**Issue by Arbaz7861** [Ebazhanov/linkedin-skill-assessments-quizzes#4755]
I have taken the QuickBooks test and noticed that LinkedIn added more questions and they are not included in the updated QuickBooks assessment section here. I still have only one try before having to wait for 3 months to retake the test again, and, unfortunately, I didn't write the new questions. is there a way that someone can add/update the QuickBooks to reflect the current quiz questions?
Thank you in advance

**Comment by auchynnikau** [comment]
@Arbaz7861 I've created PR #4829 that might help you. Please take a look.
