### ISSUE TITLE
Skill-assessment Django

### ISSUE THREAD

**Issue by Itashamodi** [Ebazhanov/linkedin-skill-assessments-quizzes#4831]
Q1. To cache your entire site for an application in Django, you add all except which of these settings?

])  django.middleware.common.CommonMiddleware
2) django.middleware.cache.UpdateCacheMiddleware
3) django.middleware.cache.FetchFromCacheMiddleware
4) django.middleware.cache.AcceleratedCacheMiddleware✔️

Answer: django.middleware.cache.AcceleratedCacheMiddleware

<img width="568" alt="DjanqoQuestion" src="https://user-images.githubusercontent.com/58629614/196073562-8769d57f-d324-427e-b604-6141fbd2bc67.png">

Django comes with a robust cache system that lets you save dynamic pages so they don’t have to be computed for each request. For convenience, Django offers cache with different granularity — from entire website to pages to part of pages to DB query results to any objects in memory.
Cache middleware. If enabled, each Django-powered page will be cached based on
URL.

**Comment by auchynnikau** [comment]
@Itashamodi  could you provide more details on this issue? This question is already includes in list and the answer is matches yours.

**Comment by Itashamodi** [comment]
sure
edited.

**Comment by auchynnikau** [comment]
Thanks, I'll update description for this answer. Assign this issue to me.

**Comment by Itashamodi** [comment]
where is the hacktoberfest tag? @Ebazhanov
