### ISSUE TITLE
New Word Questions

### ISSUE THREAD

**Issue by OtherDataDude** [Ebazhanov/linkedin-skill-assessments-quizzes#4840]
When you create a macro, you can assign it to a _____. (Select all that apply.)
A. keyboard shortcut
B. specific user
C. style pane
D. group on the ribbon

- [ ] D
- [ ] A
- [ ] A, C, D
- [ ] A, B, C

![image](https://user-images.githubusercontent.com/116020168/196230601-224e34be-6b55-4765-926a-a4191aef55fd.png)

What action allows you to quickly access a specific document from your list of saved files?

- [ ] Pin to list
- [ ] Drag to Home tab
- [ ] Add to chooser
- [ ] Mark as favorite

![image](https://user-images.githubusercontent.com/116020168/196231809-acf518c9-1114-4eb5-be7b-6a1ec4e84c42.png)

**Comment by Just2Deep** [comment]
Hi @Ebazhanov , Could you assign this to me.
I will work on it.

**Comment by AdityaShaw1** [comment]
pls assign me
