### ISSUE TITLE
Added New Question of Java

### ISSUE THREAD

**Issue by Itashamodi** [Ebazhanov/linkedin-skill-assessments-quizzes#4869]
<img width="261" alt="Javaq" src="https://user-images.githubusercontent.com/58629614/196332717-37c1521e-67b7-4cef-8b68-a268cacb4dfd.png">

**Comment by auchynnikau** [comment]
Assign this issue to me.

**Comment by Itashamodi** [comment]
@Ebazhanov I contributed to the issue, can you put label hacktoberfest
