### ISSUE TITLE
Windows Server

### ISSUE THREAD

**Issue by Ebazhanov** [Ebazhanov/linkedin-skill-assessments-quizzes#4921]
1)Which of the following is not an option for evaluating Storage Spaces Direct in Windows Server 2016?

Hyper-V virtual machines
validated server configuration from a partner
any computer that has a hard disk
existing hardware if it meets the requirements

2)When you move a Hyper-V virtual machine from Windows Server 2012 R2 to Windows Server 2016, _____.

it will run on the Server 2016 but cannot be moved back to the Server 2012
it will fail because the configuration of the virtual machine has to match the 2016 version
it will automatically update the virtual machine configuration to the 2016 version
the virtual machine configuration is not updated so it can be moved back to the Server 2012

3)Installing Windows Server 2016 without a product key _____.

is only possible if you install it without the Desktop Experience
is only possible if you install it as Standard
is possible but it will not activate after installation
is not possible

4)What is the benefit of access control policy templates?

They allow an administrator to enforce policy settings by assigning a template to a group of relying parties.
They allow adding Windows Server 2016 nodes to the existing farm while minimizing farm downtime.
They make it easier to migrate from Active Directory Federation Services in Windows Server 2012 R2.
They allow to add a new Windows Server 2016 Federation Servers to an existing

5)The _____ capability directly gives you the ability to implement site-to-site VPNs.

SET Architecture
RAS Gateway
NIC Teaming
Flow Engine

6)The _____ feature helps prevent malicious users from starting the denial of service attacks by using your DNS servers.

IPv6 Root Hints
Unknown Record Support
DNS-Based Authentication of Names Entities
Response Rate Limiting

7)A user is added to multiple time-bound groups. His Kerberos ticket-granting ticket lifetime will be the _____.

lowest time-to-live among all groups
sum of the time-to-live values across all groups
highest time-to-live among all groups
none of these answers

8)Which Hyper-V switch feature helps you set up a virtual machine as a virtual appliance and direct specific VLAN traffic to it?

Internet Protocol v6
Trunk mode to a virtual machine
Network traffic monitoring
Isolated VLANs

9)In _____ replication scenario(s), the replicated servers or clusters can be far from each other.

neither the server-to-server and cluster-to-cluster
only the cluster-to-cluster
only the server-to-server
both the server-to-server and cluster-to-cluster

10)The _____ Windows Server 2016 feature helps with meeting service level agreements.

Object-Oriented PowerShell syntax
Active Memory Dumps
Cluster OS Rolling Upgrade
Network Name Diagnostics

11)In the storage Qos deployment scenario based on Hyper-V using a Scale-Out File Server, _____.

you need a compute cluster with the Hyper-V role enabled
you need a computer cluster that has at least one server with the Hyper-V role enabled
you need Hyper-V configured using Cluster Shared Volumes for storage
you don't actually need a Scale-Out File Server cluster functioning as a storage cluste

**Comment by Arman143786** [comment]
All above question answer pls
