### ISSUE TITLE
New Python Question

### ISSUE THREAD

**Issue by MakendranG** [Ebazhanov/linkedin-skill-assessments-quizzes#4939]
You should pass in a value of _____ for the axis argument to the Pandas apply method to apply the function to each row.

row
col
**1**
0

To use pipelines in scikit-learn, import from the scikit-learn._____ submodule.

preprocessing
**pipeline**
filters
pipe_filter

Which of the following statements defines a new object type named "Dog" in Python?

**class Dog:**
Dog class:
Dog:
class Dog

Consider the following code snippet that uses decorators to calculate the execution time of execution_fn function:
```
import functools
import time

def timer(MISSING_ARG_1):
    @functools.wraps(func)
    def wrapper(*args, **kwargs):
        start_time = time.perf_counter()
        rval = func(*args, **kwargs)
        end_time = time.perf_counter() 
        duration = end_time - start_time
        print(f"Executed in {duration:.4f} seconds")
        return MISSING_ARG_2
    return MISSING_ARG_3

@timer
def execution_fn():
    for i in range(3):
        time.sleep(1)

execution_fn()
```

Which of the following choices are the missing arguments?

```
MISSING_ARG_1 = wrapper 

MISSING_ARG_2 = rval

MISSING_ARG_3 = func
```

```
MISSING_ARG_1 = func

MISSING_ARG_2 = rval

MISSING_ARG_3 = wrapper
```

```
MISSING_ARG_1 is empty 

MISSING_ARG_2 = rval

MISSING_ARG_3 = wrapper
```

```
MISSING_ARG_1 is empty

MISSING_ARG_2 = rval

MISSING_ARG_3 = func
```

Which comparison of lists and tuples in Python is correct?

Use lists instead of tuples when you have a collection of related but dissimilar objects.
Use tuples instead of lists when you have a common collection of similar objects.
**Use tuples instead of lists for functions that need to return multiple values.**
Use lists instead of tuples when the position of elements is important.

**Comment by MakendranG** [comment]
Hi @Ebazhanov

I have worked on this issue and raised a PR https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/pull/4940

Kindly merge it.

**Comment by Dilpreet1409** [comment]
Please assign this issue to me
