### ISSUE TITLE
New questions and answers for Google Ads quiz

### ISSUE THREAD

**Issue by fencerven** [Ebazhanov/linkedin-skill-assessments-quizzes#5045]
-You want to determine exactly what search terms triggered your ads to display. What do you do?

 [ ] Review the attribution report.

 [ ] Review the bidding report.

 [ ] Review the search terms report.

 [ ] Review the keyword frequency report.

-Which statement is true when structuring ad groups?

 [ ] Adding more ads to an ad group will improve the likelihood of multiple ads appearing for a search query.

 [ ] Adding more ads to an ad group provides more chances for success in an auction.

 [ ] Adding fewer ads to an ad group will improve the likelihood of an ad receiving a high-quality score.

 [ ] Adding fewer ads to an ad group means higher bounce rates.

-Patrick sells hats, and has added [womens hats] to his keyword list. Which search term will not trigger Patrick's ad to display?

 [ ] the women's hats

 [ ] hat for women

 [ ] women's hats

 [ ] sewing womens hats

**Comment by iam-roshanj** [comment]
I have solved these questions with their answers and references. You can review my pull request.😊
