### ISSUE TITLE
New Questions in the test

### ISSUE THREAD

**Issue by paumor28** [Ebazhanov/linkedin-skill-assessments-quizzes#5085]
1. You are creating columns in a text box using the Format Shape menu. What properties of the column can you adjust under the Text Options tab?

- [ ] number of columns and length of columns

- [ ] only the number of columns

- [ ] number of columns and space between columns

- [ ] space between lines of text and space between columns

2. Which choice describes the result of importing this Word outline into a presentation?
![image](https://user-images.githubusercontent.com/117478045/200050858-8b8cb87e-269c-4ac0-aa51-3efbcfe92126.png)
- [ ] Two slides will be created from the outline.
- [ ] One slide will be created with seven bullet items.
- [ ] Two sections will be created, one with three slides and one with two slides.
- [ ] Seven slides will be created from the outline.

**Comment by HemantMalokar** [comment]
1 = Ans => number of columns and space between columns.
2 = Ans => One slide will be created with seven bullet items.

**Comment by Rohxn16** [comment]
I can add these qs but can anyone please tell to which folder these questions belong to?
