### ISSUE TITLE
New Questions in the test

### ISSUE THREAD

**Issue by paumor28** [Ebazhanov/linkedin-skill-assessments-quizzes#5086]
1. You need to submit a PDF to a commercial printing company. They specify that the PDF shall only contain CMYK image content, with no RB images, no layers, and no live transparency. Which preset will meet these specifications?

- [ ] PDF/X-3
- [ ] PDF/X-4
- [ ] PDF/X-1a
- [ ] PDF/X-1b

2. A client provides a paper copy of an important document, but has lost the original file. Unfortunately, there are several misspelled words in the document. You scan the document, then convert it to a PDF using the File > Create > PDF from File...
option. What can you choose to repair the file?
(I cannot screenshot the opstions but the correct was "edit document")

3. A historical society asks you to design a book that will honor the society's founders. They want a PDF version of the book that ensures that the file will be readable in the distant future. What PDF format is designed for future readability?

- [ ] PDF/X-1a
- [ ] PDF/X-3 PDF/X-4
- [ ]  PDF/A-1a

**Comment by elenderg** [comment]
What Skill quiz does this questions belong to?

**Comment by dylannalex** [comment]
Adobe Acrobat maybe?

![image](https://user-images.githubusercontent.com/59183947/207463886-e94f6a23-1a2d-4785-820f-c55dc952fe44.png)

**Comment by lipprints71** [comment]
Adobe Acrobat Skills assessment - Not specifically formatting. Just the general assessment. I ran into those questions also

**Comment by Ebazhanov** [comment]
https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/pull/6501
