### ISSUE TITLE
New additions to Python

### ISSUE THREAD

**Issue by SpasticCamel** [Ebazhanov/linkedin-skill-assessments-quizzes#5107]
![Capture](https://user-images.githubusercontent.com/35035535/200874913-4fb31f49-0b0a-4ad9-8ef5-eef73cee4997.PNG)
 The one above is a new variant to Question 74.

![Capture2](https://user-images.githubusercontent.com/35035535/200874987-9044ca75-42f2-4539-a8f1-373ca86c0abc.PNG)
This one is a new question. I believe I answered correctly.

**Comment by rsk2** [comment]
Hi @Ebazhanov, I have created a PR for this issue
