### ISSUE TITLE
Second versions without answers

### ISSUE THREAD

**Issue by admhemed** [Ebazhanov/linkedin-skill-assessments-quizzes#5129]
Can we add a second version of each quiz where questions are not answered? this would give better chance for practicing.

**Comment by Ebazhanov** [comment]
I have an answer for your question already! Here you can choose playground with linkedin assessment on your choice:
e.g.
 - https://linassess.netlify.app/
 - https://linkedin-faq.github.io/md2practice/
 - https://github.com/linkedin-faq/linkedin-quizzes-kodyfire
 
need more? take a look at https://github.com/linkedin-faq

@admhemed I hope it can help and no need to create second version!
