### ISSUE TITLE
New question for Linux Quiz

### ISSUE THREAD

**Issue by anancola** [Ebazhanov/linkedin-skill-assessments-quizzes#5137]
I'm submitting an ISSUE: please check one with "x"

- [x] New question{'s} 
- [ ] New assessment 
- [ ] Missed questions/answers 
- [ ] Request for new quiz/answers/...
- [ ] Documentation issue or request for ...

![螢幕擷取畫面 2022-11-17 141334](https://user-images.githubusercontent.com/6374885/202374121-777a1410-5687-4b9b-b272-438f30908288.png)

**Comment by emanuele-em** [comment]
assign test
