### ISSUE TITLE
New question - Microsoft Excel

### ISSUE THREAD

**Issue by jocra07** [Ebazhanov/linkedin-skill-assessments-quizzes#5163]
I'm submitting an ISSUE: please check one with "x"

- [x] New question{'s} 
- [ ] New assessment 
- [ ] Missed questions/answers 
- [ ] Request for new quiz/answers/...
- [ ] Documentation issue or request for ...
- [ ] ...

![image](https://user-images.githubusercontent.com/35852334/203585483-76dbdb3a-2259-453e-962b-59e8a6c4bcb2.png)

**Comment by LoftyDroid** [comment]
Hi, @Ebazhanov can you assign this to me? I would like to contribute to this repo.

**Comment by emanuele-em** [comment]
close with #5210
