### ISSUE TITLE
New Question for Git

### ISSUE THREAD

**Issue by mikeycrystal** [Ebazhanov/linkedin-skill-assessments-quizzes#5177]
I'm submitting an ISSUE: please check one with "x"

- [
<img width="1127" alt="Screenshot 2022-11-25 at 5 06 32 PM" src="https://user-images.githubusercontent.com/108841529/204104226-8368d893-fd31-4df4-8ed4-340d0412910c.png">
x] New question{'s} 
- [ ] New assessment 
- [ ] Missed questions/answers 
- [ ] Request for new quiz/answers/...
- [ ] Documentation issue or request for ...
- [ ] ...

**Comment by ctnicholson** [comment]
Hey Ebazhanov, could you assign this issue to me?

**Comment by emanuele-em** [comment]
closed with #5210
