### ISSUE TITLE
Q3 Bug

### ISSUE THREAD

**Issue by Joseph7695** [Ebazhanov/linkedin-skill-assessments-quizzes#5184]
I'm submitting an ISSUE: please check one with "x"

- [ ] New question{'s} 
- [ ] New assessment 
- [ ] Missed questions/answers 
- [ ] Request for new quiz/answers/...
- [x] Documentation issue or request for ...

![image](https://user-images.githubusercontent.com/36186848/204142108-cfe2deec-443e-46f7-990f-3bfeb0501da1.png)
Code is not showing properly

**Comment by LoftyDroid** [comment]
Hi, @Ebazhanov can you assign this to me? I would like to contribute to this repo.

**Comment by emanuele-em** [comment]
@Ebazhanov close this issue, the question is Q3 in javascript-quiz.md
