### ISSUE TITLE
 New question Microsoft Power Point

### ISSUE THREAD

**Issue by Ender0715** [Ebazhanov/linkedin-skill-assessments-quizzes#5199]
I'm submitting an ISSUE: please check one with "x"

- [X] New question{'s} 
- [ ] New assessment 
- [ ] Missed questions/answers 
- [ ] Request for new quiz/answers/...
- [ ] Documentation issue or request for ...
- [ ] ...
![image](https://user-images.githubusercontent.com/34316986/205923382-7184ccdb-b49d-4287-aba6-45a39ce9abb7.png)

**Comment by emanuele-em** [comment]
@Ebazhanov Close this issue, the question is Q3 in javascript-quiz.md
