### ISSUE TITLE
Missing question Python

### ISSUE THREAD

**Issue by edunzer** [Ebazhanov/linkedin-skill-assessments-quizzes#5213]
I'm submitting an ISSUE: please check one with "x"

- [x] New question{'s} 
![Picture2](https://user-images.githubusercontent.com/20893684/206876157-a4d264d3-f28e-46e9-b25d-0c89b935ee96.jpg)

- [ ] New assessment 
- [ ] Missed questions/answers 
- [ ] Request for new quiz/answers/...
- [ ] Documentation issue or request for ...
- [ ] ...

**Comment by dylannalex** [comment]
I'm working on it!

**Comment by ed3899** [comment]
closed!
