### ISSUE TITLE
Microsoft PowerPoint duplicate question with 2 different 'correct' answers

### ISSUE THREAD

**Issue by nakigoe** [Ebazhanov/linkedin-skill-assessments-quizzes#5283]
# How can you reorder the levels of shapes in a SmartArt diagram?
the question has a duplicate with a different answer.

I'm submitting an ISSUE: please check one with "x"

- [ ] New question{'s} 
- [ ] New assessment 
- [ ] Missed questions/answers 
- [ ] Request for new quiz/answers/...
- [ ] Documentation issue or request for ...
- [x] Error in answers

**Comment by BHARGAVPATEL1244** [comment]
I check this question have only one answer in File.

Now u can close this issue @Ebazhanov
