### ISSUE TITLE
Please update my username in contributors list

### ISSUE THREAD

**Issue by vanenshi** [Ebazhanov/linkedin-skill-assessments-quizzes#5317]
I'm submitting an ISSUE: please check one with "x"

- [ ] New question{'s} 
- [ ] New assessment 
- [ ] Missed questions/answers 
- [ ] Request for new quiz/answers/...
- [ ] Documentation issue or request for ...
- [X] Fix my username

Hi, I had some contributions a while ago to your project, but I had to change my username for personal branding. Can you please update my username from @shekari-ah to @vanenshi?

**Comment by Ebazhanov** [comment]
Hello, @vanenshi! Thanks for letting me know. I have updated here https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/commit/d3ae7391c462bc70652dbff8536af65c4a66f865
please let me know if everything is ok now. Or just close this ticket!

**Comment by vanenshi** [comment]
Thanks, everything is ok
