### ISSUE TITLE
Python New Question

### ISSUE THREAD

**Issue by owseaman** [Ebazhanov/linkedin-skill-assessments-quizzes#5333]
I'm submitting an ISSUE: please check one with "x"

- [ x ] New question{'s} 
- [ ] New assessment 
- [ ] Missed questions/answers 
- [ ] Request for new quiz/answers/...
- [ ] Documentation issue or request for ...
- [ ] ...
![Python new question](https://user-images.githubusercontent.com/30220160/211716992-93b8dbfb-5781-4276-a238-d64a8427c4b4.jpg)

3rd option is the correct answer, I think.

**Comment by BalasubramanyamEvani** [comment]
First one seems correct

**Comment by mediumhotcoffee** [comment]
Simple, let's run the code!

```python
employees = {
  'alice' : {
    'position' : 'Lead Developer',
    'salary': 1000
  },
  'bob' : {
    'position' : 'Lead Artist',
    'salary': 2000
  },
  'charlie': {
    'position' : 'cfo',
    'salary': 3000
  }
}

print(employees['alice']['salary']) # 1000
employees['alice']['salary'] = employees['charlie']['salary'] # Code from Option 1
print(employees['alice']['salary']) # 3000
```

This means that option 1 is correct. But what's wrong with the other ones?

- Option 2: Tries to use a dictionary like an array. This is invalid
- Option 3: Tries to access a property `salary` on the dictionary, which doesn't exist. This is invalid
- Option 4: Tries to access a property `alice` on the dictionary, which doesn't exist. This is invalid

The actual error messages are:

```python
# Option 2
print(employees['alice'].salary) # AttributeError: 'dict' object has no attribute 'salary'
# Option 3
print(employees['alice'][1]) # KeyError: 1
# Option 4
employees.alice.salary # AttributeError: 'dict' object has no attribute 'alice'
```

**Comment by mediumhotcoffee** [comment]
@Ebazhanov this question was added to the Python quiz on PR #5340. I think this issue can be closed since the explanation was provided above.
