### ISSUE TITLE
AWS Lambda

### ISSUE THREAD

**Issue by owseaman** [Ebazhanov/linkedin-skill-assessments-quizzes#5336]
I'm submitting an ISSUE: please check one with "x"

- [ ] New question{'s} 
- [ ] New assessment 
- [ X ] Missed questions/answers 
- [ ] Request for new quiz/answers/...
- [ ] Documentation issue or request for ...
- [ ] ...
Answer to question 43 is the first  Option
![Screenshot 2023-01-12 195927](https://user-images.githubusercontent.com/30220160/212227380-90d0da75-001b-4bb1-9c4c-ab2af31f3f0a.jpg)

**Comment by ayan-joshi** [comment]
@Ebazhanov I want to work on this issue

**Comment by ayan-joshi** [comment]
@Ebazhanov  I have a doubt which is the correct ans , one shown in the image or the first option written in the message
