### ISSUE TITLE
C - Q40

### ISSUE THREAD

**Issue by houserockr** [Ebazhanov/linkedin-skill-assessments-quizzes#5343]
I'm submitting an ISSUE: please check one with "x"

- [ ] New question{'s} 
- [ ] New assessment 
- [ ] Missed questions/answers 
- [ ] Request for new quiz/answers/...
- [ ] Documentation issue or request for ...
- [x] Rant

Q40 of the C Quiz is an absolute nightmare!

**Question**:
You have written a function that you want to include as a member of structure a. How is such as structure member defined?
- [x] (a) :

```c
struct a {
    void *f1;
};
```

- [ ] (b) :

```c
struct a {
    void (*f1)();
};
```

- [ ] (c) :

```c
struct a {
    *(void *f1)();
};
```

- [ ] (d) :

```c
struct a {
    void *f1();
};
```

My remarks:
- First of all, the signature of the function is not given. But that's ok, because it becomes implicitly clear with the choices. So I can live with that.
- (c) and (d) are obviously BS, any C developer will skip those immediately.
- My main rant is that both (a) and (b) are correct, at least in terms of declaration
- However, if anyone in the field would write (a) in an actual project, I would personally slap them in the face
- IMO (b) is THE only permissible answer of this question
- Yes, you can in fact declare (a) and you will also be able to assign an actual function to that void pointer. But as soon as you want to actually call said function, it gets really ugly. I mean REALLY ugly

I know the motivation of this repo is to reflect the correct answers. What I'm saying is that whoever created the questions and the correct answers should think about this again.

**Comment by jgbispo** [comment]
Seeing my answer is correct, since this question refers to the way of declaring a member in a struct, The alternative "a" is the only one that actually declares a new member by putting its type and name, the others are trying to declare a function.

[Used reference](https://www.w3schools.com/c/c_structs.php)

**Comment by houserockr** [comment]
close.
