### ISSUE TITLE
lots of wrong answers at the java file.

### ISSUE THREAD

**Issue by brenoas** [Ebazhanov/linkedin-skill-assessments-quizzes#5371]
I'm submitting an ISSUE: please check one with "x"

- [ ] New question{'s} 
- [ ] New assessment 
- [ ] Missed questions/answers 
- [ ] Request for new quiz/answers/...
- [ ] Documentation issue or request for ...
- [ ] ...

**Comment by Ebazhanov** [comment]
Guys you might want to take a look [@sumanas27](https://github.com/sumanas27), [@ruslanbes](https://github.com/ruslanbes), [@PROCW](https://github.com/PROCW/), to double check, thank you in advance!

**Comment by Manish814142** [comment]
failed due to wrong answers "You scored higher than 38% of assessment takers".

**Comment by chela10** [comment]
Same here

**Comment by smashcoder** [comment]
I would like to look into this issue @Ebazhanov and try to solve it

**Comment by monkrus** [comment]
Closed as a dupilcate issue of https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/issues/5443
