### ISSUE TITLE
Chnanging the about section

### ISSUE THREAD

**Issue by disha-baldawa** [Ebazhanov/linkedin-skill-assessments-quizzes#5376]
I'm submitting an ISSUE: please check one with "x"

- [ ] New question{'s} 
- [ ] New assessment 
- [ ] Missed questions/answers 
- [ ] Request for new quiz/answers/...
- [x] Documentation issue or request for ...
- [ ] ...

Unfortunately we are in 2023 now so instead of "Full reference of LinkedIn answers 2022 for skill assessments", it should be "Full reference of LinkedIn answers **2023** for skill assessments".

**Comment by disha-baldawa** [comment]
Unfortunately we are in 2023 now so instead of "Full reference of LinkedIn answers 2022 for skill assessments", it should be "Full reference of LinkedIn answers 2023 for skill assessments".

**Comment by Ebazhanov** [comment]
great idea, thank you! going to update it now!
