### ISSUE TITLE
Object-Oriented Programming (OOP)

### ISSUE THREAD

**Issue by Ebazhanov** [Ebazhanov/linkedin-skill-assessments-quizzes#5404]
![image](https://user-images.githubusercontent.com/13170022/214893301-6089d252-20e9-4bee-b6c1-764b430f02dc.png)
![image](https://user-images.githubusercontent.com/13170022/214893448-06c83d43-ce57-4747-b69e-50cb12df04d5.png)

**Comment by smashcoder** [comment]
Is the issue solved or need to be solve ?? Please let me know
