### ISSUE TITLE
T-SQL

### ISSUE THREAD

**Issue by Ebazhanov** [Ebazhanov/linkedin-skill-assessments-quizzes#5407]
![image](https://user-images.githubusercontent.com/13170022/214894711-b0a8f37d-0f6f-43f4-9b70-0e758b2ca8fd.png)

**Comment by AnirudhKaranth** [comment]
I would like to solve this issue. Can you tell me how to do it? @Ebazhanov

**Comment by AnirudhKaranth** [comment]
am i supposed to add this question? @Ebazhanov
