### ISSUE TITLE
Ruby on rails

### ISSUE THREAD

**Issue by Ebazhanov** [Ebazhanov/linkedin-skill-assessments-quizzes#5415]
#### Q77. Which choice best describes the expected value of @result?

```
@result = Article.first.tags.build(name: ‘Urgent’)
```
- [ ] either true or false
- [x] an unsaved Tag instance
- [ ] a saved Tag instance
- [ ] an array of Tag instances

@manj01

**Comment by bhartee-sahare** [comment]
Return to the 1st object of the article. and build a method call that creates a new Tag object and associates it with the first Article object without saving it to the database.

if you want to save the object, you can use the following command:
@result.save # save that saving the object into the DB.

or you can use @result.create

**Comment by Rohxn16** [comment]
Imma work on this one

**Comment by Rohxn16** [comment]
I just reviewed the code, I saw that it already exists. This issue can be closed.
