### ISSUE TITLE
Maven

### ISSUE THREAD

**Issue by thieunguyenhung** [Ebazhanov/linkedin-skill-assessments-quizzes#5418]
New question

`This image shows a POM file with a profile. When will this profile be activated?`

- [ ] always
- [ ] when the system property debug is set to !true
- [ ] never
- [ ] when the system property debug is not set to true, or is not defined

<img width="840" alt="5d697fe5498e21bcd2763bfb-1567197835594" src="https://user-images.githubusercontent.com/15966296/215703364-e7e3d3ac-0a27-45d2-9861-10d73d34893a.png">

![Screen Shot 2023-01-31 at 15 08 14](https://user-images.githubusercontent.com/15966296/215704060-f3da48c8-22d9-4979-847f-6701aac8c16f.png)

**Comment by 53jk1** [comment]
@Ebazhanov when the system property debug is not set to true, or is not defined
