### ISSUE TITLE
10 new screenshots of questions Microsoft Access, answers needed

### ISSUE THREAD

**Issue by Jirafey** [Ebazhanov/linkedin-skill-assessments-quizzes#5477]
I'm submitting an ISSUE: please check one with "x"

micorosft access is really out of date, only 5 out of 15 questions I saw here (roughly)

- [x] New questions 

![Screenshot_22](https://user-images.githubusercontent.com/97115044/219486797-b2b35415-b2cb-4be9-aa9a-077c20f6f074.png)
![Screenshot_21](https://user-images.githubusercontent.com/97115044/219486798-6da91cdf-bce1-4fda-b2b1-a4086137bd65.png)
![Screenshot_20](https://user-images.githubusercontent.com/97115044/219486799-e2421131-5cd3-4ba2-999a-490569961e53.png)
![Screenshot_19](https://user-images.githubusercontent.com/97115044/219486802-46ae7cda-940b-4091-bbd4-0395609b7b2a.png)
![Screenshot_18](https://user-images.githubusercontent.com/97115044/219486805-8a4c108a-19b1-4996-9839-d81fe78fa1e3.png)
![Screenshot_17](https://user-images.githubusercontent.com/97115044/219486807-f8cd2429-fd97-4ff1-8d8f-3d7c02701f6b.png)
![Screenshot_16](https://user-images.githubusercontent.com/97115044/219486809-460272bc-b521-4bd4-bf4b-b3cfd10cb93e.png)
![Screenshot_25](https://user-images.githubusercontent.com/97115044/219486811-541893fe-294b-4fd7-8888-ef956eca898b.png)
![Screenshot_24](https://user-images.githubusercontent.com/97115044/219486815-062ca6de-be3e-4eef-afd7-e5f33547cc7a.png)
![Screenshot_23](https://user-images.githubusercontent.com/97115044/219486816-3f69ef6e-7ea3-40cb-afff-032bb76cdbcd.png)
 

- [x] Request for new answers to these
- Add to questions database:
- [ ] Add Q11
- [ ] Add Q10
- [ ] Add Q9
- [ ] Add Q7
- [ ] Add Q5
- [ ] Add Q4
- [ ] Add Q3
- [ ] Add Q15
- [ ] Add Q14
- [ ] Add Q12

- Add answers for:
- [ ] Add answers for Q11:
- [ ] Add answers for Q10:
- [ ] Add answers for Q9:
- [ ] Add answers for Q7:
- [ ] Add answers for Q5:
- [ ] Add answers for Q4:
- [ ] Add answers for Q3:
- [ ] Add answers for Q15:
- [ ] Add answers for Q14:
- [ ] Add answers for Q12:

 (I somehow managed to get a badge but I didnt count lol)

**Comment by payalpm** [comment]
@Ebazhanov @Jirafey assign me this issue i solved
