### ISSUE TITLE
Java is all wrong. Failed many times with the answers

### ISSUE THREAD

**Issue by slidingwindowkrissmittur2** [Ebazhanov/linkedin-skill-assessments-quizzes#5504]
I'm submitting an ISSUE: please check one with "x"

- [ ] New question{'s} 
- [ ] New assessment 
- [ ] Missed questions/answers 
- [ ] Request for new quiz/answers/...
- [ ] Documentation issue or request for ...
- [ ] ...

**Comment by nisarg0** [comment]
++

**Comment by KauaBR0** [comment]
++

**Comment by monkrus** [comment]
Close as duplicate issue of https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/issues/5443
