### ISSUE TITLE
Microsoft Excel new question

### ISSUE THREAD

**Issue by andrew-kovalenk0** [Ebazhanov/linkedin-skill-assessments-quizzes#5509]
I'm submitting an ISSUE: please check one with "x"

- [x] New question{'s} 
- [ ] New assessment 
- [ ] Missed questions/answers 
- [ ] Request for new quiz/answers/...
- [ ] Documentation issue or request for ...
- [ ] ...
![изображение](https://user-images.githubusercontent.com/43520508/221381161-5885b4aa-b836-41eb-9e98-1a68cfb53e04.png)

**Comment by Just2Deep** [comment]
![Q145](https://user-images.githubusercontent.com/48485675/221608974-f1fa1369-9a52-43d5-a738-5744ede084bc.png)

**Comment by Just2Deep** [comment]
This issue can be closed.

**Comment by KHChen-NY** [comment]
Answer is Histogram btw.
