### ISSUE TITLE
autocad-quiz.md missing questions

### ISSUE THREAD

**Issue by trogfield** [Ebazhanov/linkedin-skill-assessments-quizzes#5538]
I'm submitting an ISSUE: please check one with "x"

- [x] New question{'s} 
- [ ] New assessment 
- [ ] Missed questions/answers 
- [ ] Request for new quiz/answers/...
- [ ] Documentation issue or request for ...
- [ ] ...

please double check that these are right, most of them were missing from the test

![image](https://user-images.githubusercontent.com/22109189/223653053-091e9da7-4fa9-46af-98a8-78f03bddd329.png)
![image](https://user-images.githubusercontent.com/22109189/223653077-68520fef-6d56-4271-82d5-32abb04e2588.png)
![image](https://user-images.githubusercontent.com/22109189/223653090-a8aa6fc0-30d7-46ee-9284-e17b7bebffcc.png)
![image](https://user-images.githubusercontent.com/22109189/223653105-3b399a51-a579-41fa-bf15-8c06f3176adf.png)
![image](https://user-images.githubusercontent.com/22109189/223653128-15b70f09-aaba-4e81-968c-d536a85744bd.png)
![image](https://user-images.githubusercontent.com/22109189/223653153-b3d9af9a-d9c2-48fd-81f0-9fa835766bc3.png)
![image](https://user-images.githubusercontent.com/22109189/223653165-da784d78-9c44-42c9-89e3-2b2e7b413156.png)
![image](https://user-images.githubusercontent.com/22109189/223653176-e837cb77-b5ce-4417-9908-5688085f0758.png)

**Comment by trogfield** [comment]
I am pretty sure all of them are right. i got graded in the top 5%

**Comment by Rohxn16** [comment]
I will be adding these questions to the repo.

**Comment by Rohxn16** [comment]
@Ebazhanov  I made a little mistake here, I wrote photoshop instead of AutoCAD in the the commit message.
