### ISSUE TITLE
search-engine-optimization-quiz.md missing question

### ISSUE THREAD

**Issue by trogfield** [Ebazhanov/linkedin-skill-assessments-quizzes#5539]
I'm submitting an ISSUE: please check one with "x"

- [x] New question{'s} 
- [ ] New assessment 
- [ ] Missed questions/answers 
- [ ] Request for new quiz/answers/...
- [ ] Documentation issue or request for ...
- [ ] ...

this is probably the wrong answer

what is the right answer?

![image](https://user-images.githubusercontent.com/22109189/223659844-60010f32-f19f-42a3-9fa4-4a05620d7810.png)

**Comment by dcantatore** [comment]
X - a domain name that fits their branding

https://www.shopify.com/blog/domain-seo
`Domain SEO only strives to optimize the name of your registered domain.`

https://www.website.com/website-builder-and-web-design/how-to-choose-a-seo-friendly-domain-name
`Yes it does. If we are looking at just the domain name alone, it is undeniable that you want people to recognize your brand, your business or what your website is all about.`
