### ISSUE TITLE
python-quiz.md missing question

### ISSUE THREAD

**Issue by trogfield** [Ebazhanov/linkedin-skill-assessments-quizzes#5540]
I'm submitting an ISSUE: please check one with "x"

- [x] New question{'s} 
- [ ] New assessment 
- [ ] Missed questions/answers 
- [ ] Request for new quiz/answers/...
- [ ] Documentation issue or request for ...
- [ ] ...

this easy question is missing:

![image](https://user-images.githubusercontent.com/22109189/223660023-872f0ca2-842c-46e8-85d3-8a5c009f1deb.png)

**Comment by AnirudhKaranth** [comment]
@Ebazhanov I have created a PR for the same.

**Comment by MandyMeindersma** [comment]
@Ebazhanov can you close this?
