### ISSUE TITLE
Is the Answer to React Q48 correct?

### ISSUE THREAD

**Issue by KasunShanaka** [Ebazhanov/linkedin-skill-assessments-quizzes#5554]
What will happen when this useEffect Hook is executed, assuming name is not already equal to John?

```
useEffect(() => {
  setName('John');
}, [name]);
```

- [ ] It will cause an error immediately.
- [ ] It will execute the code inside the function, but only after waiting to ensure that no other component is accessing the name variable.
- [x] It will update the value of name once and not run again until name is changed from the outside.
- [ ] It will cause an infinite loop.

**Current merked answer is the 4th option which is "It will cause an infinite loop". But this code wouldn't cause an infinite loop. I think the answer should be the 3rd option."**

Am I missing something here? Can someone explain why it has marked the 4th option?

**Comment by ArenRitz** [comment]
I believe this happens because we pass the "name" state in the array, the useEffect will trigger every time the name is changed, which will cause the infinite loop. 
To resolve this, we could pass an empty array instead, so that the useEffect will trigger only once.

You can find a much better explanation here :
https://stackoverflow.com/a/54923969

**Comment by ArenRitz** [comment]
You are right it does not loop.
I had it wrong, if the dependency array was not there then it would infinitely loop.
The correct answer is definitely the 3rd option as you mentioned.
It will update the value of name once and not run again until name is changed from the outside.

**Comment by monkrus** [comment]
It is the 3rd option.  
We assume that name is not already equal to "John", right?

The useEffect hook with a dependency array [name] will only be triggered when the value of name is **changed**. In this case, the function inside the useEffect hook will set the value of name to "John" once when it is triggered.

After this, the useEffect hook will not run again until the value of name is changed from the outside. Therefore, there will be no infinite loop, error, or waiting for other components to access the name variable.

**Comment by monkrus** [comment]
@all-contributors please add @KasunShanaka for code
