### ISSUE TITLE
AWS missing Question

### ISSUE THREAD

**Issue by ColbyMay** [Ebazhanov/linkedin-skill-assessments-quizzes#5565]
I'm submitting an ISSUE: please check one with "x"

- [x] New question{'s} 
- [ ] New assessment 
- [ ] Missed questions/answers 
- [ ] Request for new quiz/answers/...
- [ ] Documentation issue or request for ...
- [ ] ...
![image](https://user-images.githubusercontent.com/47373853/225419569-681b926d-8812-4784-9802-8ca49523c39b.png)

**Comment by AnirudhKaranth** [comment]
I would like to solve this issue. Can you assign me? @Ebazhanov

**Comment by MandyMeindersma** [comment]
This can be closed now right?
