### ISSUE TITLE
Answer to Question 27 Incorrect

### ISSUE THREAD

**Issue by KHChen-NY** [Ebazhanov/linkedin-skill-assessments-quizzes#5628]
I'm submitting an ISSUE: please check one with "x"

- [ ] New question{'s} 
- [ ] New assessment 
- [ x] Missed questions/answers 
- [ ] Request for new quiz/answers/...
- [ ] Documentation issue or request for ...
- [ ] ...

Q27. Which formula correctly counts the number of numeric values in both B4:E4 and G4:I4?

 =COUNT(B4:E4&G4:I4)
 =COUNT(B4:E4,G4:I4)
 =COUNT(B4:E4 G4:I4)
 =COUNT(B4:I4)

The Answer is the second one “=COUNT (B4:E4, G4:I4).  The last answer is incorrectly labelled as the correct answer

**Comment by monkrus** [comment]
Indeed, the correct formula to count the number of numeric values in both B4:E4 and G4:I4 is:=COUNT(B4:E4,G4:I4)

This formula uses the COUNT function to count the numeric values in the specified ranges separated by a comma. The ampersand symbol (&) is used to concatenate the two ranges, which is not necessary for this calculation.

The formula COUNT(B4:I4) would count the numeric values in a different range that includes columns B through I, which is not what is requested.

**Comment by monkrus** [comment]
Answer corrected
