### ISSUE TITLE
R quiz

### ISSUE THREAD

**Issue by Ebazhanov** [Ebazhanov/linkedin-skill-assessments-quizzes#5636]
![image](https://user-images.githubusercontent.com/13170022/230904356-1f446e47-5976-4476-b5a9-8559ff910967.png)

**Comment by monkrus** [comment]
Correct answer is the last choice.

When stringAsFactors=TRUE, R automatically converts character variables into factors, which are categorical variables that have a fixed set of possible values. If you later want to add new values to the variable, you may need to convert it back to a character variable or manually modify the factor levels. This can cause difficulty and extra work, especially if the variable is used in multiple places in your code.

Therefore, it is generally recommended to set stringAsFactors=FALSE when creating an object's initial data structure, unless you specifically need to use factors for some reason.

**Comment by monkrus** [comment]
@all-contributors please add @monkrus  for documentation
