### ISSUE TITLE
Git answer incorrect

### ISSUE THREAD

**Issue by staerz** [Ebazhanov/linkedin-skill-assessments-quizzes#5639]
There's a mistake in one of the git questions:

98: After checking out a specific commit, you receive a warning message indicating You are in 'detached HEAD' state. What is Git warning you of?

The ticked answer "You are not working on the most recent commit of a branch." is actually not correct: That message **always** is given when checking out **a specific commit**, no matter if or if not this is related to any recent branch.

Just reporting the fact. Not sure if the people from LinkedIn would be notified of that problem.

(I just took the quiz and got the most expert set of questions (some of which have no relevance to a regular nor expert user IMHO) ever thinkable :D )

Addon:
- Typo in Q103: "until it os peer reviewed" is likely to mean "until it **is** peer reviewed"
- Style typo in Q105: 2nd line `hint: ...` should be on new line in code env
- Q113: Technically the proposed answer is also incorrect. `HEAD` is simply the pointer to the current commit. No matter how recent or if on a branch or not.
- Typo in Q115: "an issue is create that" likely to mean "an issue is create**d** that"

**Comment by lcreed** [comment]
i just ran through this test and failed using the published answers so there are some wrong answers there.

**Comment by btt08** [comment]
> i just ran through this test and failed using the published answers so there are some wrong answers there.

Same. Using the answers i got only in the 46% and you need to be in the 30%

**Comment by syedhannan** [comment]
@Ebazhanov  Assign me this

**Comment by Ebazhanov** [comment]
https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/pull/6422
