### ISSUE TITLE
object-oriented-programming question 29 problem

### ISSUE THREAD

**Issue by khoay** [Ebazhanov/linkedin-skill-assessments-quizzes#5646]
I'm submitting an ISSUE: On question 29, the answer is not one of the possible options

- [ ] New question{'s} 
- [ ] New assessment 
- [x] Missed questions/answers 
![image](https://user-images.githubusercontent.com/75439583/232859516-08a3c180-2f62-4b36-aad8-86673398804d.png)
- [ ] Request for new quiz/answers/...
- [ ] Documentation issue or request for ...
- [ ] ...

**Comment by anubhav1206** [comment]
Can I work on this?

**Comment by khoay** [comment]
Sure

**Comment by smashcoder** [comment]
@Ebazhanov Can you provide me the permission to accept and merge the pull request ??
