### ISSUE TITLE
missing answer

### ISSUE THREAD

**Issue by johnfelipe** [Ebazhanov/linkedin-skill-assessments-quizzes#5656]
https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/main/hadoop/hadoop-quiz.md#q61-which-statement-should-you-add-to-improve-the-performance-of-the-following-query

**Comment by payalpm** [comment]
@Ebazhanov @johnfelipe assign me

**Comment by syedhannan** [comment]
This issue needs to be closed as the answer has already been added
