### ISSUE TITLE
javaScript assessment

### ISSUE THREAD

**Issue by abagrevatil** [Ebazhanov/linkedin-skill-assessments-quizzes#5677]
I'm submitting an ISSUE: please check one with "x"

- [x] New question{'s}
- [ ] New assessment
- [ ] Missed questions/answers
- [ ] Request for new quiz/answers/...
- [ ] Documentation issue or request for ...

Which line is missing from this code if you expect the code to evaluate to true?

```
var compare = function(test1, test2) {
    // Missing line
}

compare(1078, "1078"); // yields true
```

- [ ] test1==test2;
- [ ] return test1===test2;
- [ ] return test1==test2;
- [ ] return test1!=test2;

**Comment by ntatko** [comment]
@Ebazhanov This issue can be closed
