### ISSUE TITLE
Microsoft Outlook assessment

### ISSUE THREAD

**Issue by abagrevatil** [Ebazhanov/linkedin-skill-assessments-quizzes#5679]
I'm submitting an ISSUE:

- [x] New question
- [ ] New assessment
- [ ] Missed questions/answers
- [ ] Request for new quiz/answers/...
- [ ] Documentation issue or request for ...

Without leaving the Email page, which is the _most efficient_ way to add the contact of someone who sent you an email?

- [ ] Copy and paste their email address into a new contact form.
- [ ] Open the email and press Ctrl+Q (Windows) or Command + Q (Mac).
- [ ] On Windows, right-click the sender's name in the message and select **Add to Outlook Contacts**. On Mac, Control+click the sender's name in the message and select **Open Outlook contact > Add to Contacts > Save** and then **Close**.
- [ ] Double-click the sender's email address in the message and select **Add to Outlook Contacts** (Windows) or **Open Outlook contacts** (Mac).

**Comment by webdev-ashishk** [comment]
I have create PR for this , let me know if any changes required ?

**Comment by webdev-ashishk** [comment]
I was confused with all my changes, so I decided to close the existing pull request (PR) and create a fresh one that doesn't conflict with any other codes.
