### ISSUE TITLE
Microsoft PowerPoint assessment

### ISSUE THREAD

**Issue by abagrevatil** [Ebazhanov/linkedin-skill-assessments-quizzes#5680]
I'm submitting an ISSUE:

- [x] New question
- [ ] New assessment
- [ ] Missed questions/answers
- [ ] Request for new quiz/answers/...
- [ ] Documentation issue or request for ...

Which Bullets and Numbering function should you use to start a numbered list at a value other than 1?

- [ ] Custom Number
- [ ] AutoNumber
- [ ] Align Number
- [ ] Start At

**Comment by webdev-ashishk** [comment]
@Ebazhanov , Start At
