### ISSUE TITLE
SharePoint assessment

### ISSUE THREAD

**Issue by abagrevatil** [Ebazhanov/linkedin-skill-assessments-quizzes#5681]
I'm submitting an ISSUE:

- [x] New questions
- [ ] New assessment
- [ ] Missed questions/answers
- [ ] Request for new quiz/answers/...
- [ ] Documentation issue or request for ...

The News web part allows users to add a news post to the web part. What other item can users add to the News web part?

- [ ] a list
- [ ] a news link
- [ ] a page
- [ ] a form

You need to create a new site as a SharePoint subsite that will not inherit permissions from the parent site. What must you do to block inheritance?

- [ ] Create and assign users to the subsite.
- [ ] Create or assign groups to the subsite.
- [ ] Copy permissions from the parent site to the subsite.
- [ ] Block permissions inheritance from the parent site.

You created a site collection and would like to give a manager in your organization the capability to add and maintain users. To which group do you add this manager without compromising security?

- [ ] contributor
- [ ] administrator
- [ ] owner
- [ ] viewer

How do you find site usage statistics in SharePoint Online?

- [ ] On the site home page, click the gear (**Settings**) icon and go to **Site information**. Select **View all site settings**, and then in the **Site Administration section**, select **Site usage statistics**.
- [ ] On the **Site contents** page, click **Site usage**.
- [ ] On the site home page, click the gear (**Settings**) icon, go to **Site settings**, and select **Site usage**.
- [ ] In the SharePoint Admin Center, select the SharePoint File Activity report.

An organization has deployed a SharePoint parent site that includes a four-level hierarchy of subsites. You want to add another subsite to this hierarchy. What is the hard limit on a subsite hierarchy?

- [ ] There is a limit of up to ten subsites in a single hierarchy.
- [ ] There is a limit of up to five sites (one parent, four subsites) in a single hierarchy.
- [ ] There is no hierarchy limit for subsites.
- [ ] There is a limit of up to five subsites in a single hierarchy.

You have created a new page in a SharePoint Online site. Which elements are displayed on the page by default?

- [ ] the title area web part, the document library web part, and comments
- [ ] the title area web part, the Yammer web part, and comments
- [ ] the News web part, the title area web part, and comments
- [ ] the title area web part and comments

What initiates a SharePoint workflow? (Select all that apply.)
A. manual trigger
B. on-change automatic trigger
C. on-create automatic trigger
D. on-delete automatic trigger

- [ ] B,C, D
- [ ] A.C, D
- [ ] A, B.C
- [ ] A, B, C, D

**Comment by harsitagarwalla187** [comment]
Hello @Ebazhanov. 
I am interested in solving this issue.
I have a question:
    Do i have to add the question to [SharePoint](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/main/sharepoint/sharepoint-quiz.md) or the solutions also?

**Comment by harsitagarwalla187** [comment]
@Ebazhanov Do i have to add the solution of all the questions?

**Comment by Ebazhanov** [comment]
> @Ebazhanov Do i have to add the solution of all the questions?

it is up to you, no needed for all

**Comment by harsitagarwalla187** [comment]
> > @Ebazhanov Do i have to add the solution of all the questions?
> 
> it is up to you, no needed for all

Ok
