### ISSUE TITLE
#Request to add more questions on aws

### ISSUE THREAD

**Issue by Bsp4pl** [Ebazhanov/linkedin-skill-assessments-quizzes#5689]
We need more questions on AWS so that it will be easier to get all questions at one place. @jokerkeny  @Amsal1  

The reference which i know is here below:-
https://quizlet.com/340744042/aws-flash-cards/

**Comment by webdev-ashishk** [comment]
I recently learned about Version Control systems and I'm excited to work with you. Can you assign this task to me?

**Comment by webdev-ashishk** [comment]
@Ebazhanov , I started working on this project

**Comment by webdev-ashishk** [comment]
@Ebazhanov,   Some questions do not have options. What can I do?
