### ISSUE TITLE
missing answer

### ISSUE THREAD

**Issue by payalpm** [Ebazhanov/linkedin-skill-assessments-quizzes#5735]
I'm submitting an ISSUE: please check one with "x"

- [ ] New question{'s} 
- [ ] New assessment 
- [ ] Missed questions/answers 
- [ ] Request for new quiz/answers/...
- [ ] Documentation issue or request for ...
- [ ] ...
Q66. When you implement a custom Writable, you must also define which of these object?
 a sort policy
 a combiner policy
 a compression policy
 a filter policy

**Comment by webdev-ashishk** [comment]
Can You write file name where this questions is present ???

**Comment by payalpm** [comment]
I don't remember sorry

**Comment by webdev-ashishk** [comment]
I got it where This is present , I will take this issue as reference and create pull request  and guide You also , contact me as soon as possible other wise some one create pull request

**Comment by payalpm** [comment]
Where i will contact you

**Comment by webdev-ashishk** [comment]
Here You contact Me =>7905101205

**Comment by payalpm** [comment]
Thanks a lot. I dm u check
