### ISSUE TITLE
Java Quiz Q24 error 

### ISSUE THREAD

**Issue by toysoldier2012** [Ebazhanov/linkedin-skill-assessments-quizzes#5746]
#java

In Q24, why "An anonymous class does not require a zero-argument constructor." is not true?

Original question:
Q 24. Which statement is **NOT** true? #anonymousclass

- [ ] An anonymous class may specify an abstract base class as its base type.
- [x] An anonymous class does not require a zero-argument constructor.
- [ ] An anonymous class may specify an interface as its base type.
- [ ] An anonymous class may specify both an abstract class and interface as base types.

**Comment by webdev-ashishk** [comment]
do you want to change original question ?

**Comment by webdev-ashishk** [comment]
I created PR for this ?

**Comment by toysoldier2012** [comment]
Yes plz :)
