### ISSUE TITLE
New JSON question

### ISSUE THREAD

**Issue by ed3899** [Ebazhanov/linkedin-skill-assessments-quizzes#5747]
I'm submitting an ISSUE: please check one with "x"

- [x ] New question{'s} 
- [ ] New assessment 
- [ ] Missed questions/answers 
- [ ] Request for new quiz/answers/...
- [ ] Documentation issue or request for ...
- [ ] ...

I forgot to take a screenshot of the question but it's regarding JSON number types:

The answer is: Integer, Floating Points and Exponents (Scientific Notation, something like that i.e 3e4)

**Comment by webdev-ashishk** [comment]
I go through entire JSON Quiz.md file there is no such Question exist ? Could You tell me Question Number ?

**Comment by marifoglu** [comment]
> 

I think he means that the problem doesn't exist in the json-quiz.md, it's a new question.

**Comment by syedhannan** [comment]
This needs to be closed as this does not contain any info related to what the issue is

**Comment by aryan-rohit** [comment]
@Ebazhanov I would love to solve this issue. Please assign this issue to me

**Comment by aryan-rohit** [comment]
@Ebazhanov would you please inform me on which file you want json question or should i create a new file

**Comment by Ebazhanov** [comment]
fyi https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/main/json/json-quiz.md
