### ISSUE TITLE
3 new Unity questions with correct answers

### ISSUE THREAD

**Issue by abenteuerzeit** [Ebazhanov/linkedin-skill-assessments-quizzes#5775]
I'm submitting an ISSUE: please check one with "x"

- [X ] New question{'s} 
- [ ] New assessment 
- [ ] Missed questions/answers 
- [ ] Request for new quiz/answers/...
- [ ] Documentation issue or request for ...
- [ ] ...

I do not have all the answer options, but the responses below are correct. How should I add these?  

1. What does the `Input.touchCount` variable represent?
Answer: The `Input.touchCount` variable in Unity represents the number of touches currently present on the screen. [This variable is updated every frame and can be used to determine how many fingers are touching the screen at any given time ](https://docs.unity3d.com/ScriptReference/Input-touchCount.html)[1](https://docs.unity3d.com/ScriptReference/Input-touchCount.html).
2. You need to serialize selected variables of all enemies during gameplay to text form. This data must then be sent over a network for parsing to generate statistics about the current play session. Which class helps you convert object data to text form in unity?
Answer: The `JsonUtility` class to convert object data to and from `JSON` text format. [This class provides methods such as `ToJson` and `FromJson` that allow you to serialize and deserialize object data ](https://docs.unity3d.com/Manual/script-Serialization.html)[1](https://docs.unity3d.com/Manual/script-Serialization.html).
3. Which texture format is generally avoided in Unity?
Answer: Avoid using uncompressed texture formats or lossy formats such as `JPEG`. Uncompressed textures offer the highest quality, but they also have the highest memory usage and can impact performance. [Lossy formats such as JPEG can result in visual artifacts and reduced quality ](https://docs.unity3d.com/Manual/texture-compression-formats.html)[1](https://docs.unity3d.com/Manual/texture-compression-formats.html).

**Comment by Craniace** [comment]
Hi,please assign me this issue.
