### ISSUE TITLE
New JSON Question with answer

### ISSUE THREAD

**Issue by VIDAL-Antoine** [Ebazhanov/linkedin-skill-assessments-quizzes#5778]
- [x] New question

[](url)
![Screenshot from 2023-05-25 14-06-46](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/assets/71827734/469ecb39-9822-47db-9f7a-e4d18aafa1b1)

Text version : 

How would you update this JSON to indicate that Jane is now available for part-time work?

{
  "name": "Jane",
  "job": "developer",
  "skills": ["ruby", "rails", "javascript"],
  "available": false
}

- [x] A

{
  "name": "Jane",
  "job": "developer",
  "skills": ["ruby", "rails", "javascript"],
  "available": true,
  "seeking": "part-time"
}

- [ ] B

{
  "name": "Jane",
  "job": "developer",
  "skills": ["ruby", "rails", "javascript"],
  "available" : "true",
  "seeking": "part-time"
}

- [ ] C

{
  "name": "Jane",
  "job": "developer",
  "skills": ["ruby", "rails", "javascript"],
  "available": false,
  "seeking": "part-time"
}

- [ ] D

{
  "name": "Jane",
  "job": "developer",
  "skills": ["ruby", "rails", "javascript"],
  "available" : "true",
  "seeking": 'part-time'
}

true needs to be a boolean and part-time a string so in double quotes.

**Comment by Ebazhanov** [comment]
@VIDAL-Antoine, @AnirudhKaranth thank you guys! 👍
