### ISSUE TITLE
JSON quiz has wrong answers

### ISSUE THREAD

**Issue by eaborodkin** [Ebazhanov/linkedin-skill-assessments-quizzes#5780]
I'm submitting an ISSUE: please check one with "x"

- [ ] New question{'s} 
- [ ] New assessment 
- [ ] Missed questions/answers 
- [ ] Request for new quiz/answers/...
- [ ] Documentation issue or request for ...
- [x] I used the answers from the JSON file and failed the quiz. 
E.g. Can trailing commas be used in objects and arrays? 
The file says that the correct answer is "yes", but the linkedin says the correct answer is "no".

**Comment by eaborodkin** [comment]
E.g. Can trailing commas be used in objects and arrays?
The file says that the correct answer is "yes", but the linkedin says the correct answer is "no".

**Comment by AggarwalNeelesh** [comment]
The correct answer is "Yes". Assign me the task..

**Comment by Ebazhanov** [comment]
done, thank you all!
