### ISSUE TITLE
New React Question May 2023

### ISSUE THREAD

**Issue by ed3899** [Ebazhanov/linkedin-skill-assessments-quizzes#5783]
I'm submitting an ISSUE: please check one with "x"

- [ x] New question{'s} 

![up](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/assets/53999059/3140a9b8-56dd-479e-84a6-f28d07f3955a)

THE ANSWER I PICKED MAY NOT NECESSARILY BE THE RIGHT ONE. I PASSED BUT I AM STILL UNSURE ABOUT THE CORRECTNESS OF MY ANSWER

**Comment by Manoj-2702** [comment]
Please assign me this issue.
