### ISSUE TITLE
CSS Questions Fix

### ISSUE THREAD

**Issue by ed3899** [Ebazhanov/linkedin-skill-assessments-quizzes#5787]
I'm submitting an ISSUE: please check one with "x"
- [x ] Missed questions/answers 
Q26. When using media queries, media types are used to target a device category. Which choice lists current valid media types?
-  print, screen, aural
- print, screen, speech

note: both are valid

> In addition, the following deprecated [media types](https://drafts.csswg.org/mediaqueries/#media-type) are defined. Authors must not use these media types; instead, it is recommended that they select appropriate [media features](https://drafts.csswg.org/mediaqueries/#media-feature) that better represent the aspect of the device that they are attempting to style against.
> 
> User agents must recognize the following [media types](https://drafts.csswg.org/mediaqueries/#media-type) as valid, but must make them match nothing.
> Ref: https://drafts.csswg.org/mediaqueries/#media-types

> tty
> tv
> projection
> handheld
> braille
> embossed
> aural
> speech
> NOTE: It is expected that all of the media types will also be deprecated in time, as appropriate [media features](https://drafts.csswg.org/mediaqueries/#media-feature) are defined which capture their important differences.
>

**Comment by ahmed0saber** [comment]
Hello @ed3899 , I think "print, screen, speech" is the correct answer, "speech" and "aural" can seem like so similar but we can't use "@media aural { }", it's "@media speech { }"

**Comment by BHARGAVPATEL1244** [comment]
Yes print, screen, speech is the correct answer

**Comment by ahmed0saber** [comment]
Hi @Ebazhanov , I think we can close this issue, what do you think?
