### ISSUE TITLE
Wrong answer in Django

### ISSUE THREAD

**Issue by ed3899** [Ebazhanov/linkedin-skill-assessments-quizzes#5796]
I'm submitting an ISSUE: please check one with "x"
- [ x] Missed questions/answers 
### Q55. What is WSGI?
 an interface specification

> WSGI[[1]](https://wsgi.tutorial.codepoint.net/intro#f1) is not a server, a python module, a framework, an API or any kind of software. It is just an interface specification by which server and application communicate. Both server and application interface sides are specified in the [PEP 3333](https://www.python.org/dev/peps/pep-3333). If an application (or framework or toolkit) is written to the WSGI spec then it will run on any server written to that spec.

Ref: https://wsgi.tutorial.codepoint.net/intro

**Comment by Craniace** [comment]
Hi, I would like to be assigned to this issue.

**Comment by MandyMeindersma** [comment]
@Ebazhanov can you close this?
