### ISSUE TITLE
Bash answer to Q82

### ISSUE THREAD

**Issue by ed3899** [Ebazhanov/linkedin-skill-assessments-quizzes#5800]
I'm submitting an ISSUE: please check one with "x"
- [ X] Missed questions/answers 

### Q82. You want to match five-letter palindromes such as radar, rotor, and tenet. Which sed option should you use?
` sed -E -n '/^(.)(.)(.)\2\1$/p'
`

**Comment by Madhav-2808** [comment]
Hi , I added the reference in it and it got merged also (#5813 ) then why this issue is still open 
and what step should I follow to close this issue and get DevRank

**Comment by Ebazhanov** [comment]
> Hi , I added the reference in it and it got merged also (#5813 ) then why this issue is still open and what step should I follow to close this issue and get DevRank

good catch @Madhav-2808, closing
