### ISSUE TITLE
Add some ques in object-oriented-programming

### ISSUE THREAD

**Issue by sha0urya** [Ebazhanov/linkedin-skill-assessments-quizzes#5836]
I'm submitting an ISSUE: please check one with "x"

- [x] New question{'s} 
- [ ] New assessment 
- [ ] Missed questions/answers 
- [ ] Request for new quiz/answers/...
- [ ] Documentation issue or request for ...
- [ ] ...

![WhatsApp Image 2023-06-12 at 00 15 06](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/assets/94980644/9ae341fe-72ae-4f4d-83ea-8d7bd955b0f5)

Kindly assign this work to me.

**Comment by Ebazhanov** [comment]
@sha0urya hello, thanks for the opening this issue, but is it related to Linkedin quiz?

**Comment by aryan-rohit** [comment]
@Ebazhanov assign this issue to me

**Comment by rahulmangla28** [comment]
Please assign this issue to me.

**Comment by Adi-456** [comment]
@Ebazhanov Kindly assign it to me.

**Comment by aryan-rohit** [comment]
@Ebazhanov  i have sent the pull request. please see it and merge it.

**Comment by Aloneking789** [comment]
This issue is closed or not?
