### ISSUE TITLE
Python Quiz - Wrong Answer

### ISSUE THREAD

**Issue by RinaldoNani** [Ebazhanov/linkedin-skill-assessments-quizzes#5976]
I'm submitting an ISSUE: please check one with "x."

- [ ] New question{'s} 
- [ ] New assessment 
- [ ] Missed questions/answers 
- [ ] Request for new quiz/answers/...
- [ ] Documentation issue or request for ...
- [x] WRONG ANSWER 

The answer to Q149 should be corrected (I double-checked by running the related code and watching the printed result). 
It should be the fourth choice (answer: A) and not the first (answer: C).

**Comment by alanJames00** [comment]
Hello @Ebazhanov, can I get this issue assigned to me please.

**Comment by RinaldoNani** [comment]
Is it up to me to close this issue? If it is, I will happily close it. 
I've seen that the correct answer issue was fixed. 
BTW: thanks!

**Comment by Ebazhanov** [comment]
@RinaldoNani, yes it can be closed, thank you for amazing work guys! 🍺  @alanJames00 🥇
