### ISSUE TITLE
JSON assessment failed using this repo

### ISSUE THREAD

**Issue by Eleiyas** [Ebazhanov/linkedin-skill-assessments-quizzes#5991]
- [X] Documentation issue

I just did the JSON assessment using only the answers you provide in this Repo and according to LinkedIn I now scored in the bottom 30% and completely failed it.

So, clearly something is drastically wrong with the provided answers here, as more than 70% of them (for the questions I got) were wrong.

**Comment by y4zy4z** [comment]
I completely agree, and moreover, I completed a JSON course and the answers provided here in this repo seems to be true. So I don't understand why the test was completely failed for me too. I was in the bottom 30% too...

**Comment by phaberest** [comment]
I just came here to check my answers as I got the same rank, but in all honesty I think they are correct.

I guess it might be a Linkedin issue with that assessment specifically.

**Comment by y4zy4z** [comment]
Thanks for your comment @phaberest , do you think we could send a group request to Linkedin ?

**Comment by MrSparrow01** [comment]
Agree with you. I checked it all and here a lot of mistakes.

**Comment by phaberest** [comment]
> Thanks for your comment @phaberest , do you think we could send a group request to Linkedin ?

I submitted a feedback but never got a y response. Have no idea where we could contact them 🥲

**Comment by y4zy4z** [comment]
> > Thanks for your comment @phaberest , do you think we could send a group request to Linkedin ?
> 
> I submitted a feedback but never got a y response. Have no idea where we could contact them 🥲

@phaberest I have submitted a feedback too, I keep you in touch if I get an answer :)



> Agree with you. I checked it all and here a lot of mistakes.

@MrSparrow01 Are you sure that you have identified mistakes in the answers provided here ? I am pretty sure with @phaberest that they are all correct.

**Comment by MrSparrow01** [comment]
> > > Thanks for your comment @phaberest , do you think we could send a group request to Linkedin ?
> > 
> > 
> > I submitted a feedback but never got a y response. Have no idea where we could contact them 🥲
> 
> @phaberest I have submitted a feedback too, I keep you in touch if I get an answer :)
> 
> > Agree with you. I checked it all and here a lot of mistakes.
> 
> @MrSparrow01 Are you sure that you have identified mistakes in the answers provided here ? I am pretty sure with @phaberest that they are all correct.

Yep, I'm sure.

**Comment by MrSparrow01** [comment]
> Agree with you. I checked it all and here a lot of mistakes.

Thanks, bro.

**Comment by pauloreis7** [comment]
same issue here, my linkedin test for JSON always fails even if I answer all the questions correctly
