### ISSUE TITLE
PHP new question

### ISSUE THREAD

**Issue by Manish814142** [Ebazhanov/linkedin-skill-assessments-quizzes#5995]
what does this code print?

try{
echo "bodacious<be>";
throw new Exception();
} catch (Exception $e) {
echo "egregious<br>";
} finally {
echo "excellent<br>";
"

Options are:-

1-
bodacious
excellent

2-
egregious
excellent

3
bodacious
egregious
excellent

4
bodacious
egregious

**Comment by alanJames00** [comment]
@Ebazhanov Can I get this assigned please?

**Comment by alanJames00** [comment]
I have created a PR after adding the question. Please review it @Ebazhanov.
