### ISSUE TITLE
New Python question

### ISSUE THREAD

**Issue by abagrevatil** [Ebazhanov/linkedin-skill-assessments-quizzes#6015]
I'm submitting an ISSUE:

- [X] New question

What is 17 % 15 equal to?

- [ ] 17
- [ ] 15
- [ ] 2
- [ ] 16

**Comment by alanJames00** [comment]
@Ebazhanov please assign this issue to me.

**Comment by Ebazhanov** [comment]
yes, thanks! Usually if you add as reference to your PR it will be closing automatically fyi! 

have a great day!
