### ISSUE TITLE
Incomplete answer

### ISSUE THREAD

**Issue by fsantamaria1** [Ebazhanov/linkedin-skill-assessments-quizzes#6029]
I'm submitting an ISSUE: please check one with "x"

- [ ] New question{'s} 
- [ ] New assessment 
- [ ] Missed questions/answers 
- [ ] Request for new quiz/answers/...
- [ ] Documentation issue or request for ...
- [x] Incomplete answer

The right answer for question 42 of the [OOP](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/main/object-oriented-programming/object-oriented-programming-quiz.md) test is not complete.

![image](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/assets/77696721/490fcdf9-4f7f-4927-9878-bcab05ef579f)

The complete text should be:
to separate class behavior from the more general to more specific

I got that from the actual test, but I forgot to take a screenshot.

**Comment by alanJames00** [comment]
@Ebazhanov assign this issue to me please
