### ISSUE TITLE
Wrong answer for C++ Question 1 

### ISSUE THREAD

**Issue by creme332** [Ebazhanov/linkedin-skill-assessments-quizzes#6054]
I'm submitting an ISSUE: please check one with "x"

- [ ] New question{'s} 
- [ ] New assessment 
- [ ] Missed questions/answers 
- [ ] Request for new quiz/answers/...
- [ ] Documentation issue or request for ...
- [x] Wrong answer

#5984 @moesocio recently changed the answer for [question 1](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/main/c%2B%2B/c%2B%2B-quiz.md#q1-what-is-printed-from-this-code) from `1` to `Error`. His corrected version of the code is only adding boilerplate C++ code (some import statements and a main function). 

However, I think that it is safe to assume that the boilerplate code is present when the code is executed (i.e the correct libraries have been imported for all code snippets and that the given snippet is found within a main function). The boilerplate code was most probably excluded from the question to make it easier to read. Therefore the correct answer for this question should be `1`.

If my assumption is incorrect, then most of the questions that have a code snippet will cause an execution error. For example, the code snippet in Q8 (shown below) will also cause an error if we paste the code as is in a compiler because there's no import statements etc..:
```cpp
std:: vector<int> *v1 = new std::vector<int>({1,2,3});
std:: vector<int> *v2;
v2=v1;
v1->push_back(4);
v2->push_back(5);
```
(For question 8, the answer is not `Error`)

**Comment by BHARGAVPATEL1244** [comment]
Yes Question 1 answer is 1

**Comment by BHARGAVPATEL1244** [comment]
@Ebazhanov can u assign me
