### ISSUE TITLE
fix for typo in question 51 in the bash quiz

### ISSUE THREAD

**Issue by Wingman4l7** [Ebazhanov/linkedin-skill-assessments-quizzes#6060]
I'm submitting an ISSUE: please check one with "x"

- [ ] New question{'s} 
- [ ] New assessment 
- [ ] Missed questions/answers 
- [ ] Request for new quiz/answers/...
- [ ] Documentation issue or request for ...
- [x ] Typo in question title

https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/main/bash/bash-quiz.md#q51-in-bash-what-does-the-comment-below-do -- question should read "In Bash, what does the command below do?"; it currently reads "In Bash, what does the comment below do?"

**Comment by nouri-muhammad** [comment]
Hi, I fixed the issue and pulled a request for it.

**Comment by Somil-Shukla** [comment]
Please assign this issue to me.

**Comment by ShubhamPaliwal03** [comment]
@Ebazhanov please assign this issue to me

**Comment by ShubhamPaliwal03** [comment]
i tried making a pr, but since the typo has already been corrected by
someone else and the issue has not been closed, there was no difference
between your and my repository, hence I could not make a pr.

**Comment by spandan0724** [comment]
@Ebazhanov Kindly close this issue, as it is already been solved.
