### ISSUE TITLE
java q46

### ISSUE THREAD

**Issue by kgoedert** [Ebazhanov/linkedin-skill-assessments-quizzes#6090]
The questions seems to have two correct answers

**Comment by abhaygzb15** [comment]
@kgoedert Please assign this issue to me.

**Comment by SanketPatil7467** [comment]
@Ebazhanov and @kgoedert , I carefully reviewed question I didn't saw any issue, there is only one answer for the question 46 which is mentioned in #6090 and it's answer is also correctly marked.
![q46](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/assets/98931495/7f252be1-3db0-49b8-980d-184680cb3d0b)

**Comment by hamexhanif** [comment]
> @Ebazhanov and @kgoedert , I carefully reviewed question I didn't saw any issue, there is only one answer for the question 46 which is mentioned in #6090 and it's answer is also correctly marked. ![q46](https://user-images.githubusercontent.com/98931495/271884918-7f252be1-3db0-49b8-980d-184680cb3d0b.png)

yes i agree,
the first choice clearly doesn't assign the "Waddles" to `name`, instead `waddles` the nameless Duck
the second one would be correct if the second line says `ducks.add(duck);`
the third one correctly created a duck and assign "Waddles" to `name`
the las one made am object called Waddles which is clearly wrong

**Comment by Rohxn16** [comment]
Hey I wan't to work on this issue

**Comment by ShubhamPaliwal03** [comment]
@kgoedert @Ebazhanov please assign this issue to me, let me resolve this

**Comment by ShubhamPaliwal03** [comment]
Great! I hope you had closed this earlier, I wasted a lot of my time in
these 2 issues.
