### ISSUE TITLE
java Q133

### ISSUE THREAD

**Issue by kgoedert** [Ebazhanov/linkedin-skill-assessments-quizzes#6092]
The code seems to be missing from the question

**Comment by Rohxn16** [comment]
Ok I will take up this issue and add the code

**Comment by Rohxn16** [comment]
@Ebazhanov  can you take a look at my PR say if it is alright? I am not 100% certain and am willing to make changes if there is anything wrong in the code.

**Comment by Rohxn16** [comment]
@Ebazhanov why do I see a cross (X) sign next to the verified tag? is there something wrong with my code?

**Comment by Ebazhanov** [comment]
i have no idea, can you pls share screenshot

**Comment by Rohxn16** [comment]
![Screenshot (36)](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/assets/142105763/bb598ece-d2c1-4e27-bca5-4e911ff5b3b2)
