### ISSUE TITLE
New question PHP

### ISSUE THREAD

**Issue by kushtra24** [Ebazhanov/linkedin-skill-assessments-quizzes#6099]
I'm submitting an ISSUE: please check one with "x"

- [ x] New question{'s} 
- [ ] New assessment 
- [] Missed questions/answers 
- [ ] Request for new quiz/answers/...
- [ ] Documentation issue or request for ...
- [ ] ...
![Screenshot_1](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/assets/288865/8305b5f4-77c7-46a8-b020-5b40fc9c3ca4)

**Comment by Cretus-iosDev** [comment]
Hi @kushtra24 
I've added the  PR. 
Please check and let me know if need any corrections.
