### ISSUE TITLE
Kotlin Q35 - Unsure about the answer

### ISSUE THREAD

**Issue by danielsacco** [Ebazhanov/linkedin-skill-assessments-quizzes#6109]
I'm submitting an ISSUE: please check one with "x"

- [ ] New question{'s} 
- [ ] New assessment 
- [ ] Missed questions/answers 
- [ ] Request for new quiz/answers/...
- [ ] Documentation issue or request for ...
- [x] Not sure about the selected answer

The options are:
- [x] `val max3 = a.max(b)` (Extension Function is One of the idiomatic Solutions in Kotlin)
- [ ] `val max = a > b ? a : b`
- [ ] `val max = if (a > b) a else b`
- [ ] `if (a > b) max = a else max = b`

I believe according https://kotlinlang.org/docs/idioms.html#if-expression that `val max = if (a > b) a else b` **_is_** an Idiom so I would choose that answer as the right one.
If you agree please let know so I submit a PR.

**Comment by bhoomikarao22** [comment]
val max = if (a > b) a else b
is the correct answer

**Comment by danielsacco** [comment]
Thanks @bhoomikarao22 .
Opened https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/pull/6151 according this issue.
