### ISSUE TITLE
C Q40:The question and answer don't seem to match

### ISSUE THREAD

**Issue by Baymax-Rob** [Ebazhanov/linkedin-skill-assessments-quizzes#6111]
I'm submitting an ISSUE: 

- [x] New question{'s} 
The question is to write a function that is included as a member of a structure a, but the checked answer is that the structure contains a pointer to void type, not a function pointer

**Comment by Naman065Malik** [comment]
Please Review My Above PR, I have Solved the Issue

**Comment by Priyanshuthapliyal2005** [comment]
is this issue closed @Naman065Malik @Ebazhanov

**Comment by Priyanshuthapliyal2005** [comment]
@Ebazhanov Please review the changes in this pull request #6673  and consider merging and close this issue. Thank you!
