### ISSUE TITLE
few new ques

### ISSUE THREAD

**Issue by vpandey1887** [Ebazhanov/linkedin-skill-assessments-quizzes#6119]
> I'm submitting an ISSUE: please check one with "x"

- [ ] New question{'s} 
- [ ] New assessment 
- [ ] Missed questions/answers 
- [ ] Request for new quiz/answers/...
- [ ] Documentation issue or request for ...
- [ ] ...
![Screenshot (4)](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/assets/78435248/3ec16cc8-114d-4adb-b942-cf918fcacfa5)
![Screenshot (3)](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/assets/78435248/e1ab3989-65f8-44f5-8029-1bcfd91f93c5)

**Comment by AnirudhKaranth** [comment]
@Ebazhanov I have created a PR.
