### ISSUE TITLE
New Questions: AWS Lambda

### ISSUE THREAD

**Issue by tuhinaww** [Ebazhanov/linkedin-skill-assessments-quizzes#6128]
I'm submitting an ISSUE: please check one with "x"

- [x] New question{'s} 
![image](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/assets/119059108/ed6ba013-bb1e-4f86-9520-b77c99e6d081)
![image](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/assets/119059108/51313dc4-98fc-4a63-9a4b-10d3efd216f3)

- [ ] New assessment 
- [ ] Missed questions/answers 
- [ ] Request for new quiz/answers/...
- [ ] Documentation issue or request for ...
- [ ] ...

**Comment by tuhinaww** [comment]
![image](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/assets/119059108/445fc831-a450-4cae-bbc0-4e6a5b6596ba)

**Comment by sarthak-dms** [comment]
I created a pull request for this issue.

**Comment by tuhinaww** [comment]
@sarthak-dms , I have already created a PR for this before, please check #6129 
![image](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/assets/119059108/bc06c4a0-ab85-4088-983a-1fdd8534e9a8)
Thanks & Regards
