### ISSUE TITLE
c++ question in c-(programming-language) file

### ISSUE THREAD

**Issue by ayush-yadavv** [Ebazhanov/linkedin-skill-assessments-quizzes#6136]
I'm submitting an ISSUE: please check one with "x"

- [ ] New question{'s} 
- [ ] New assessment 
- [ ] Missed questions/answers 
- [ ] Request for new quiz/answers/...
- [x] Documentation issue or request for relocating Q82 to C++ category. 
- [ ] ...

**Comment by UjjwalPardeshi** [comment]
can you assign me this task please .

**Comment by ayush-yadavv** [comment]
Already done

**Comment by mrinalproxy** [comment]
Assigned this issue to me
