### ISSUE TITLE
New question

### ISSUE THREAD

**Issue by imtayyabhayat** [Ebazhanov/linkedin-skill-assessments-quizzes#6149]
I'm submitting an ISSUE: please check one with "Django"

- [+] New question{'s} 
- 
![image_2023_10_02T09_32_16_368Z](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/assets/53258863/e73b23d3-11d5-48c7-b9c0-51b5cab2b71d)
![image_2023_10_02T09_32_07_154Z](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/assets/53258863/cb2b5e07-bddd-4534-ab83-8c7a2e55168c)

**Comment by Sumitwarrior7** [comment]
@Ebazhanov 
I want to add the 2 questions of django described above
Please assign me this

**Comment by Sumitwarrior7** [comment]
i have created a pr for above, please merge it
@Ebazhanov
