### ISSUE TITLE
IMovie

### ISSUE THREAD

**Issue by Bharath-KumarReddy** [Ebazhanov/linkedin-skill-assessments-quizzes#6157]
I found a new Skill Assessment  IMovie 

I want to add into this repo ;

can you please assign this to me , I am interested to contribute myself in hacktoberfest_23 : );

**Comment by MrAnayDongre** [comment]
You can simply open a PR.

**Comment by akashBharti001** [comment]
Hey! I would to work on this issue, Can you assign this to me?
