### ISSUE TITLE
Adding new Flutter Quiz

### ISSUE THREAD

**Issue by Miran-Firdausi** [Ebazhanov/linkedin-skill-assessments-quizzes#6205]
I'm submitting an ISSUE: please check one with "x"

- [ ] New question{'s} 
- [ ] New assessment 
- [ ] Missed questions/answers 
- [x] Request for new quiz/answers/...
- [ ] Documentation issue or request for ...
- [ ] ...
I think there should be a new quiz for flutter too. A lot of people use flutter and it would be great to have it too. I can create a new flutter quiz and 20 questions to it.

**Comment by ayush-yadavv** [comment]
yes, it would be helpful for everyone

**Comment by Miran-Firdausi** [comment]
Flutter quiz not available on linkedin.
