### ISSUE TITLE
JavaScript Q2，forEach and for statement different

### ISSUE THREAD

**Issue by makerhou** [Ebazhanov/linkedin-skill-assessments-quizzes#6242]
In JavaScript question 2, option 2, "A for statement is generic, but a forEach statement can be used only with an array."，the answer is not complete. This is because a new property called Set was introduced in ES6. The Set property is not an array, but it can still be used with the forEach property.

```
let s = new Set([1,2,3,4])
console.log(s instanceof Set)
// print  true
s.forEach(item=>console.log(item))
// 1
// 2
// 3
// 4
````

**Comment by Adi-456** [comment]
@makerhou   Kindly assign it to me.

**Comment by Adi-456** [comment]
Kindly assign this issue to me.

**Comment by Ayush-Vish** [comment]
Kindly assign  me this issue under hacktober fet.

**Comment by sonicdashh** [comment]
Please assign me this issue @Ebazhanov .

**Comment by sonicdashh** [comment]
I have opened PR #6260 addressing this issue.
Please review and merge .
@Ebazhanov
