### ISSUE TITLE
Add Spanish Translation for Final Cut Pro Quiz

### ISSUE THREAD

**Issue by aneeshd27** [Ebazhanov/linkedin-skill-assessments-quizzes#6259]
I'm submitting an ISSUE: please check one with "x"

- [ ] New question{'s} 
- [ ] New assessment 
- [ ] Missed questions/answers 
- [ ] Request for new quiz/answers/...
- [x] Documentation issue or request for ...
- [ ] ...

**Comment by sonicdashh** [comment]
Please assign me this issue .
