### ISSUE TITLE
React.js - new question and corrections

### ISSUE THREAD

**Issue by mmm4m5m** [Ebazhanov/linkedin-skill-assessments-quizzes#6505]
I'm submitting an ISSUE: please check one with "x"

- [x] New question{'s}
- [x] Missed questions/answers 

---

Similar questions. (Could be reordered or add "see also Question #")
Q36 and Q65
Q66 and Q71
Q10 and Q104
Q99, Q106, Q109
Q81 and Q114
Q6 and Q115
Q60 and Q118
Q113 and Q129
Q105 and Q130

---

Q19 - typo answer (4).

Q127 - the correct answer should be (3).
There is typo in the example - "setstate" must be "setState".

Q128 - typo "componenet".

Q129 - missing answer. The correct answer should be (1).

Q130 - the correct answer should be (4).

Q131 - the correct answer should be (1).

---

- [x] New question{'s} 

New question - very similar to Q53
![image](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/assets/995706/2c433afd-0096-4558-aed3-a8fd0cf7c16b)

**Comment by ihgazi** [comment]
I would like to work on this issue. Please assign it to me.
