### ISSUE TITLE
Suggesting to add question for solidity!!!

### ISSUE THREAD

**Issue by CodeBurnerProgramming** [Ebazhanov/linkedin-skill-assessments-quizzes#6522]
I was researching and found out that there are no repositories for solidity!!

**Comment by parthasdey2304** [comment]
well I agree on this wait i am doing the same and adding 10 questions for now!

**Comment by haxkd** [comment]
@CodeBurnerProgramming add questions according to skill assessments quizzes of linkedin.

**Comment by HimanshuMahto** [comment]
hey, @Ebazhanov could you please assign me this issue  to work  on.
