### ISSUE TITLE
Power Point new question

### ISSUE THREAD

**Issue by finfante-ia** [Ebazhanov/linkedin-skill-assessments-quizzes#6583]
I'm submitting an ISSUE: please check one with "x"

- [ X] New question{'s} 
-
![Captura de pantalla 2023-10-19 175307](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/assets/123666137/4c4e59b3-e30c-4384-9564-074d2d49f694)

**Comment by sonicdashh** [comment]
Please assign me this issue.
