### ISSUE TITLE
Bugs - Grammar mistake in README.md inside "Adding Answers " section.

### ISSUE THREAD

**Issue by ayushrakesh** [Ebazhanov/linkedin-skill-assessments-quizzes#6591]
I'm submitting an ISSUE: one grammar mistake inside "Adding Answers" section in README.md.

"**spelling and grammar is correct.**"  should be "**spelling and grammar are correct.**"

Below I have attached the screenshot of it.

![Screenshot (79)](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/assets/115995339/ea651ad4-3d2e-4b58-bb3e-bbc7e09c5b27)

Please assign this issue to me.

**Comment by haxkd** [comment]
@ayushrakesh make the changes and create PR

**Comment by ayushrakesh** [comment]
I have made a PR.
