### ISSUE TITLE
Linux - maybe 2 corrections and few notes

### ISSUE THREAD

**Issue by mmm4m5m** [Ebazhanov/linkedin-skill-assessments-quizzes#6651]
I'm submitting an ISSUE: please check one with "x"

- [x] Missed questions/answers

---

Duplicate:
Q68 and Q88

Very similar:
Q4 and Q47
Q24 and Q54

Similar:
Q13 and Q99

---

Q38. What is the /etc/hosts file used for?

Current answer:
(4) configuring DNS name servers

Most likely the correct answer is:
(1) resolving the local name

---

Q75. journald differs from traditional logging services such as rsyslogd and syslogd because its logs are _ by default.

Current answer:
(3) persistent

Looks like the correct answer is:
(4) not persistent

**Comment by sonicdashh** [comment]
Please assign me this issue.
Do add the hacktoberfest-accepted tag.
@Ebazhanov

**Comment by haxkd** [comment]
@mmm4m5m 
Q68 and Q88 is completely same (removed duplicate)
(Q4, Q47) and (Q24, Q54) are different of their examples (no changes required)
(Q13, Q99) are completely different (no changes required)
Q38 corrent answer is wrong (changes required)
Q75 the option is correct (no changes required)

**Comment by HimanshuMahto** [comment]
Is this still an issue if so, I would like to work on it @haxkd @Ebazhanov

**Comment by HimanshuMahto** [comment]
hey, @Ebazhanov I won't be able to do this issue as I'm traveling so, would be great if you assign someone else who can do it. Sorry

**Comment by dhirajs16** [comment]
Hey @Ebazhanov, is this issue still open? 
**Can I work on it?**

**Comment by Ebazhanov** [comment]
> Hey @Ebazhanov, is this issue still open? **Can I work on it?**

yes, go ahead 👍

**Comment by dhirajs16** [comment]
Hey! @Ebazhanov, would you mind adding a #hacktoberfest tag to it as you assign me for the issue?

**Comment by Ebazhanov** [comment]
> Hey! @Ebazhanov, would you mind adding a #hacktoberfest tag to it as you assign me for the issue?

should be already there 
![image](https://github.com/user-attachments/assets/fb8799ce-8ec9-40b9-ae50-2b05170896a3)
