### ISSUE TITLE
New question in JAVA

### ISSUE THREAD

**Issue by Manish814142** [Ebazhanov/linkedin-skill-assessments-quizzes#6652]
What kind of relationship does extends denote?
options:- 
is-a
has-a
was-a
uses-a

According to me: is-a

**Comment by sonicdashh** [comment]
Please assign me this issue.
Do add the hacktoberfest-accepted tag.
@Ebazhanov

**Comment by HimanshuMahto** [comment]
hey @Ebazhanov could you please assign me this issue would love to work on it.

**Comment by sonicdashh** [comment]
@Ebazhanov 
Please review PR #6703 and merge.

**Comment by HimanshuMahto** [comment]
Merge the conflict please do review it.

**Comment by Priyanshuthapliyal2005** [comment]
@Ebazhanov can you review the latest Pr #6878 which will close this issue #6703
