### ISSUE TITLE
Bash - 2 new questions, 1 correction, 1 note

### ISSUE THREAD

**Issue by mmm4m5m** [Ebazhanov/linkedin-skill-assessments-quizzes#6664]
I'm submitting an ISSUE: please check one with "x"

- [x] New question{'s}
- [x] Missed questions/answers

---

Duplicate:
Q52 and Q81

---

Q42. For the script to print "Is numeric" on screen, what would the user have to enter when prompted?

Current answer:
(4) Due to a syntax error it is impossible to get the script to print "Is numeric"

The correct answer should be:
(2) The user would have to enter the character sequence of ^[0-9]]+$ Only this will prove to be true and "Is numeric" would be printed on the screen due to incorrect syntax. By encapsulating the regular expression in double quotes every match will fail except the text string ^[0-9]+$

(Except if you consider it misleading and intentionally wrong answer, because of the mistake in the first occurence of "^[0-9]+$".)

---

- [x] New question{'s} 

![image](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/assets/995706/de4525cc-784d-4228-8402-d41ff44ac350)

![image](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/assets/995706/7e4cecba-9456-4f7f-9a86-e7f43a300b6a)

**Comment by sonicdashh** [comment]
Please assign me this issue.
Do add the hacktoberfest-accepted tag.
@Ebazhanov

**Comment by Priyanshuthapliyal2005** [comment]
can i work on this issue to remove the duplicate and new questions.
@Ebazhanov

**Comment by Priyanshuthapliyal2005** [comment]
@Ebazhanov Please review the changes in this pull request #6678  and consider merging. Thank you!
here in this pr  i add Q90 and Q91 in bash.
Thank you
