### ISSUE TITLE
Microsoft Access : No answers for Q45-Q49

### ISSUE THREAD

**Issue by Sumitwarrior7** [Ebazhanov/linkedin-skill-assessments-quizzes#6788]
I'm submitting an ISSUE: please check one with "x"

- [X] Missed questions/answers 

Q 45, 46, 47, 48, 49 must be answered because right now they are unanswered

**Comment by Sumitwarrior7** [comment]
![Screenshot from 2023-10-24 23-15-33](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/assets/108853577/78c21b0d-f316-4370-862e-ceea5fd34754)

**Comment by Sumitwarrior7** [comment]
@Ebazhanov Assign me this issue please

**Comment by alpha2207** [comment]
@Ebazhanov Completed this please check and merge. ( #6790 )

**Comment by Priyanshuthapliyal2005** [comment]
@Ebazhanov close this isssue
