### ISSUE TITLE
[iMovie assessment]  Missed questions/answers

### ISSUE THREAD

**Issue by Maxozs** [Ebazhanov/linkedin-skill-assessments-quizzes#6934]
### > I'm submitting an ISSUE:

- [x] Missed questions/answers 

![88](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/assets/151802032/65324497-c4d9-4831-b013-4795fcd524d5)
![555](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/assets/151802032/080a2d35-0539-45c2-8a34-d3080ef5a7b6)
![99](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/assets/151802032/9afcf797-9e3f-4189-9750-5fee05ef5076)

**Comment by haxkd** [comment]
solved #6938 6938
