### ISSUE TITLE
New Questions For Git 40 Question Test. Need help answering.

### ISSUE THREAD

**Issue by xLikeABox** [Ebazhanov/linkedin-skill-assessments-quizzes#6969]
I'm submitting an ISSUE: please check one with "x"

- [
![IMG_2532](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/assets/153853068/f6f48ba9-6b4a-4265-8c1f-3f4777682834)
![IMG_2533](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/assets/153853068/01fadaa6-d18a-40ec-95dc-76fb0412d218)
![IMG_2534](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/assets/153853068/a73f895c-5e96-47d9-b89b-f3b1ccf299e4)
![IMG_2535](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/assets/153853068/f97984f8-0212-4c60-8624-98f77018d162)
![IMG_2536](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/assets/153853068/98c534cf-48c5-4dae-b5e5-e9af305180bc)
![IMG_2537](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/assets/153853068/47861b04-1d36-4d5f-947a-e24ff1dde5c9)
![IMG_2538](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/assets/153853068/adb256ec-731d-4f92-af73-205623ff522f)
![IMG_2539](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/assets/153853068/b4126d7d-8fae-4bea-a627-3035011745e5)
![IMG_2540](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/assets/153853068/0b93073d-e498-43a3-abac-7eef8f286604)
![IMG_2541](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/assets/153853068/325f88e9-0ab4-4dd7-a2c9-cab23ee3ca0d)
![IMG_2542](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/assets/153853068/357cf0fc-f9b3-4eca-878c-c0055ec81ae8)
![IMG_2543](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/assets/153853068/09d521cd-6b1b-4c7a-89bc-42a0b2e3c934)
![IMG_2544](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/assets/153853068/f1314d39-1e46-4c6b-8857-8fff9ad3ba8b)
![IMG_2545](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/assets/153853068/12088412-70f0-4be0-bf56-2f9f24bd20d7)
![IMG_2546](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/assets/153853068/b0264025-32fd-4e56-a66f-ab9eb55b540a)
![IMG_2547](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/assets/153853068/e1828b8a-7492-4342-9d32-a4eaf42e2b2c)
![IMG_2548](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/assets/153853068/bbc6c90c-23cf-4262-805a-bdfc7c099592)
![IMG_2549](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/assets/153853068/8de55433-0eb2-4cb3-a5b2-69f88c84bc2f)
![IMG_2550](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/assets/153853068/4197f156-144c-4462-876b-7a049d7d229b)
![IMG_2551](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/assets/153853068/83ac4cb4-6bf7-4d2f-9113-21f80c775be9)
![IMG_2552](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/assets/153853068/2526f5ec-1874-4ccb-b848-0b0537ce56c5)
![IMG_2553](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/assets/153853068/79388f10-983a-4a7c-a512-eaae1c1c0b6b)
![IMG_2554](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/assets/153853068/3ec39480-494f-4454-8860-7cc0d49facc1)
![IMG_2555](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/assets/153853068/7eb7a739-65b4-4d00-bdf2-d31d0cd50df3)
![IMG_2556](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/assets/153853068/31de5f9d-f3b1-470e-9077-9f5b73839bbe)
![IMG_2557](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/assets/153853068/d4284c7a-5ba2-4372-a187-9f89aa0a320a)
![IMG_2558](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/assets/153853068/58ffa08f-9314-4f53-9a9a-e5de69646a22)
![IMG_2559](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/assets/153853068/e1bc070b-0905-4311-b2e3-8447de9654a2)
![IMG_2560](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/assets/153853068/097b536b-8246-4b7a-8de4-a41dacf4b5d8)
![IMG_2561](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/assets/153853068/34c3772d-a2bd-4036-94ea-230abb9a870c)
![IMG_2562](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/assets/153853068/81a367f6-5e78-4435-8358-bcc9fc756e5e)
![IMG_2563](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/assets/153853068/83ac5aa4-e12c-43ea-9e66-e4ff2eb4b861)
![IMG_2564](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/assets/153853068/f8981593-1792-46a1-8308-e59d97c1a4ea)
![IMG_2565](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/assets/153853068/c8d3f62b-55fc-4a5d-88e6-577784260efe)
![IMG_2566](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/assets/153853068/847a2d66-d678-461c-a746-b089c8fbbd18)
![IMG_2567](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/assets/153853068/f78f5f7b-92b3-4067-bef5-98ab225e98e5)
![IMG_2568](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/assets/153853068/e0a7897e-60d8-42c0-a1d8-d911f6cd8a15)
![IMG_2569](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/assets/153853068/ef2d52dd-e1d8-4200-82f5-ccc0ddbb0ac3)
![IMG_2570](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/assets/153853068/9a3e0dcf-ffcb-4c4a-b718-c0d1cb760171)
![IMG_2571](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/assets/153853068/cd66fb16-f01f-40c9-9cd1-ec662a6524af)
![IMG_2572](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/assets/153853068/8b0ae024-7bbc-44fb-bf43-0ca192dece98)
![IMG_2573](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/assets/153853068/efcaed63-2135-4861-81b3-9f521020c3c3)
x] New question{'s} 
- [ ] New assessment 
- [ ] Missed questions/answers 
- [ ] Request for new quiz/answers/...
- [ ] Documentation issue or request for ...
- [ ] ...

**Comment by monkrus** [comment]
@xLikeABox Can you please save it as **one** file, jpeg or pdf, and attach here?

**Comment by xLikeABox** [comment]
@monkrus Not a problem Here ya go! Thanks!

[Git 40 Questions.pdf](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/files/13811089/Git.40.Questions.pdf)

**Comment by monkrus** [comment]
@xLikeABox was not able to convert your file into readable text file. If you can provide one, will be happy to assist with chatbot for you.

**Comment by xLikeABox** [comment]
@monkrus not sure the easiest way to make a pic into a text file. I can take the test two more times. I can grab the questions by copy pasting them maybe from the test to help from having to type out 40 questions. I need help answering the 40 questions correctly because this isn't a passed exam. Hopefully by taking pics of the questions someone can answer them correctly.

[GIT 40 Question.docx](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/files/13821426/GIT.40.Question.docx)

**Comment by monkrus** [comment]
Your text is mostly clear, but there are a couple of minor grammar adjustments for improved readability:
To get text from the image, the file has to be OCR'd. I tried several options, but the output file comes out unformatted/unreadable (see below). The options you might try are Adobe Acrobat (requires a subscription), SimpleView, or maybe OneNote. If your result is no different from mine, it looks like a time-consuming job to me. Once we get it in a readable text file (Word, TXT, PDF, etc.), we can verify the answers and add them to the chatbot so that you can find those answers easily.
[Git.40.Questions_scan.docx](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/files/13823141/Git.40.Questions_scan.docx)

**Comment by xLikeABox** [comment]
I cannot copy and paste I will have to type it out by hand. Once I am done chatbot will help answer it correctly and wont mess up on questions that are scenario based, require multiple correct choices, and wont has issues with diagrams? Does it matter how I make the ABCD answers?

**Comment by xLikeABox** [comment]
Does this work so far? I got this type and still working on it. Just want to make sure the chatbot will work with this format.

[Uploading GIT 40 Question.docx…]()

**Comment by monkrus** [comment]
@xLikeABox The format we want has to be readable by the chatbot. An example would be a text file, in other words, something that can be copied and pasted. The file you have is not good for a chatbot as a chatbot most of the time can only read from text. You might literally save time by manually typing this information in a new pdf file. Or you can just simply use Chat GPT to help you answer those questions (e.g. android version of it allows to use voice commands). It all depends on how much time you have during the test.

**Comment by xLikeABox** [comment]
Passing score with 85%

All correct answers are marked in Bold

1.	You’re looking at a repository page and click a folder name to open it. You have code search on, so you land in the code view. What is the quickest way to find a file on a path in your repo?
A.	Press the slash (/) key and then the T key.
B.	Go to advanced search.
**C.	From the search menu, select Path.**
D.	Press the T key.
2.	How do you save a search that you use often using GitHub?
A.	Click Save on the search box.
B.	Click Save in the advanced search menu.
C.	Click Save on the search results page.
**D.	Bookmark the search results page.** 
3.	Which of these in NOT a label that GitHub creates by default?
A.	Bug
B.	Documentation
C.	Wontfix
**D.	Repo**
4.	What is the fastest way to start a search using the GitHub web page?
**A.	Press the slash (/) key on any page of the site.**
B.	Click the Search tab from the GitHub navigation.
C.	Click the Advanced Search Link.
D.	Click the search box and type your search query.
5.	Assigning an issue to a person implies that they ___.
A.	Will get a notification asking them to review the issue.
**B.	Are responsible for resolving the issue.**
C.	Are being informed of the issue’s details.
D.	Supervise the team resolving the issue.
6.	What does a Template repository do?
A.	It creates a live demo of the current repository for training. 
**B.	It allows you to create a default structure and files based on the current repository.**
C.	It lets you archive and store project settings.
D.	It imports another project’s settings to the current project.
7.	You’re creating an action for the GitHub Marketplace. Why is it important to create a release?
A.	To allow you to create .zip files that you can easily share
B.	To initiate a continuous integration process
**C.	To package your software so that it can become available through the Github Marketplace**
D.	To create workflows and automate the process of generating software
8.	What are two ways to help Copilot give you more accurate suggestions?
A.	Add instructions in parentheses.
B.	Use shorthand, but accurate, descriptors.
**C.	Add context in comments.**
D.	Use concise variable names.
**E.	Use descriptive function names.**
9.	What is the main purpose of the Chat panel?
A.	To search for answers in the current project’s repository
B.	To chat with other developers who are working at your company
**C.	To have a conversational discussion with the AI behind Copilot**
D.	To get a list possible answers to a question
10.	While doing a code review, you want to start an issue by highlighting a function that takes up several lines of code. What is the fastest way to do this in code view?
**A.	Click the first line number with the function, click the last line number to select a range, then in the hamburger menu select Reference in new issues**
B.	Copy the code and start a new issue, then use backticks around the function to create the issue
C.	Select the function with the mouse, then right click and select reference in new issue
D.	Click the line number with the function and select reference function in an issue
11.	You’re reviewing a file in a repository and want to link to the current version of the file, even if it gets updated later. How can you achieve this?
A.	Go to the Code tab and click Download zip
B.	Right click the code text and select Permalink
**C.	Click Permalink on the code view**
D.	Copy the URL from the address bar
12.	You’re organizing a desktop application project. You want to use an overview f your project statuses and be able to drag and drop issues. Which view would you use?
**A.	Board**
B.	Overview
C.	Roadmap
D.	Table
13.	You’re in the repo for a specific project while working on an app module. You want to look for some of the docs you’ve been working on, which you wrote in markdown. To quickly look in your own repo for all files with a markdown extension, press the slash (/) button on the keyboard while on the repository page and type ___.
A.	Path:*.md
B.	Grep:*.md
**C.	Code:*.md**
D.	Ext:*.md
14.	In GitHub Projects, how can you assign an issue to a collaborator?
A.	Label the item with their username.
**B.	Select their username from the Assignees field.**
C.	Move the item to their column in the Boards view.
D.	Add their handle in the comments.
15.	Why should you include a descriptive function name when writing code with Copilot?
A.	It helps Copilot add more variables to a function.
B.	It trains the algorithm for the next time a GitHub client answers the question.
**C.	It helps Copilot have better context for code assistance and generation.**
D.	The function names are not fed to Copilot and are ignored by the AI.
16.	You are working on a project that uses a Python library and you want to find an example of how to use a function across all public repositories. Which part of GitHub’s platform would you use?
A.	Issues.
B.	Discussions
C.	Projects
**D.	Search**
17.	Working late on a project, you need to find an issue that was assigned to you. What query do you type?
**A.	Is:issue assignee:username**
B.	Is:issue user:username
C.	Issue:issue user:username
D.	assignee:username is:rep
18.	you are working on an AI app and need to add information on project tables about the AI model being targeted. What feature allows you to do this?
**A.	Custom fields**
B.	Comments
C.	Pull requests
D.	Custom properties
19.	What feature does the shortcut /table activate when used inside a GitHub comment section?
A.	A data visualization table
**B.	A markdown table structure**
C.	An HTML table structure
D.	A table of contents
20.	How can you get better suggestions when creating functions?
**A.	Type “function” and then add a detailed and expressive function name.**
B.	Type “function” and then press Ctrl+/ (Windows) or Command +/ (Mac).
C.	Include variables in the parentheses.
D.	Use consistent formatting for your function names.
21.	What does the RUN command do in a Dockerfile?
A.	 It allows you to specify which type of machine to procure.
B.	It helps run your workflows.
C.	It fires up an additional container
**D.	It allows you to execute a shell command during the image generation** process
22.	How can you ensure that you are matching an exact combination of words?
A.	Enclose your query in parentheses
B.	Use the exact: qualifier
**C.	Put the series of words in quotes**
D.	Add the AND operator to the end of your query
23.	What is the main function of the Entrypoint instruction in a Dockerfile?
A.	It gives instructions to the Docker container to follow before it loads
**B.	It executes a script when the docker container starts.**
C.	It serves as the first file that an editor opens when it loads the container.
D.	It indicates a specific command to be run during the Docker image build process
24.	Inside a GitHub action, which keyword do you use to specify the operating system to run jobs?
A.	Hardware
**B.	Runs-on**
C.	Machine
D.	Os
25.	How can you get additional context from other files in your code?
A.	Right-click a file and add it to context
**B.	Open additional tabs with some of your codes; they will be in Copilot context**
C.	Create a comment with the list of files you want Copilot to have context from
D.	Highlight the files you want to add context to form the file sidebar
26.	When creating a release, which of these would count as a valid release format?
A.	*3.2.4
B.	@3.2.4
C.	#3.2.4
**D.	V3.2.4**
27.	What is the maximum number of suggestions the completions panel gives at one time?
A.	100
**B.	5**
C.	10
D.	8
28.	You are looking for markdown files in a project, so you type in the following search: repo:planetoftheweb/slides_vue3 *.md. What does the commits section in the filter by siderbar show?
A.	Any commits that you are mentioned on
**B.	The commits that match your search query**
C.	The most recent commits
D.	All the commits you personally made
29.	Your company worked on a popular utility module and you remember that it had between 100 and 200 stars. How would you write qualifiers that would limit that search?
**A.	Stars:100..200**
B.	Stars: 100 or 200
C.	Stars:100,200
D.	Stars:100-200
30.	What’s a good way to use the filter feature to display only the issues that are assigned to a specific user?
A.	Owner: username
B.	Assigned:username
**C.	Assignee:username**
D.	User: username
31.	Which feature is enabled for a checklist when added to the description of an issue?
A.	You can convert an individual checklist item to a GitHub issue.
**B.	You can mark the checklist items as completed**
C.	You can link directly to an issue and show a popup with issue information
D.	You can reorder the checklist items
32.	You are building a visual studio code extension and you remember that microsoft has sample code you could learn from. Which search would yield the fewest results while searching all of GitHub for “vscode” repos from “microsoft”?
**A.	Owner:microsoft repo:vscode**
B.	Vscode
C.	Company:microsoft repo:vscode
D.	Microsoft/vscode
33.	What language can you use to create a GitHub action workflow?
**A.	YAML**
B.	Javascript
C.	JSON
D.	Python
34.	In GitHub Projects, what does a blue dot next to a table view represent?
A.	New views have been added to the project
**B.	New items have been added to the view**
C.	The system has a notification about the table view
D.	Modifications have been made to the view
35.	Which of these in not a slash command available in comment field?
A.	/details
B.	/code block
C.	/table
**D.	/issue**
36.	Select two ways you can add an emoji to an issue in GitHub.
A.	Type a hashtag (#) and then the ID of emoji
B.	Press Ctrl +C (Mac) and then select the emoji from the drp-down
**C.	Select the emoji menu in the editor toolbar**
D.	Paste an emoji from the clipboard
**E.	Type a colon (;) and then the name of the emoji**
37.	You can sell all of the chats you’ve had with copilot in the ___ panel.
A.	Note
**B.	History**
C.	Completions
D.	Chat
38.	Which command would you use to install python on a decker image in a dockerfile?
A.	Run install python3
B.	Run pip install python3
**C.	Run apt-get install python3**
D.	Run python3 install
39.	You created some excellent drafts for your project. You will convert a draft to an issue when you want to ___.
A.	Mark if for deletion
B.	Assign it a due date
C.	Assign the issue to someone
**D.	Start working on the issue**
40.	What are the two quickest ways to use GitHub search from any page on the site?
A.	Press and hold Ctrl (Windows) or Command (Mac). Then press S.
B.	Press the Esc key
**C.	Press the S Key
D.	Press the slash (/) key**

**Comment by monkrus** [comment]
### Here is what **ChatGPT** says about your answers, Care to double-check?


1. **Quickest way to find a file on a path in your repo?**
   - Correct Answer: **A. Press the slash (/) key and then the T key.**

2. **How to save a search you use often using GitHub?**
   - Correct Answer: **A. Click Save on the search box.**

3. **NOT a label that GitHub creates by default?**
   - Correct Answer: **D. Repo**

4. **Fastest way to start a search using the GitHub web page?**
   - Correct Answer: **A. Press the slash (/) key on any page of the site.**

5. **Assigning an issue to a person implies that they ___?**
   - Correct Answer: **B. Are responsible for resolving the issue.**

6. **Purpose of a Template repository?**
   - Correct Answer: **B. It allows you to create a default structure and files based on the current repository.**

7. **Why is it important to create a release for a GitHub Marketplace action?**
   - Correct Answer: **C. To package your software so that it can become available through the Github Marketplace.**

8. **Two ways to help Copilot give more accurate suggestions?**
   - Correct Answers: **C. Add context in comments.** and **E. Use descriptive function names.**

9. **Main purpose of the Chat panel?**
   - Correct Answer: **C. To have a conversational discussion with the AI behind Copilot.**

10. **Fastest way to start an issue during a code review?**
    - Correct Answer: **C. Select the function with the mouse, then right-click and select reference in new issue.**

11. **Link to the current version of a file in a repository even if it gets updated later?**
    - Correct Answer: **B. Right-click the code text and select Permalink.**

12. **View to use for organizing a desktop application project with drag and drop issues?**
    - Correct Answer: **A. Board.**

13. **Searching for markdown files in your repo using the slash (/) button?**
    - Correct Answer: **C. Code:*.md**

14. **How to assign an issue to a collaborator in GitHub Projects?**
    - Correct Answer: **B. Select their username from the Assignees field.**

15. **Why include a descriptive function name when writing code with Copilot?**
    - Correct Answer: **C. It helps Copilot have better context for code assistance and generation.**

16. **Searching for examples of using a Python function across all public repositories?**
    - Correct Answer: **D. Search.**

17. **Query to find an issue assigned to you while working late on a project?**
    - Correct Answer: **A. Is:issue assignee:username.**

18. **Adding information about an AI model in project tables?**
    - Correct Answer: **A. Custom fields.**

19. **Feature activated by the shortcut /table in GitHub comments?**
    - Correct Answer: **B. A markdown table structure.**

20. **Getting better suggestions when creating functions with Copilot?**
    - Correct Answer: **C. Include variables in the parentheses.**

21. **Purpose of the RUN command in a Dockerfile?**
    - Correct Answer: **D. It allows you to execute a shell command during the image generation process.**

22. **Ensuring an exact combination of words in a GitHub search?**
    - Correct Answer: **C. Put the series of words in quotes.**

23. **Main function of the Entrypoint instruction in a Dockerfile?**
    - Correct Answer: **B. It executes a script when the docker container starts.**

24. **Keyword for specifying the operating system in GitHub Action jobs?**
    - Correct Answer: **D. Os.**

25. **Getting additional context from other files in your code with Copilot?**
    - Correct Answer: **C. Create a comment with the list of files you want Copilot to have context from.**

26. **Valid release format when creating a release?**
    - Correct Answer: **D. V3.2.4.**

27. **Maximum number of suggestions the completions panel gives at one time?**
    - Correct Answer: **C. 10.**

28. **Commits section in the filter by sidebar when searching for markdown files?**
    - Correct Answer: **C. The most recent commits.**

29. **Qualifiers to limit a search for repositories with 100-200 stars?**
    - Correct Answer: **A. Stars:100..200.**

30. **Filter feature to display only issues assigned to a specific user?**
    - Correct Answer: **C. Assignee:username.**

31. **Feature enabled for a checklist in the issue description?**
    - Correct Answer: **B. You can mark the checklist items as completed.**

32. **Searching for Microsoft's vscode repos with the fewest results?**
    - Correct Answer: **A. Owner:microsoft repo:vscode.**

33. **Language to create a GitHub Action workflow?**
    - Correct Answer: **A. YAML.**

34. **Blue dot next to a table view in GitHub Projects?**
    - Correct Answer: **B. New items have been added to the view.**

35. **Not a slash command available in the comment field?**
    - Correct Answer: **D. /issue.**

36. **Two ways to add an emoji to an issue in GitHub?**
    - Correct Answers: **C. Select the emoji menu in the editor toolbar.** and **D. Paste an emoji from the clipboard.**

37. **Panel to see all chats with Copilot?**
    - Correct Answer: **C. Completions.**

38. **Command to install Python on a Docker image in a Dockerfile?**
    - Correct Answer: **C. Run apt-get install python3.**

39. **Converting a draft to an issue when you want to?**
    - Correct Answer: **D. Start working on the issue.**

40. **Two quickest ways to use GitHub search from any page on the site?**
    - Correct Answers: **A. Press and hold Ctrl (Windows) or Command (Mac). Then press S.** and **D. Press the slash (/) key.**

**Comment by monkrus** [comment]
@xLikeABox If you are good to go, it could be added to the chatbot.

**Comment by monkrus** [comment]
If no more help is needed, closing.
