### ISSUE TITLE
Wrong or right answer for #55 [MAVEN]

### ISSUE THREAD

**Issue by MiloosN5** [Ebazhanov/linkedin-skill-assessments-quizzes#7008]
Hey! I'm wondering is "/src/main/WEB-INF" the right answer for Q55 [Maven]? According to source [(maven.apache.org)](https://maven.apache.org/plugins/maven-war-plugin/war-mojo.html) it should be "${basedir}/src/main/webapp" or I missunderstood something?

**Comment by jdegand** [comment]
Both answers may be correct.   

The default resource directory for all Maven projects is `src/main/resources` which will end up in `target/classes` and in `WEB-INF/classes` in the WAR. The directory structure will be preserved in the process -- [Maven](https://maven.apache.org/plugins/maven-war-plugin/examples/adding-filtering-webresources.html) .
