### ISSUE TITLE
Quickbook Online Quize

### ISSUE THREAD

**Issue by dgohel01** [Ebazhanov/linkedin-skill-assessments-quizzes#757]
I want to take Quickbook quize. Can you please post that here?
It will be a big healp.
Thank you!

**Comment by tik9** [comment]
@dgohel01 Can you send a link and give more info. We will then look into it.

**Comment by dgohel01** [comment]
@tik9 Quize Link is https://www.linkedin.com/help/linkedin/answer/115834/quickbooks-skill-assessment?lang=en

This Quize is about "QuickBooks", which is a software used for accounting and bookkeeping purposes.

**Comment by Ebazhanov** [comment]
Guys @dgohel01, @tik9 => let's say thank you to @rradfar for adding this new quiz! :tada:
https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/master/quickbooks/quickbooks-quiz.md
