### ISSUE TITLE
LinkedIn Skill Assessment for VBA

### ISSUE THREAD

**Issue by QB628** [Ebazhanov/linkedin-skill-assessments-quizzes#834]
May I know if there is any questions and answers for VBA?

**Comment by Ebazhanov** [comment]
good question @QB628, I have checked there is no VBA question yet :disappointed_relieved:

**Comment by QB628** [comment]
Just did the quizzes requested by a recruiter for two times, but both failed.🤮

**Comment by Ebazhanov** [comment]
Understand :+1:

**Comment by tik9** [comment]
Proposing to close. VBA is out of date, there is Powershell and C Sharp as newer tools.

**Comment by Ebazhanov** [comment]
Thank you for the answer @tik9, I agree with you, but @QB628 also right because linkedin provide this VBA quiz. So I still think it is good to have this `good first issue` 
![image](https://user-images.githubusercontent.com/13170022/102257442-096a0580-3f0d-11eb-8407-c836ec4b916e.png)

**Comment by tik9** [comment]
The quiz is online, now we need the missing answers. Come on guys.
