### ISSUE TITLE
Need Kotlin Assessment 

### ISSUE THREAD

**Issue by karouAhmed** [Ebazhanov/linkedin-skill-assessments-quizzes#996]

**Comment by mohamedebrahim96** [comment]
<img width="956" alt="1" src="https://user-images.githubusercontent.com/16405013/105494227-ed0f7480-5cd3-11eb-8ba1-1cbdcf324741.png">
<img width="956" alt="2" src="https://user-images.githubusercontent.com/16405013/105494233-ef71ce80-5cd3-11eb-802c-94acfe0c901f.png">
<img width="956" alt="3" src="https://user-images.githubusercontent.com/16405013/105494237-f13b9200-5cd3-11eb-86a1-ab66cf2357c9.png">
<img width="956" alt="4" src="https://user-images.githubusercontent.com/16405013/105494239-f1d42880-5cd3-11eb-8355-f688494aee10.png">
<img width="956" alt="5" src="https://user-images.githubusercontent.com/16405013/105494240-f26cbf00-5cd3-11eb-8e78-87596505f460.png">
<img width="956" alt="6" src="https://user-images.githubusercontent.com/16405013/105494242-f3055580-5cd3-11eb-8624-32a56ecac073.png">
<img width="956" alt="7" src="https://user-images.githubusercontent.com/16405013/105494245-f39dec00-5cd3-11eb-92f5-5afab7c1ac3a.png">
<img width="956" alt="8" src="https://user-images.githubusercontent.com/16405013/105494248-f4368280-5cd3-11eb-9d0e-de83745ae0fd.png">
<img width="956" alt="9" src="https://user-images.githubusercontent.com/16405013/105494251-f4cf1900-5cd3-11eb-85be-e12b177b30ac.png">
<img width="956" alt="10" src="https://user-images.githubusercontent.com/16405013/105494253-f567af80-5cd3-11eb-85d9-41f88d9c60a3.png">
<img width="956" alt="11" src="https://user-images.githubusercontent.com/16405013/105494255-f6004600-5cd3-11eb-89e3-de899acbadc7.png">
<img width="956" alt="12" src="https://user-images.githubusercontent.com/16405013/105494256-f698dc80-5cd3-11eb-8e36-511cea5f64b4.png">
<img width="956" alt="13" src="https://user-images.githubusercontent.com/16405013/105494260-f7317300-5cd3-11eb-9870-e1c4181b83d5.png">
<img width="956" alt="14" src="https://user-images.githubusercontent.com/16405013/105494262-f7ca0980-5cd3-11eb-8bd4-9a79961573fb.png">
<img width="956" alt="15" src="https://user-images.githubusercontent.com/16405013/105494264-fa2c6380-5cd3-11eb-9e40-f4bcfc8976e6.png">
<img width="978" alt="Screen Shot 2021-01-22 at 16 15 52" src="https://user-images.githubusercontent.com/16405013/105494265-fac4fa00-5cd3-11eb-9970-a84bb58e909c.png">
<img width="978" alt="Screen Shot 2021-01-22 at 16 16 03" src="https://user-images.githubusercontent.com/16405013/105494267-fb5d9080-5cd3-11eb-9497-139c775c8304.png">
<img width="978" alt="Screen Shot 2021-01-22 at 16 16 11" src="https://user-images.githubusercontent.com/16405013/105494269-fbf62700-5cd3-11eb-92e8-71aa2124c17a.png">
<img width="978" alt="Screen Shot 2021-01-22 at 16 16 21" src="https://user-images.githubusercontent.com/16405013/105494271-fbf62700-5cd3-11eb-837b-ae87ab14bb93.png">
<img width="978" alt="Screen Shot 2021-01-22 at 16 16 29" src="https://user-images.githubusercontent.com/16405013/105494274-fc8ebd80-5cd3-11eb-8646-6dce5e44b92b.png">
<img width="978" alt="Screen Shot 2021-01-22 at 16 16 34" src="https://user-images.githubusercontent.com/16405013/105494277-fd275400-5cd3-11eb-9941-ae61b17fa6bb.png">
<img width="978" alt="Screen Shot 2021-01-22 at 16 16 40" src="https://user-images.githubusercontent.com/16405013/105494280-fdbfea80-5cd3-11eb-9395-2c8643998231.png">
<img width="978" alt="Screen Shot 2021-01-22 at 16 16 46" src="https://user-images.githubusercontent.com/16405013/105494283-fe588100-5cd3-11eb-90d7-7e4c43e63c5c.png">
<img width="978" alt="Screen Shot 2021-01-22 at 16 17 01" src="https://user-images.githubusercontent.com/16405013/105494285-fe588100-5cd3-11eb-944e-5cd5b0380352.png">
<img width="978" alt="Screen Shot 2021-01-22 at 16 17 11" src="https://user-images.githubusercontent.com/16405013/105494289-fef11780-5cd3-11eb-9bc4-7b6be4dcf7bf.png">
<img width="978" alt="Screen Shot 2021-01-22 at 16 17 24" src="https://user-images.githubusercontent.com/16405013/105494291-ff89ae00-5cd3-11eb-9162-058675f1a6c7.png">
<img width="978" alt="Screen Shot 2021-01-22 at 16 17 38" src="https://user-images.githubusercontent.com/16405013/105494293-ff89ae00-5cd3-11eb-96c2-5be62adb924a.png">
<img width="978" alt="Screen Shot 2021-01-22 at 16 17 44" src="https://user-images.githubusercontent.com/16405013/105494295-00224480-5cd4-11eb-9353-2a90ea1296c3.png">
<img width="978" alt="Screen Shot 2021-01-22 at 16 17 50" src="https://user-images.githubusercontent.com/16405013/105494297-00badb00-5cd4-11eb-8c82-e206c11af65e.png">

**Comment by mohamedebrahim96** [comment]
<img width="936" alt="Screen Shot 2021-02-19 at 21 36 00" src="https://user-images.githubusercontent.com/16405013/108540750-015a8780-72fb-11eb-9c94-02ebc0f91485.png">
<img width="872" alt="Screen Shot 2021-02-19 at 21 28 06" src="https://user-images.githubusercontent.com/16405013/108540768-08819580-72fb-11eb-969d-d9c0525b77cb.png">
<img width="872" alt="Screen Shot 2021-02-19 at 21 27 14" src="https://user-images.githubusercontent.com/16405013/108540778-0a4b5900-72fb-11eb-8703-0d97017af48b.png">

**Comment by Ebazhanov** [comment]
Hello, @mohamedebrahim96! Thank you for your slides and participation! :+1: FYI all the questions was typed in this PR https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/pull/1198 by @lnugraha
and from now they are available here
https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/master/kotlin/kotlin-quiz.md

:love_letter:
